### ISSUE TITLE
missing specific query 4.0.3 - findQueryByAlias

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2315]
Jargon testing with 4.0.3 reveals missing spec query

```
iadmin asq "select alias,sqlStr from R_SPECIFIC_QUERY where alias = ?" findQueryByAlias
```

**Comment by trel** [comment]
still cannot reproduce.

**Comment by michael-conway** [comment]
well, it still happens, fresh install, fresh 4.0.3 vm

jargon unit test

```shell

org.irods.jargon.core.exception.SpecificQueryException: Exception processing specific query
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:186)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:117)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1167)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:621)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:587)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:228)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:129)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:529)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.queryOnAliasGivenDefinition(SpecificQueryAOImpl.java:550)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.executeSpecificQueryUsingAliasWithoutAliasLookup(SpecificQueryAOImpl.java:446)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.findSpecificQueryByAlias(SpecificQueryAOImpl.java:174)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.findSpecificQueryByAlias(SpecificQueryAOImpl.java:136)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.executeSpecificQueryUsingAlias(SpecificQueryAOImpl.java:502)
	at org.irods.jargon.core.pub.CollectionAOImpl.findPermissionForUserGrantedThroughUserGroup(CollectionAOImpl.java:1966)
	at org.irods.jargon.core.pub.CollectionAOImpl.getPermissionViaSpecQueryAsGroupMember(CollectionAOImpl.java:1924)
	at org.irods.jargon.core.pub.CollectionAOImpl.getPermissionForUserName(CollectionAOImpl.java:1907)
	at org.irods.jargon.core.pub.CollectionAOImplTest.testGetPermissionsForCollectionForUserNoUser(CollectionAOImplTest.java:2636)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)



```

**Comment by michael-conway** [comment]
now I'll run add spec query...

```shell

e ?" listQueryByAliasLikelect alias,sqlStr from R_SPECIFIC_QUERY where alias lik
e ?" listQueryByAliasLikelect alias,sqlStr from R_SPECIFIC_QUERY where alias lik
ERROR: rcGeneralAdmin failed with error -816000 CAT_INVALID_ARGUMENT
Level 0: Alias is not unique


```

So the first infocation shows no alias, second run shows it was created 

heh....

**Comment by kellerb** [comment]
Next time you are at RENCI, can we step through this together? This behavior is surprising.
