### ISSUE TITLE
9000 error on various file operations with DataObjInp, testing against 4.1

### ISSUE THREAD

**Issue by michael-conway** [irods/irods#2679]
Hey all,

This is more of a heads-up, it could well be a config error, but various file operations, like this put operation, are failing as follows.  I am looking into this.

```Shell

762  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message:<DataObjInp_PI><objPath>/tempZone/home/test1/jargon-scratch/IRODSFileFactoryAOImplTest/testCreateOutStreamFromFileName.csv</objPath>
<createMode>33188</createMode>
<openFlags>2</openFlags>
<offset>0</offset>
<dataSize>1</dataSize>
<numThreads>0</numThreads>
<oprType>1</oprType>
<KeyValPair_PI><ssLen>3</ssLen>
<keyWord>dataType</keyWord>
<keyWord>dataIncluded</keyWord>
<keyWord>destRescName</keyWord>
<svalue>generic</svalue>
<svalue></svalue>
<svalue>test1-resc</svalue>
</KeyValPair_PI>
</DataObjInp_PI>

762  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - functionID: 606
762  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>508</msgLen><errorLen>0</errorLen><bsLen>1</bsLen><intInfo>606</intInfo></MsgHeader_PI>
762  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - final flush of data sent
762  [main] INFO  org.irods.jargon.core.connection.AbstractConnection  - total sent:1
762  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - data sent, getting response
762  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - reading message from irods
762  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
762  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
762  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  145
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 145
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length:0
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - error length:178
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - bytesLength:0
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - info value:-9000
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - info is < 0
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  178
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
1237 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 178
1237 [main] ERROR org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - IRODS error occured msg : -9000
1237 [main] DEBUG org.irods.jargon.core.connection.IRODSErrorScanner  - inspectAndThrowIfNeeded:-9000
1237 [main] DEBUG org.irods.jargon.core.connection.IRODSErrorScanner  - scanning for info value...
1237 [main] DEBUG org.irods.jargon.core.connection.IRODSErrorScanner  - errorEnum val:SYS_EXCEED_CONNECT_CNT
1238 [main] ERROR org.irods.jargon.core.pub.TransferOperationsHelper  - exception in transfer
org.irods.jargon.core.exception.JargonException: error code received from iRODS:-9000 message:db_mod_data_obj_meta_op - Failed to find file in database by its logical path.
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:194)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:92)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunctionIncludingAllDataInStream(AbstractIRODSMidLevelProtocol.java:398)
	at org.irods.jargon.core.pub.DataAOHelper.processNormalPutTransfer(DataAOHelper.java:477)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putCommonProcessing(DataObjectAOImpl.java:613)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODS(DataObjectAOImpl.java:411)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processPutOfSingleFile(TransferOperationsHelper.java:966)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processPutAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:949)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:798)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:1052)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImplTest.testCreateOutStreamFromFileName(IRODSFileFactoryImplTest.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
1238 [main] WARN  org.irods.jargon.core.pub.TransferOperationsHelper  - exception will be re-thrown, as there is no status callback listener
1238 [main] WARN  org.irods.jargon.core.pub.DataTransferOperationsImpl  - unexpected exception in put operation that should have been caught in the transfer handler
org.irods.jargon.core.exception.JargonException: error code received from iRODS:-9000 message:db_mod_data_obj_meta_op - Failed to find file in database by its logical path.
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:194)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:92)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunctionIncludingAllDataInStream(AbstractIRODSMidLevelProtocol.java:398)
	at org.irods.jargon.core.pub.DataAOHelper.processNormalPutTransfer(DataAOHelper.java:477)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putCommonProcessing(DataObjectAOImpl.java:613)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODS(DataObjectAOImpl.java:411)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processPutOfSingleFile(TransferOperationsHelper.java:966)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processPutAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:949)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:798)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:1052)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImplTest.testCreateOutStreamFromFileName(IRODSFileFactoryImplTest.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
1239 [main] ERROR org.irods.jargon.core.pub.DataTransferOperationsImpl  - exception in transfer
org.irods.jargon.core.exception.JargonException: error code received from iRODS:-9000 message:db_mod_data_obj_meta_op - Failed to find file in database by its logical path.
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:194)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:92)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunctionIncludingAllDataInStream(AbstractIRODSMidLevelProtocol.java:398)
	at org.irods.jargon.core.pub.DataAOHelper.processNormalPutTransfer(DataAOHelper.java:477)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putCommonProcessing(DataObjectAOImpl.java:613)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODS(DataObjectAOImpl.java:411)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processPutOfSingleFile(TransferOperationsHelper.java:966)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processPutAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:949)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:798)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:1052)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImplTest.testCreateOutStreamFromFileName(IRODSFileFactoryImplTest.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
1239 [main] WARN  org.irods.jargon.core.pub.DataTransferOperationsImpl  - exception will be re-thrown, as there is no status callback listener
1246 [main] DEBUG org.irods.jargon.core.connection.IRODSSession  - closing all irods sessions
1246 [main] DEBUG org.irods.jargon.core.connection.IRODSSession  - found and am closing connection to : irods://test1@localhost:1247
1246 [main] DEBUG org.irods.jargon.core.connection.IRODSSimpleProtocolManager  - irodsMidLevelProtocol returned:AbstractIRODSMidLevelProtocol [irodsConnection=irods://test1.tempZone@localhost:1247/tempZone/home/test1/main/1430922405771, irodsProtocolManager=org.irods.jargon.core.connection.IRODSSimpleProtocolManager@6ed3ef1, irodsServerProperties=IRODS server properties
    icat enabled?:ICAT_ENABLED
    Server boot time:1430922396
    Rel version:rods4.1.0
    API version:d
    zone:tempZone
    eirods:true
, irodsSession=org.irods.jargon.core.connection.IRODSSession@2437c6dc, startupResponseData=StartupResponseData:
   status:0
   relVersion:rods4.1.0
   apiVersion:d
   reconnPort:20327
   reconnAddr:irodsLinux




```

**Comment by michael-conway** [comment]
nvm
