### ISSUE TITLE
Investigate external daemonizers

### ISSUE THREAD

**Issue by kellerb** [irods/irods#2774]
The iRODS server currently self-daemonizes.
- `/usr/bin/daemon`
- `systemd`

**Comment by kript** [comment]
As most modern systems use systemd these days (I don't say this is a good thing), how are you expecting people to run things on Centos 7/Ubuntu 16?

I've been hacking together a definitions file, but 3.3.1 (which I have working) is different to 4.1.x it appears, so in case I'm doing something silly...

**Comment by trel** [comment]
Our current state of the world is...

`sudo service irods status|start|stop|restart`
calls
`/etc/init.d/irods`
calls
`/var/lib/irods/irodsctl`
calls
`python /var/lib/irods/scripts/irods_control.py`

**Comment by kript** [comment]
`service` is not guaranteed to work, especially with the fast changing development of systemd, so I'm a little nervous of the backwards compatibility mode of systemd continuing to work, as they like to 'move fast and break things'.

We find we also need to set the dependencies, as systemd's graph walk puts iRODS before our authentication system, an possibly before networking, with predictably dismal results!

I've tried the following which fails as it looks at the wrong output;

```
[Unit]
Description=iRODS 4.1.x
Documentation=<our confluence page>
DefaultDependencies=no
Requires=network.target
Requires=sssd.service
Wants=network-online.target
After=sssd.service
After= network-online.target local-fs.target

[Service]
Type=oneshot
ExecStart=/var/lib/irods/iRODS/irodsctl start
ExecStop=/var/lib/irods/iRODS/irodsctl stop
RemainAfterExit=yes
WorkingDirectory=/usr/local/iRODS/
User={{ irods_system_user }} 
Group=irods

[Install]
WantedBy=multi-user.target
```

and gives;

```
● irods4.service - iRODS 4.1.x
   Loaded: loaded (/etc/systemd/system/irods4.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-04-03 14:04:59 BST; 30s ago
     Docs: https://ssg-confluence.internal.sanger.ac.uk/display/ISG/iRODS
  Process: 198474 ExecStart=/var/lib/irods/iRODS/irodsctl start (code=exited, status=1/FAILURE)
 Main PID: 198474 (code=exited, status=1/FAILURE)
```
but I am probably missing the correct `Type` to set..

**Comment by kript** [comment]
Restarting this investigation, since we need to run 4.1.12 on Bionic, just letting `systemd` try and work it out from `/etc/init.d/irods` we get;

```
Nov 29 15:43:45 our-irods-server systemd[1]: Starting LSB: Manages the iRODS service...
Nov 29 15:43:45 our-irods-server irods[2056]: No passwd entry for user 'irods'
Nov 29 15:43:45 our-irods-server su[2059]: No passwd entry for user 'irods'
Nov 29 15:43:45 our-irods-server su[2059]: FAILED su for irods by root
Nov 29 15:43:45 our-irods-server su[2059]: - ??? root:irods
Nov 29 15:43:45 our-irods-server systemd[1]: irods.service: Control process exited, code=exited status=1
Nov 29 15:43:45 our-irods-server systemd[1]: irods.service: Failed with result 'exit-code'.
Nov 29 15:43:45 our-irods-server systemd[1]: Failed to start LSB: Manages the iRODS service.

```
N.B. it starts fine when done manually with `sudo systemd start irods`
Which looks similar to the reason proposed in this MR I note no further work on https://github.com/irods/irods/pull/3999 so am wondering what the plan is, or what has been done?

**Comment by kript** [comment]
We found that using the packaged init script works on Red Hat 7.4, but on Bionic it starts before `sssd` which we use for NIS equivalent lookips to LDAP et al, so sudo was failing. 

In addition, the use of Systemd allows us to specify it starts _after_ the network and local file systems, as otherwise it will also fail.

Our Ansible template file. We've made an assumption about the group, which might be wrong/not required. Notsure ATM how to handle our sssd requirement in a more general way, as other sites may have similar but different requirements for the start order...

```
[Unit]
Description=iRODS 4.1.X Open Source Data Management Software for user {{ irods_system_user }}
Documentation=https://our-wiki/display/ISG/iRODS
DefaultDependencies=no
After=local-fs.target network.target sssd.target

[Service]
EnvironmentFile=/etc/irods/service_account.config
WorkingDirectory=/var/lib/irods
User={{ irods_system_user }} 
Group=irods
ExecStart=/var/lib/irods/iRODS/irodsctl start
ExecReload=/var/lib/irods/iRODS/irodsctl restart
ExecStop=/var/lib/irods/iRODS/irodsctl stop
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=forking

[Install]
WantedBy=multi-user.target
Alias=irods.service
```
Also note this is for 4.1.X as 4.2.x has `irodsctl` in a different location

**Comment by kript** [comment]
After some further yak shaving we got the service file reduced, and interestingly,this worked on a system without `sssd` installed,but did leave this in the list of services;
`● sssd.target                                                 not-found inactive dead      sssd.target `

```
Description=iRODS 4.1.X Open Source Data Management Software for user {{ irods_system_user }}
Documentation=https://our-wiki/display/ISG/iRODS
After=local-fs.target network.target sssd.target

[Service]
WorkingDirectory=/var/lib/irods
User={{ irods_system_user }} 
Group={{ irods_system_group }}
ExecStart=/var/lib/irods/iRODS/irodsctl start
ExecReload=/usr/bin/touch /etc/irods/core.re
ExecStop=/var/lib/irods/iRODS/irodsctl stop
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=forking

[Install]
WantedBy=multi-user.target
```

**Comment by kript** [comment]
With the announcement that 4.2.8 will support Ubuntu 18.04, will this be looked at further? We still need to be able to set the service precedence, otherwise the service will fail to start on reboot.

Our current systemd file;
```
[Unit]
Description=iRODS 4.X Open Source Data Management Software for user {{ irods_system_user }}
Documentation=<our confluence>
Wants=sssd.service
After=local-fs.target network.target sssd.service

[Service]
WorkingDirectory=/var/lib/irods
User={{ irods_system_user }} 
Group={{ irods_system_group }}
Environment="PATH=/bin:/usr/bin:/usr/sbin:/var/lib/irods:/var/lib/irods/iRODS"
{% if ansible_distribution == 'Ubuntu' -%}
Environment="LD_LIBRARY_PATH=/usr/lib/oracle/11.1/client64/lib"
{% endif -%}
ExecStart=/bin/bash -c "irodsctl start"
ExecReload=/usr/bin/touch /etc/irods/core.re
ExecStop=/bin/bash -c "irodsctl stop"
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=forking

[Install]
WantedBy=multi-user.target
```
Doesn't set a `PIDFile=` (recommended by `Type=forking`) which we think is causing other issues for systemd to determine if the service is up, in part because there are two rodsServer processes started.

**Comment by mcv21** [comment]
There's a problem with iRODS starting two processes; sometimes (I'm finding it hard to reproduce, but we keep seeing it) if one process ABRTs systemd doesn't try and stop the service, instead trying to start it up and failing because there's still a process left over from last time:
```
May 16 01:36:58 irods-hum-sr04 systemd[1]: irods.service: Main process exited, code=killed, status=6/ABRT
May 16 01:36:58 irods-hum-sr04 systemd[1]: irods.service: Failed with result 'signal'.
May 16 01:36:58 irods-hum-sr04 systemd[1]: irods.service: Service hold-off time over, scheduling restart.
May 16 01:36:58 irods-hum-sr04 systemd[1]: irods.service: Scheduled restart job, restart counter is at 1.
May 16 01:36:58 irods-hum-sr04 systemd[1]: Stopped iRODS 4.X Open Source Data Management Software for user irods.
May 16 01:36:58 irods-hum-sr04 systemd[1]: irods.service: Found left-over process 51094 (irodsServer) in control group while starting unit. Ignoring.
May 16 01:36:58 irods-hum-sr04 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
May 16 01:36:58 irods-hum-sr04 systemd[1]: Starting iRODS 4.X Open Source Data Management Software for user irods...
May 16 01:37:01 irods-hum-sr04 bash[6384]: Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
May 16 01:37:01 irods-hum-sr04 bash[6384]: Validating [/var/lib/irods/VERSION.json]... Success
May 16 01:37:02 irods-hum-sr04 bash[6384]: Validating [/etc/irods/server_config.json]... Success
May 16 01:37:02 irods-hum-sr04 bash[6384]: Validating [/etc/irods/host_access_control_config.json]... Success
May 16 01:37:02 irods-hum-sr04 bash[6384]: Validating [/etc/irods/hosts_config.json]... Success
May 16 01:37:03 irods-hum-sr04 bash[6384]: Error encountered running irods_control start:
May 16 01:37:03 irods-hum-sr04 bash[6384]: Traceback (most recent call last):
May 16 01:37:03 irods-hum-sr04 bash[6384]:   File "/var/lib/irods/scripts/irods_control.py", line 116, in main
May 16 01:37:03 irods-hum-sr04 bash[6384]:     operations_dict[operation]()
May 16 01:37:03 irods-hum-sr04 bash[6384]:   File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
May 16 01:37:03 irods-hum-sr04 bash[6384]:     operations_dict['start'] = lambda: irods_controller.start()
May 16 01:37:03 irods-hum-sr04 bash[6384]:   File "/var/lib/irods/scripts/irods/controller.py", line 48, in start
May 16 01:37:03 irods-hum-sr04 bash[6384]:     raise IrodsError('iRODS already running')
May 16 01:37:03 irods-hum-sr04 bash[6384]: IrodsError: iRODS already running
May 16 01:37:03 irods-hum-sr04 bash[6384]: Exiting...
May 16 01:37:03 irods-hum-sr04 systemd[1]: irods.service: Control process exited, code=exited status=1
May 16 01:37:03 irods-hum-sr04 systemd[1]: irods.service: Failed with result 'exit-code'.
May 16 01:37:03 irods-hum-sr04 systemd[1]: Failed to start iRODS 4.X Open Source Data Management Software for user irods.
```

In testing, there is a stop action, so it's not quite clear why this doesn't happen in some cases - it maybe that the failure is while the other process is busy (I've noticed that irodsctl attempts and fails a clean shutdown on those machines and has to kill the process) and that isn't sufficiently replicated by starting the unit and kill -ABRT one of the processes. Here's what a test that does restart OK looks like:
```
May 19 11:14:22 irods-cgp-sr15-dev systemd[1]: Started iRODS 4.X Open Source Data Management Software for user irods-cgp.
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: irods.service: Main process exited, code=killed, status=6/ABRT
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: irods.service: Failed with result 'signal'.
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: irods.service: Service hold-off time over, scheduling restart.
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: irods.service: Scheduled restart job, restart counter is at 1.
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: Stopped iRODS 4.X Open Source Data Management Software for user irods-cgp.
May 19 11:16:35 irods-cgp-sr15-dev systemd[1]: Starting iRODS 4.X Open Source Data Management Software for user irods-cgp...
May 19 11:16:36 irods-cgp-sr15-dev bash[48822]: Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
May 19 11:16:36 irods-cgp-sr15-dev bash[48822]: Validating [/var/lib/irods/VERSION.json]... Success
May 19 11:16:37 irods-cgp-sr15-dev bash[48822]: Validating [/etc/irods/server_config.json]... Success
May 19 11:16:37 irods-cgp-sr15-dev bash[48822]: Validating [/etc/irods/host_access_control_config.json]... Success
May 19 11:16:38 irods-cgp-sr15-dev bash[48822]: Validating [/etc/irods/hosts_config.json]... Success
May 19 11:16:38 irods-cgp-sr15-dev bash[48822]: Starting iRODS server...
May 19 11:16:39 irods-cgp-sr15-dev bash[48822]: Success
May 19 11:16:39 irods-cgp-sr15-dev systemd[1]: Started iRODS 4.X Open Source Data Management Software for user irods-cgp.
```

It's possible that setting `KillMode=cgroup` would catch this.

**Comment by mcv21** [comment]
Right, I have a reproducer, and a probable fix.
First, to reproduce:
1) start irods using systemd (and this unit file); run systemctl status:
```
root@irods-cgp-sr15-dev:~# systemctl status irods
● irods.service - iRODS 4.X Open Source Data Management Software for user irods-cgp
   Loaded: loaded (/etc/systemd/system/irods.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2020-05-19 11:16:39 BST; 4min 18s ago
     Docs: https://ssg-confluence.internal.sanger.ac.uk/display/ISG/iRODS
  Process: 48822 ExecStart=/bin/bash -c irodsctl start (code=exited, status=0/SUCCESS)
 Main PID: 48869 (irodsServer)
    Tasks: 11 (limit: 8601)
   CGroup: /system.slice/irods.service
           ├─48869 /usr/sbin/irodsServer
           └─48870 /usr/sbin/irodsServer
```
2. Attach `gdb` to the second process (`gdb /usr/sbin/irodsServer -p 48870`)
3. Send SIGABRT to the first process (`kill -ABRT 48869`)
4.Now you will observe systemd try and fail to start iRODS up again, complaining about the live process - e.g. with `journalctl -u irods.service`:
```
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: irods.service: Main process exited, code=killed, status=6/ABRT
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: irods.service: Failed with result 'signal'.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: irods.service: Service hold-off time over, scheduling restart.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: irods.service: Scheduled restart job, restart counter is at 2.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: Stopped iRODS 4.X Open Source Data Management Software for user irods-cgp.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: irods.service: Found left-over process 48870 (irodsServer) in control group while starting unit. Ignoring.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
May 19 11:22:12 irods-cgp-sr15-dev systemd[1]: Starting iRODS 4.X Open Source Data Management Software for user irods-cgp...
May 19 11:22:13 irods-cgp-sr15-dev bash[49320]: Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
May 19 11:22:14 irods-cgp-sr15-dev bash[49320]: Validating [/var/lib/irods/VERSION.json]... Success
May 19 11:22:14 irods-cgp-sr15-dev bash[49320]: Validating [/etc/irods/server_config.json]... Success
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: Validating [/etc/irods/host_access_control_config.json]... Success
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: Validating [/etc/irods/hosts_config.json]... Success
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: Error encountered running irods_control start:
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: Traceback (most recent call last):
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:   File "/var/lib/irods/scripts/irods_control.py", line 116, in main
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:     operations_dict[operation]()
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:   File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:     operations_dict['start'] = lambda: irods_controller.start()
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:   File "/var/lib/irods/scripts/irods/controller.py", line 48, in start
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]:     raise IrodsError('iRODS already running')
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: IrodsError: iRODS already running
May 19 11:22:15 irods-cgp-sr15-dev bash[49320]: Exiting...
May 19 11:22:15 irods-cgp-sr15-dev systemd[1]: irods.service: Control process exited, code=exited status=1
May 19 11:22:15 irods-cgp-sr15-dev systemd[1]: irods.service: Failed with result 'exit-code'.
May 19 11:22:15 irods-cgp-sr15-dev systemd[1]: Failed to start iRODS 4.X Open Source Data Management Software for user irods-cgp.
```

To compare, if I set `KillMode=control-group` in the unit file, and perform the analogous steps, systemd waits (by default 90s) for the other process to die, then sends it a SIGKILL, after which it can start iRODS up OK:
```
May 19 11:26:23 irods-cgp-sr15-dev systemd[1]: irods.service: Main process exited, code=killed, status=6/ABRT
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: irods.service: State 'stop-sigterm' timed out. Killing.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: irods.service: Killing process 49552 (irodsServer) with signal SIGKILL.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: irods.service: Failed with result 'signal'.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: irods.service: Service hold-off time over, scheduling restart.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: irods.service: Scheduled restart job, restart counter is at 1.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: Stopped iRODS 4.X Open Source Data Management Software for user irods-cgp.
May 19 11:27:53 irods-cgp-sr15-dev systemd[1]: Starting iRODS 4.X Open Source Data Management Software for user irods-cgp...
May 19 11:27:54 irods-cgp-sr15-dev bash[49658]: Validating [/usr/local/iRODS/.irods/irods_environment.json]... Success
May 19 11:27:55 irods-cgp-sr15-dev bash[49658]: Validating [/var/lib/irods/VERSION.json]... Success
May 19 11:27:56 irods-cgp-sr15-dev bash[49658]: Validating [/etc/irods/server_config.json]... Success
May 19 11:27:56 irods-cgp-sr15-dev bash[49658]: Validating [/etc/irods/host_access_control_config.json]... Success
May 19 11:27:56 irods-cgp-sr15-dev bash[49658]: Validating [/etc/irods/hosts_config.json]... Success
May 19 11:27:57 irods-cgp-sr15-dev bash[49658]: Starting iRODS server...
May 19 11:27:58 irods-cgp-sr15-dev bash[49658]: Success
May 19 11:27:58 irods-cgp-sr15-dev systemd[1]: Started iRODS 4.X Open Source Data Management Software for user irods-cgp.
```

**Comment by trel** [comment]
3.5y update from @kript ... from https://groups.google.com/g/irod-chat/c/uZpNuQn6ytw/m/X0Pa4-eNAQAJ


> If it helps, this is the Jinja2 template we deploy via ansible;
> 
> ```
> [Unit]
> Description=iRODS 4.X Open Source Data Management Software for user {{ irods_system_user }}
> Documentation=https://ourconfluence/display/ISG/iRODS
> Wants=sssd.service
> After=local-fs.target network.target sssd.service
> 
> [Service]
> WorkingDirectory=/var/lib/irods
> User={{ irods_system_user }}
> Group={{ irods_system_group }}
> Environment="PATH=/bin:/usr/bin:/usr/sbin:/var/lib/irods:/var/lib/irods/iRODS"
> {% if ansible_distribution == 'Ubuntu' -%}
> Environment="LD_LIBRARY_PATH=/usr/lib/oracle/11.1/client64/lib"
> {% endif -%}
> ExecStart=/bin/bash -c "irodsctl start"
> ExecReload=/usr/bin/touch /etc/irods/[core.re](http://core.re/)
> ExecStop=/bin/bash -c "irodsctl stop"
> LimitNOFILE=131072
> KillMode=control-group
> Restart=on-failure
> RestartPreventExitStatus=255
> Type=forking
> 
> [Install]
> WantedBy=multi-user.target
> ```
> A few issues we hit;
> 1. if you are using unixfilesystem resources, you need the local-fs.target to be started first
> 2. you need whatever name service (in our case sssd) to start first or iRODS cant look up its service account etc
> 3. the file descriptor count needs bumping from the default if you have lots of connections
> 4. (This is valid for 4.2, might not be valid for 4.3);
> Starting with iRODS 4.2, iRODS starts two server processes. If the Main
>     PID fails but the other process doesn't, then systemd tries to start
>     up the unit again (while warning about the still-running process)
>     which fails because iRODS won't start when there's still and
>     irodsServer process extant.
>    
>     Setting KillMode to control-group means in this situation that systemd
>     will send a SIGTERM to the other process then after 90s send it a
>     SIGKILL; and then can successfully start iRODS up again.
>    
>     There's an upstream issue with further details:
>     https://github.com/irods/irods/issues/2774
> 5. we no longer use Oracle, but we found environment handling iffy, especially if you're deploying it to multiple OS's, hence our LD_LIBRARY_PATH
> 6. we found systemd didn't actually honour the $PATH, hence using bash. That was three years ago and 18.04, things may have improved since.
> 7. On Red Hat, the init  'emulator' version runs OK, but on Bionic it runs before sssd, and hence fails to use sudo.

**Comment by trel** [comment]
4.3 now properly handles the parent/child process tracking (number 4 above) and should be mitigated.

**Comment by korydraughn** [comment]
Related to #7229.

Pulled into 5.0.0 milestone.

**Comment by korydraughn** [comment]
The redesign work in #7988 made iRODS 5 compatible with systemd.
