### ISSUE TITLE
Configuration problem:     Communications with the database failed.         Segmentation fault (core dumped)* after ICAT DB population aftrer running setup_irods.sh

### ISSUE THREAD

**Issue by anjum11** [irods/irods#3429]
Hi all,

We had been looking into this error which we got after executing the `setup_irods.sh`.

```
****Configuration problem:
    Communications with the database failed.
        Segmentation fault (core dumped)****
```

We tried to use gdb debugging upon the execution of `test_cll` which is throwing this error and found this backtrace.

```
Starting program: /var/lib/irods/iRODS/server/test/bin/test_cll irods irods
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
userName=irods
password=irods

Program received signal SIGSEGV, Segmentation fault.
__lll_unlock_elision (lock=0x7ffff76c7480, private=0) at ../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
29    ../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.
(gdb) bt
#0  __lll_unlock_elision (lock=0x7ffff76c7480, private=0) at ../nptl/sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
#1  0x00007ffff74a5417 in ?? () from /usr/lib/x86_64-linux-gnu/libodbc.so.1
#2  0x00007ffff747da48 in ?? () from /usr/lib/x86_64-linux-gnu/libodbc.so.1
#3  0x00007ffff746ec80 in ?? () from /usr/lib/x86_64-linux-gnu/libodbc.so.1
#4  0x00007ffff747091d in SQLConnect () from /usr/lib/x86_64-linux-gnu/libodbc.so.1
#5  0x000000000045deb3 in cllConnect (icss=icss@entry=0x7fffffffdb60) at ../src/low_level_odbc.cpp:183
#6  0x000000000045f28d in cllTest (userArg=0x7fffffffe2a4 "irods", pwArg=0x7fffffffe2aa "irods") at ../src/low_level_odbc.cpp:1063
#7  0x00007ffff6337ec5 in __libc_start_main (main=0x4464b0 <main(int, char**)>, argc=3, argv=0x7fffffffdef8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdee8) at libc-start.c:287
#8  0x000000000045cf07 in _start ()
(gdb) q
A debugging session is active.

    Inferior 1 [process 3075] will be killed.
```

The backtrace mentions `low_level_odbc.cpp` but we were not able to find it in the folder:

`/var/lib/irods/plugins/database/src/low_level_odbc.cpp`, is this the issue which results in our inability to progress further with the installation? Could you please share your thoughts upon this?

**Comment by kellerb** [comment]
Which version of iRODS is this?
Which OS and OS version?
How was iRODS installed? (built from source, installed from packages.irods.org repo, etc.)
Which flavor of database are you using?
