### ISSUE TITLE
iRODS rule language tuple issue causes irodsReServer to silently die.

### ISSUE THREAD

**Issue by tedgin** [irods/irods#3629]
I'm using version 4.1.10 of iRODS.

I have created the custom rules file ipc-repl.re that is configured to load before core.re. Here's the server_config.json entry.

```
  "re_rulebase_set": [
    { "filename": "ipc-repl" },
    { "filename": "core" }
  ],
```

Here's the contents of ipc-repl.re

```
_mvReplicas(*ReplResc) {
  if (true) {}
  (*replName, *replRequired) = *ReplResc;
}
```

After using `irodsctl start` to start the iRODS, the irodsReServer process isn't present, and there is nothing in the logs.

If either one of the statements in `_mvReplicas` is removed, irodsReServer starts.  Also if a `;` is added between the statements, irodsReServer starts.

**Comment by trel** [comment]
I have replicated the report.

When putting the above `_mvReplicas()` at the top of `core.re` directly, the following is in the `rodsLog*` on an initial startup:
```
Aug 17 20:10:09 pid:20941 NOTICE: rodsServer Release version rods4.1.10 - API Version d is up
Aug 17 20:10:09 pid:20943 NOTICE: Starting irodsReServer
Aug 17 20:10:09 pid:20941 ERROR: server_control_executor - icat_host_name is localhost, not a fqdn
Aug 17 20:10:09 pid:20941 NOTICE: >>> control plane :: listening on port 1248
Aug 17 20:10:09 pid:20941 NOTICE: Agent process 20943 exited with status 139 but not in queue
```
There is nothing in the `reLog*`.

**Comment by trel** [comment]
Duplicated in 4.2.1 as well.     Feels like a parsing bug.

Console shows:
```
$ sudo service irods start
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Ensuring catalog schema is up-to-date...
Catalog schema is up-to-date.
Starting iRODS server...
Failure
Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 115, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 121, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 115, in start
    raise IrodsError('iRODS server failed to start.')
IrodsError: iRODS server failed to start.
Exiting...
```

`rodsLog*` only has two new lines:
```
Aug 17 20:32:58 pid:24078 NOTICE: Agent factory process pid = [24079]
Aug 17 20:32:59 pid:24079 NOTICE: The rodsServer socket peer has shut down
```

**Comment by trel** [comment]
This works fine in both 4.1.10 and 4.2.1:
```
_mvReplicas(*ReplResc) {
  if (true) {}
  *a=""
}
```
