### ISSUE TITLE
Error when "yum erase irods-server" if didn't run setup script

### ISSUE THREAD

**Issue by kellerb** [irods/irods#3646]
On CentOS 7:
```
$ sudo yum erase irods-server
Loaded plugins: fastestmirror, priorities
Resolving Dependencies
--> Running transaction check
---> Package irods-server.x86_64 0:4.2.1-1 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

==================================================================
 Package                Arch      Version     Repository     Size
==================================================================
Removing:
 irods-server           x86_64    4.2.1-1     @renci-irods   16 M

Transaction Summary
==================================================================
Remove  1 Package

Installed size: 16 M
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Stopping iRODS :: /var/lib/irods/irodsctl stop
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 42, in <module>
    wrap_if_necessary()
  File "/var/lib/irods/scripts/irods_control.py", line 21, in wrap_if_necessary
    with open(irods.paths.server_config_path()) as server_config_path:
IOError: [Errno 2] No such file or directory: '/etc/irods/server_config.json'
NOTE :: The Local System Administrator should delete these if necessary.
     :: Leaving root Service Account in place.
     :: try:
     ::      sudo /usr/sbin/userdel root
  Erasing    : irods-server-4.2.1-1.x86_64                    1/1
  Verifying  : irods-server-4.2.1-1.x86_64                    1/1

Removed:
  irods-server.x86_64 0:4.2.1-1

Complete!
```

**Comment by SwooshyCueb** [comment]
This also affects debian packages when upgrading without ever setting up irods.
It can safely be ignored, so fixing this is low priority for now IMO
