### ISSUE TITLE
occasional test failure in Test_Native_Rule_Engine_Plugin.test_network_pep

### ISSUE THREAD

**Issue by trel** [irods/irods#3689]
irods.test.test_native_rule_engine_plugin.Test_Native_Rule_Engine_Plugin.test_network_pep

Sometimes, an assertion error occurs:

```
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_native_rule_engine_plugin.py", line 45, in test_network_pep
    self.helper_test_pep(rule_texts[self.plugin_name][self.class_name][inspect.currentframe().f_code.co_name], "iput -f --metadata ATTR;VALUE;UNIT "+self.testfile)
  File "/var/lib/irods/scripts/irods/test/test_native_rule_engine_plugin.py", line 42, in helper_test_pep
    assert number_of_strings_to_look_for == count, 'Found {0} instead of {1} occurrences of {2}'.format(count, number_of_strings_to_look_for, s)
AssertionError: Found 2 instead of 1 occurrences of THIS IS AN OUT VARIABLE
```

**Comment by tempoz** [comment]
Just saw this on ub16 oracle
