### ISSUE TITLE
iRODS setup failed with MySQL 5.6 on CentOS 7.2

### ISSUE THREAD

**Issue by lanjiantm** [irods/irods#3694]
Environment:

- CentOS 7.2
- iRODS 4.2.1
- MySQL Server Community 5.6 : InnoDB engine, utf8 charset, utf8_general_ci collation
- Python 2.7.5

Run 'python /var/lib/irods/scripts/setup_irods.py' to setup.

1. First try

When run:

`create table R_RULE_MAIN ( rule_id bigint not null, rule_version varchar(250) DEFAULT '0', rule_base_name varchar(250) not null, rule_name varchar(2700) not null, rule_event varchar(2700) not null, rule_condition varchar(2700), rule_body varchar(2700) not null, rule_recovery varchar(2700) not null, rule_status bigint DEFAULT 1, rule_owner_name varchar(250) not null, rule_owner_zone varchar(250) not null, rule_descr_1 varchar(2700), rule_descr_2 varchar(2700), input_params text, output_params text, dollar_vars text, icat_elements text, sideeffects text, r_comment text, create_ts varchar(32), modify_ts varchar(32)) ;`

Error:

`Listing database tables...
Defining mysql functions...
Creating database tables...
Traceback (most recent call last):
  File "setup_irods.py", line 448, in <module>
    sys.exit(main())
  File "setup_irods.py", line 436, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "setup_irods.py", line 123, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 23, in setup_catalog
    database_connect.create_database_tables(irods_config, cursor)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 327, in create_database_tables
    execute_sql_file(sql_file, cursor, by_line=True)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 231, in execute_sql_file
    cursor.execute(line)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 1608, in execute
    self.execdirect(query_string)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 1634, in execdirect
    check_success(self, ret)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 986, in check_success
    ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 964, in ctrl_err
    raise Error(state,err_text)
irods.pypyodbc.Error: ('HY000', '[HY000] [MySQL][ODBC 5.2(w) Driver][mysqld-5.6.38]Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')`

**Changed some `varchar(2700)` to `text` in `create table R_RULE_MAIN` statement, and try again.**

2. Second try

Table `R_RULE_MAIN` created after modification.

But when run:

`create unique index idx_coll_main3 on R_COLL_MAIN (coll_name (767));`

Error:

`
Listing database tables...
Defining mysql functions...
Creating database tables...
Traceback (most recent call last):
  File "setup_irods.py", line 448, in <module>
    sys.exit(main())
  File "setup_irods.py", line 436, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "setup_irods.py", line 123, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 23, in setup_catalog
    database_connect.create_database_tables(irods_config, cursor)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 327, in create_database_tables
    execute_sql_file(sql_file, cursor, by_line=True)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 231, in execute_sql_file
    cursor.execute(line)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 1608, in execute
    self.execdirect(query_string)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 1634, in execdirect
    check_success(self, ret)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 986, in check_success
    ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 964, in ctrl_err
    raise Error(state,err_text)
irods.pypyodbc.Error: ('HY000', '[HY000] [MySQL][ODBC 5.2(w) Driver][mysqld-5.6.38]Specified key was too long; max key length is 767 bytes')
`

Give up.

**Comment by alanking** [comment]
Please try this again on a more recent iRODS release to see if things have been resolved. If not, please open a new issue.
