### ISSUE TITLE
Failure to find PID age in resource server topology test

### ISSUE THREAD

**Issue by alanking** [irods/irods#3777]
When running tests on a resource server in a topology (same test as described in #3775), a silent failure seems to occur when finding the PID age at a few points when the tests **passed.** rodsServerLog in all the resource servers and iCAT contain messages similar to the following:
```
Traceback (most recent call last):
  File "/var/lib/irods/scripts/pid_age.py", line 13, in <module>
    p = psutil.Process(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 232, in __init__
    raise NoSuchProcess(pid, None, 'no process found with pid %s' % pid)
psutil._error.NoSuchProcess: no process found with pid 8235
Jan  3 22:49:14 pid:2558 remote addresses: 172.25.14.58 ERROR: [-]      /tmp/tmp19pXM6/server/core/src/irods_server_control_plane.cpp:367:int irods::get_pid_age(pid_t) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
        [-]     /tmp/tmp19pXM6/server/core/src/miscServerFunct.cpp:3079:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
```
iCAT had 3 failures. Resource servers had 2 failures each.

**Comment by trel** [comment]
Is there a way to find out what PID 8235 was?  And what it was supposed to be doing?

**Comment by trel** [comment]
The control plane is removed in iRODS 5.0.0.   Closing.
