### ISSUE TITLE
iRODS setup fails with MySQL 8.0 on RHEL7.6

### ISSUE THREAD

**Issue by nearodney** [irods/irods#4169]
### iRODS Version, OS and Version
iRODS Version: 4.2.4-1
OS: Red Hat Enterprise Linux Server 7.6
MySQL Server version: 8.0.13 MySQL Community Server
Python: 3.7.1
Anaconda: conda 4.5.11
ODBC version: mysql-connector-odbc-8.0.13-1.el7.x86_64

### What did you try to do?
After creating the database and user, I executed the iRODS setup script.
Using Python 3.7, the setup script failed to create the iRODS ICAT schema on MySQL by invoking the setup script and answering the setup questions.

### Expected behavior
Expected the script output shown on page 13 of setting up the iRODS server, from https://github.com/irods/irods_training/blob/master/beginner/irods_beginner_training_2018.pdf.

### Observed behavior (including steps to reproduce, if applicable)

As root:
python /var/lib/irods/scripts/setup_irods.py

The iRODS setup script fails and exits at the point of creating the database schema with the following Python error trace output to the console:

```
Listing database tables...
Defining mysql functions...
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 449, in <module>
    sys.exit(main())
  File "/var/lib/irods/scripts/setup_irods.py", line 437, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "/var/lib/irods/scripts/setup_irods.py", line 124, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 26, in setup_catalog
    database_connect.create_database_tables(irods_config, cursor)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 325, in create_database_tables
    '='.join(['host', irods_config.database_config['db_host']])
  File "/root/anaconda3/envs/py37/lib/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

The output log, from setup_log.txt, does not log the Python TypeError shown at the console:

```
+--------------------------------+
| Setting up the service account |
+--------------------------------+

2018-11-05 22:13:52,675 -    INFO -                 setup_irods.py: 209 - Existing Group Detected: irods
2018-11-05 22:13:52,675 -   DEBUG -                         lib.py:  56 - Calling ['id', 'irods'] with options:
{'shell': False, 'stderr': -1, 'stdout': -1}
2018-11-05 22:13:52,681 -   DEBUG -                         lib.py: 129 - Command ['id', 'irods'] returned with code 0.
stdout:
  uid=986(irods) gid=980(irods) groups=980(irods)
2018-11-05 22:13:52,681 -    INFO -                 setup_irods.py: 224 - Existing Account Detected: irods
2018-11-05 22:13:52,683 -    INFO -                 setup_irods.py: 231 - Setting owner of /var/lib/irods to irods:irods
2018-11-05 22:13:52,763 -    INFO -                 setup_irods.py: 242 - Setting owner of /etc/irods to irods:irods
2018-11-05 22:13:52,764 -   DEBUG -                 setup_irods.py: 252 - Setting uid bit on /var/lib/irods/clients/bin/genOSAuth
2018-11-05 22:13:52,766 -   DEBUG -                         lib.py:  56 - Calling ['su', '-', 'irods', '-c', 'python -c "from __future__ import print_function; import os; import json; print(json.dumps(dict(os.environ)))"'] with options:
{'shell': False, 'stderr': -1, 'stdout': -1}
2018-11-05 22:13:52,900 -   DEBUG -                         lib.py: 129 - Command ['su', '-', 'irods', '-c', 'python -c "from __future__ import print_function; import os; import json; print(json.dumps(dict(os.environ)))"'] returned with code 0.
stdout:
  {"PERL_MM_OPT": "INSTALL_BASE=/var/lib/irods/perl5", "LESSOPEN": "||/usr/bin/lesspipe.sh %s", "PERL_LOCAL_LIB_ROOT": ":/var/lib/irods/perl5", "LOGNAME": "irods", "USER": "irods", "PATH": "/usr/lib64/qt-3.3/bin:/var/lib/irods/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin", "XDG_VTNR": "1", "HOME": "/var/lib/irods", "LANG": "en_US.UTF-8", "QTLIB": "/usr/lib64/qt-3.3/lib", "TERM": "xterm-256color", "SHELL": "/bin/bash", "QTINC": "/usr/lib64/qt-3.3/include", "HISTSIZE": "1000", "QT_PLUGIN_PATH": "/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins", "PERL5LIB": "/var/lib/irods/perl5/lib/perl5:", "SHLVL": "1", "QT_GRAPHICSSYSTEM_CHECKED": "1", "XDG_SESSION_ID": "19", "_": "/bin/python", "KDEDIRS": "/usr", "HOSTNAME": "cos75-rnh1.lanl.gov", "HISTCONTROL": "ignoredups", "XDG_DATA_DIRS": "/var/lib/irods/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share", "PWD": "/var/lib/irods", "PERL_MB_OPT": "--install_base /var/lib/irods/perl5", "MAIL": "/var/spool/mail/irods", "LS_COLORS": "rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:", "QTDIR": "/usr/lib64/qt-3.3", "XDG_SEAT": "seat0"}
2018-11-05 22:13:52,901 -   DEBUG -               configuration.py: 439 - Loading /etc/irods/server_config.json into dictionary
2018-11-05 22:13:52,902 -   DEBUG -                         lib.py: 495 - iRODS server's role:
1. provider
2. consumer
Please select a number or choose 0 to enter a new value [1]: 
2018-11-05 22:13:53,713 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:53,714 -    INFO -               configuration.py: 288 - Updating /etc/irods/server_config.json...
2018-11-05 22:13:53,738 -    INFO -                 setup_irods.py: 115 - 
+-----------------------------------------+
| Configuring the database communications |
+-----------------------------------------+

2018-11-05 22:13:53,744 -   DEBUG -          database_interface.py:  97 - setup_database_config has been called with database type 'mysql'.
2018-11-05 22:13:53,744 -    INFO -          database_interface.py:  99 - You are configuring an iRODS database plugin. The iRODS server cannot be started until its database has been properly configured.

2018-11-05 22:13:53,744 -   DEBUG -                         lib.py:  56 - Calling ['odbcinst', '-q', '-d'] with options:
{'shell': False, 'stderr': -1, 'stdout': -1}
2018-11-05 22:13:53,748 -   DEBUG -                         lib.py: 129 - Command ['odbcinst', '-q', '-d'] returned with code 0.
stdout:
  [PostgreSQL]
  [MySQL]
  [MySQL ODBC 8.0 Unicode Driver]
  [MySQL ODBC 8.0 ANSI Driver]
2018-11-05 22:13:53,749 -   DEBUG -                         lib.py: 495 - ODBC driver for mysql:
1. MySQL
2. MySQL ODBC 8.0 Unicode Driver
3. MySQL ODBC 8.0 ANSI Driver
Please select a number or choose 0 to enter a new value [1]: 
2018-11-05 22:13:54,825 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:54,825 -   DEBUG -                         lib.py: 495 - Database server's hostname or IP address [localhost]: 
2018-11-05 22:13:55,897 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:55,897 -   DEBUG -                         lib.py: 495 - Database server's port [3306]: 
2018-11-05 22:13:56,673 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:56,673 -   DEBUG -                         lib.py: 495 - Database name [ICAT]: 
2018-11-05 22:13:57,376 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:57,377 -   DEBUG -                         lib.py: 495 - Database username [irods]: 
2018-11-05 22:13:58,313 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:58,313 -   DEBUG -                         lib.py: 495 - 
-------------------------------------------
Database Type: mysql
ODBC Driver:   MySQL
Database Host: localhost
Database Port: 3306
Database Name: ICAT
Database User: irods
-------------------------------------------

Please confirm [yes]: 
2018-11-05 22:13:58,905 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:13:58,905 -   DEBUG -                         lib.py: 495 - Database password: 
2018-11-05 22:14:02,505 -    INFO -               configuration.py: 288 - Updating /etc/irods/server_config.json...
2018-11-05 22:14:02,510 -   DEBUG -                         lib.py:  56 - Calling ['odbcinst', '-i', '-s', '-h', '-r'] with options:
{'env': 'HIDDEN', 'shell': False, 'stderr': -1, 'stdin': -1, 'stdout': -1}
2018-11-05 22:14:02,517 -   DEBUG -                         lib.py: 129 - Command ['odbcinst', '-i', '-s', '-h', '-r'] returned with code 0.
stdin:
  [iRODS Catalog]
  Driver=MySQL
  Option=2
  Description=iRODS catalog
  Server=localhost
  Port=3306
  Database=ICAT
stdout:
  odbcinst: Sections and Entries from stdin have been added to ODBC.INI
2018-11-05 22:14:02,539 -    INFO -            database_connect.py: 260 - Listing database tables...
2018-11-05 22:14:02,541 -   DEBUG -            database_connect.py: 262 - List of tables:
[]
2018-11-05 22:14:02,541 -   DEBUG -                         lib.py: 495 - Salt for passwords stored in the database: 
2018-11-05 22:14:05,241 -    INFO -               configuration.py: 288 - Updating /etc/irods/server_config.json...
2018-11-05 22:14:05,243 -    INFO -                 setup_irods.py: 268 - 
+--------------------------------+
| Configuring the server options |
+--------------------------------+

2018-11-05 22:14:05,245 -   DEBUG -               configuration.py: 439 - Loading /etc/irods/server_config.json into dictionary
2018-11-05 22:14:05,245 -   DEBUG -                         lib.py: 495 - iRODS server's zone name [tempZone]: 
2018-11-05 22:14:06,169 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:06,176 -   DEBUG -                         lib.py: 495 - iRODS server's port [1247]: 
2018-11-05 22:14:06,864 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:06,864 -   DEBUG -                         lib.py: 495 - iRODS port range (begin) [20000]: 
2018-11-05 22:14:07,241 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:07,241 -   DEBUG -                         lib.py: 495 - iRODS port range (end) [20199]: 
2018-11-05 22:14:07,601 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:07,601 -   DEBUG -                         lib.py: 495 - Control Plane port [1248]: 
2018-11-05 22:14:07,992 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:07,993 -   DEBUG -                         lib.py: 495 - Schema Validation Base URI (or off) [file:///var/lib/irods/configuration_schemas]: 
2018-11-05 22:14:08,929 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:08,929 -   DEBUG -                         lib.py: 495 - iRODS server's administrator username [rods]: 
2018-11-05 22:14:09,897 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:09,897 -   DEBUG -                         lib.py: 495 - 
-------------------------------------------
Zone name:                  tempZone
iRODS server port:          1247
iRODS port range (begin):   20000
iRODS port range (end):     20199
Control plane port:         1248
Schema validation base URI: file:///var/lib/irods/configuration_schemas
iRODS server administrator: rods
-------------------------------------------

Please confirm [yes]: 
2018-11-05 22:14:10,817 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:10,817 -   DEBUG -                         lib.py: 495 - iRODS server's zone key: 
2018-11-05 22:14:19,969 -   DEBUG -                         lib.py: 495 - iRODS server's negotiation key (32 characters): 
2018-11-05 22:14:21,568 -   DEBUG -                         lib.py: 495 - Control Plane key (32 characters): 
2018-11-05 22:14:23,040 -    INFO -               configuration.py: 288 - Updating /etc/irods/server_config.json...
2018-11-05 22:14:23,041 -    INFO -                 setup_irods.py: 369 - 
+-----------------------------------+
| Setting up the client environment |
+-----------------------------------+

2018-11-05 22:14:23,041 -   DEBUG -                         lib.py: 495 - iRODS server's administrator password: 
2018-11-05 22:14:26,043 -   DEBUG -               configuration.py: 228 - Writing password file /var/lib/irods/.irods/.irodsA
2018-11-05 22:14:26,053 -    INFO -               configuration.py: 288 - Updating /var/lib/irods/.irods/irods_environment.json...
2018-11-05 22:14:26,055 -    INFO -                 setup_irods.py: 180 - 
+--------------------------+
| Setting up default vault |
+--------------------------+

2018-11-05 22:14:26,055 -   DEBUG -                         lib.py: 495 - iRODS Vault directory [/var/lib/irods/Vault]: 
2018-11-05 22:14:26,776 -   DEBUG -                         lib.py: 500 - User input: 
2018-11-05 22:14:26,777 -    INFO -                 setup_irods.py: 123 - 
+-------------------------+
| Setting up the database |
+-------------------------+

2018-11-05 22:14:26,777 -   DEBUG -                         lib.py:  56 - Calling ['odbcinst', '-i', '-s', '-h', '-r'] with options:
{'env': 'HIDDEN', 'shell': False, 'stderr': -1, 'stdin': -1, 'stdout': -1}
2018-11-05 22:14:26,782 -   DEBUG -                         lib.py: 129 - Command ['odbcinst', '-i', '-s', '-h', '-r'] returned with code 0.
stdin:
  [iRODS Catalog]
  Driver=MySQL
  Option=2
  Description=iRODS catalog
  Server=localhost
  Port=3306
  Database=ICAT
stdout:
  odbcinst: Sections and Entries from stdin have been added to ODBC.INI
2018-11-05 22:14:26,797 -    INFO -            database_connect.py: 260 - Listing database tables...
2018-11-05 22:14:26,799 -   DEBUG -            database_connect.py: 262 - List of tables:
[]
2018-11-05 22:14:26,799 -    INFO -            database_connect.py: 318 - Defining mysql functions...
2018-11-05 22:14:26,800 -   DEBUG -          database_interface.py:  31 - Rolling back database changes...
```

**Comment by tempoz** [comment]
This is a documentation error for the moment; the setup script currently does not support being run by Python 3. However, given that Python 2 is reaching EOL in the next year, this is something that will need to be addressed in code in the future.
