### ISSUE TITLE
Failure starting iRODS: missing dependency version XZ_5.2.2 in liblzma.so.5

### ISSUE THREAD

**Issue by ccacciari** [irods/irods#4425]
### iRODS Version, OS and Version
iRODS: 4.2.6
OS: Fedora 30

### What did you try to do?
Starting the iRODS server.

### Expected behavior
$ ./irodsctl status
No iRODS servers running.
[irodsmaster@l0419005 irods]$ ./irodsctl start
Validating [/home/irodsmaster/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Ensuring catalog schema is up-to-date...
Catalog schema is up-to-date.
Starting iRODS server...

iRODS server up and running successfully.

### Observed behavior (including steps to reproduce, if applicable)

$ ./irodsctl status
No iRODS servers running.
$ ./irodsctl start
Validating [/home/irodsmaster/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Ensuring catalog schema is up-to-date...
Catalog schema is up-to-date.
Starting iRODS server...
Failure
Error encountered running irods_control start:
Traceback (most recent call last):
  File "./scripts/irods_control.py", line 116, in main
    operations_dict[operation]()
  File "./scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 121, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/controller.py", line 112, in start
    raise IrodsError('iRODS port returned non-heartbeat message:\n{0}'.format(message))
IrodsError: iRODS port returned non-heartbeat message:

Exiting...

$ tail -f reLog.2019.06.11
remote addresses: x.x.x.x ERROR: [-]	/tmp/tmpfe6BJv/lib/core/src/sockComm.cpp:1159:int sendStartupPack(rcComm_t *, int, int) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]
	[-]	/tmp/tmpfe6BJv/lib/core/src/sockComm.cpp:1235:irods::error sendRodsMsg(irods::network_object_ptr, const char *, bytesBuf_t *, bytesBuf_t *, bytesBuf_t *, int, irodsProt_t) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]
		[-]	/tmp/tmpfe6BJv/lib/core/src/irods_tcp_object.cpp:98:virtual irods::error irods::tcp_object::resolve(const std::string &, plugin_ptr &) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]
			[-]	/tmp/tmpfe6BJv/lib/core/src/irods_network_manager.cpp:104:irods::error irods::network_manager::init_from_type(const int &, const std::string &, const std::string &, const std::string &, const std::string &, network_ptr &) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]
				[-]	/tmp/tmpfe6BJv/lib/core/src/irods_network_manager.cpp:75:irods::error irods::load_network_plugin(network_ptr &, const std::string &, const std::string &, const std::string &) :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]
					[-]	/tmp/tmpfe6BJv/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const Ts &...) [PluginType = irods::network, Ts = <std::__1::basic_string<char>>] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/network/libtcp_client.so] :: dlerror: is [/lib64/liblzma.so.5: version `XZ_5.2.2' not found (required by /opt/irods-externals/libarchive3.3.2-0/lib/libarchive.so.16)]]

remote addresses: x.x.x.x ERROR: connectToRhost: sendStartupPack to x.x.x.x failed status = -1808000 PLUGIN_ERROR
 ERROR: _rcConnect: connectToRhost error, server on x.x.x.x:1247 is probably down status = -1808000 PLUGIN_ERROR
 ERROR: connect error

**Comment by alanking** [comment]
Please try again on a newer version of iRODS and, if any issues arise, open a new issue. Closing this one.
