### ISSUE TITLE
scripts/get_db_schema_version.py doesn't work 

### ISSUE THREAD

**Issue by sviscapi** [irods/irods#4434]
### iRODS Version, OS and Version

iRODS 4.2.6, CentOS 7.6 x86_64

### What did you try to do?

Run scripts/get_db_schema_version.py to be sure about the DB schema version in iRODS 4.2.5 / 4.2.6. Was there an update from v5 to v6 ?

### Expected behavior

```bash
python get_db_schema_version.py

Your DB schema version is v5 (or v6 ?)
```

### Observed behavior (including steps to reproduce, if applicable)

```bash
python get_db_schema_version.py
```

```python
Traceback (most recent call last):
  File "get_db_schema_version.py", line 26, in <module>
    print(get_current_schema_version(irods_config))
  File "get_db_schema_version.py", line 15, in get_current_schema_version
    return irods_config.get_schema_version_in_database()
AttributeError: 'IrodsConfig' object has no attribute 'get_schema_version_in_database'
```

**Comment by trel** [comment]
iRODS 4.2.5 bumped the database_schema_version from 5 to 6 (adding two indices for #4181)

We'll look into how these scripts can be run more standalone... or mark them as not intended for that usage.

**Comment by sviscapi** [comment]
@trel : thanks for your reply, and sorry for the noise. I thought those were standalone scripts, but it seems I got it wrong. Cheers, Samuel from CINES (Montpellier, France)

**Comment by trel** [comment]
No problem.   We'll leave this open for now as a possible bit of documentation work.
