### ISSUE TITLE
Test Failure: test_resource_types.Test_Resource_Replication.test_rebalance_logging_replica_update__3463

### ISSUE THREAD

**Issue by jassigill2000** [irods/irods#4765]
- [ ] master
- [x] 4-2-stable
-------

the test fails in ci with AssertionError but passes on the bench.

```
ERROR [114.670s]: test_rebalance_logging_replica_update__3463 (irods.test.test_resource_types.Test_Resource_Replication)
```

```
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_resource_types.py", line 4384, in test_rebalance_logging_replica_update__3463
    lambda: lib.log_message_occurrences_equals_count(
  File "/var/lib/irods/scripts/irods/lib.py", line 657, in delayAssert
    raise AssertionError
AssertionError
```

**Comment by alanking** [comment]
The timing tests are no longer run as part of regular test suite. Should any issues arise if/when those are re-introduced, we will open new issues for them.
