### ISSUE TITLE
Upgrade from 4.1.12 to 4.2.7 doesn't update server_config.json when icat host FQDN on Ubuntu 18.04

### ISSUE THREAD

**Issue by kript** [irods/irods#4873]
### iRODS Version, OS and Version

Ubuntu 18.04
iRODS 4.1.12 -> 4.2.7

### What did you try to do?

Install `irods-server` when `irods-resource` already installed

### Expected behavior

package update completes and updates appropriate json files in `/etc/irods`

### Observed behavior (including steps to reproduce, if applicable)
Running the iRODS start outside of systemd to remove that from the equation gives;
```
$ PATH=/bin:/usr/bin:/usr/sbin:/var/lib/irods:/var/lib/irods/iRODS
$ LD_LIBRARY_PATH=/usr/lib/oracle/11.1/client64/lib
$ /var/lib/irods/irodsctl start
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 127, in <module>
    sys.exit(main())
  File "/var/lib/irods/scripts/irods_control.py", line 116, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 40, in start
    upgrade_configuration.upgrade(self.config)
  File "/var/lib/irods/scripts/irods/upgrade_configuration.py", line 101, in upgrade
    upgrade_config_file(irods_config, path, new_version)
  File "/var/lib/irods/scripts/irods/upgrade_configuration.py", line 137, in upgrade_config_file
    config_dict = run_schema_update(config_dict, schema_name, schema_version + 1)
  File "/var/lib/irods/scripts/irods/upgrade_configuration.py", line 148, in run_schema_update
    if lib.hostname_resolves_to_local_address(config_dict['icat_host']):
  File "/var/lib/irods/scripts/irods/lib.py", line 486, in hostname_resolves_to_local_address
    hostname])
  File "/var/lib/irods/scripts/irods/lib.py", line 95, in execute_command_permissive
    p = execute_command_nonblocking(args, stdout=stdout, stderr=stderr, **kwargs)
  File "/var/lib/irods/scripts/irods/lib.py", line 58, in execute_command_nonblocking
    return subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
$ /var/lib/irods/irodsctl status
No iRODS servers running.
```

`/etc/irods/server_config.json` left as a part template where the `icat_host` is blank, and none of the rest of the configuration is transferred.

We use fqdn everywhere in the config files by policy, and following best practice. 

On Ubuntu 18.04 hosts, the output of `hostname` is not FQDN, neither is the contents of `/etc/hostname` however `hostname -A` correctly reports the FQDN.

On Ubuntu 12.04, the upgrade proceeds fine, where the hostname situation is the same. 

On Red Hat 7.4 hosts (where the hostname is FQDN), there is likewise no issue.

Once the icat_host entry is filled in on the failed template, restarting the service completes the migration.

**Comment by trel** [comment]
So, I'm reading this as an 18.04-only issue at the moment.    We will reproduce.

**Comment by trel** [comment]
First attempt to reproduce (in Docker) - everything worked as expected.  Will try again with more diverse configuration.

**Comment by alanking** [comment]
I have not been able to reproduce this issue on an Ubuntu 18.04 topology of 4.1.12 servers being upgraded to 4.2.7.

Noting relevant upgrade logic which could have possibly been a factor...
https://github.com/irods/irods/blob/c48b524a12bc726cb616044d3460554cf70def1e/scripts/irods/upgrade_configuration.py#L135-L139

https://github.com/irods/irods/blob/c48b524a12bc726cb616044d3460554cf70def1e/scripts/irods/upgrade_configuration.py#L148-L155

Additional notes: The error above can only be produced when the `icat_host` entry of the server_config file is null, an integer, a float, or a boolean. The default value for this entry is null in the template shipped with 4.1.12

**Comment by alanking** [comment]
4.1 and 4.2 are EOL.
