### ISSUE TITLE
upgrade 4.1 to 4.2.8 on catalog consumer fails to migrate command scripts

### ISSUE THREAD

**Issue by tedgin** [irods/irods#5586]
### iRODS Version, OS and Version

iRODS 4.1.10 --> iRODS 4.2.8, CentOS 7

### What did you try to do?

After upgrading the catalog provider to iRODS 4.2.8, I tried to upgrade iRODS on a catalog consumer from 4.1.10 to 4.2.8.  The consumer has custom command scripts installed that need to be migrated.

### Expected behavior

When I ran `irodctl start`, I expected all on the command scripts in `iRODS/server/bin/cmd/` to be move to `msiExecCmd_bin/`.

### Observed behavior (including steps to reproduce, if applicable)

`irodsctl` failed saying it couldn't find one of the custom command scripts in the new location. Upon inspection, it appears that all of the built-in command scripts were moved, but our custom command scripts were left in place.
 
```bash
[irods@up-rs ~]$ ./irodsctl start
Traceback (most recent call last):
  File "./scripts/irods_control.py", line 127, in <module>
    sys.exit(main())
  File "./scripts/irods_control.py", line 116, in main
    operations_dict[operation]()
  File "./scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start()
  File "/var/lib/irods/scripts/irods/controller.py", line 40, in start
    upgrade_configuration.upgrade(self.config)
  File "/var/lib/irods/scripts/irods/upgrade_configuration.py", line 93, in upgrade
    shutil.move(old_path, new_path)
  File "/usr/lib64/python2.7/shutil.py", line 301, in move
    copy2(src, real_dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/var/lib/irods/msiExecCmd_bin/amqptopicsend.py'

[irods@up-rs ~]$ ls msiExecCmd_bin
hello  irodsServerMonPerf  test_execstream.py  univMSSInterface.sh.template

[irods@up-rs ~]$ ls iRODS/server/bin/cmd
amqptopicsend.py  de-archive-data       delete-scheduled-rule  rm-trash  sparcd-ingest
calliope-ingest   de-create-collection  generateuuid           set-uuid
```

**Comment by tedgin** [comment]
I misunderstood what was going on.  I think the files I saw in `msiExecCmd_bin` were put there as part of the `irods-server` package installation and not by `irodsctl` moving them.  It looks like `root` maintained ownership of the `msiExecCmd_bin` after the installation. The error `irodsctl` reported was caused by it not being able to move the custom command scripts into `msiExecCmd_bin/` due to permissions issues.

```bash
[irods@up-rs ~]$ ls -l
total 20
drwxr-xr-x  4 irods irods   34 May  3 14:58 clients
drwxr-xr-x  4 irods irods   42 May  3 14:58 config
drwxr-xr-x  3 irods irods   16 May  3 14:58 configuration_schemas
drwxr-xr-x. 4 irods irods   35 May  3 14:58 iRODS
-rwxr--r--  1 irods irods  283 May 15  2020 irodsctl
drwxr-xr-x  2 irods irods   29 May  3 14:59 log
drwxr-xr-x  2 root  root   107 May  3 14:58 msiExecCmd_bin
drwxr-xr-x. 2 irods irods 4096 May  3 14:58 packaging
drwxr-xr-x  3 irods irods 4096 May  3 14:58 scripts
drwxr-xr-x  3 irods irods   65 May  3 14:58 test
-rw-r--r--  1 irods irods  166 May 21  2020 VERSION.json.dist
-rw-r--r--. 1 irods irods  477 Apr 19 14:02 VERSION.json.previous
```

The workaround is to make `irods` owner of the `msiExecCmd_bin/`.

**Comment by trel** [comment]
I think this is a 'feature'... from the looks of the comment.

https://github.com/irods/irods/blob/ca8417599c4e2706e058b833f14156ebd47b4db5/packaging/postinstall.sh#L59

That said, there's clearly a legitimate path for upgrade where the new directory *should* be owned by the service account...

**Comment by tedgin** [comment]
Since `msiExecCmd_bin` did not exist prior to installing the `irods-server` package, the question for me, is why didn't the package installation give the service account `irods` ownership of the folder when it created the folder?

**Comment by trel** [comment]
Agreed... just want to think this out loud...

I can see a case where someone else (read 'others', above) might have permissions on specific executables in there in an existing deployment... but is there a legitimate scenario where the `irods` service account would/should *not* be the owner of `msiExecCmd_bin` itself?  I suppose in the scenario where there are legitimate other-owned executables in that directory, the directory itself might have different owner or group permissions... so we don't want to just overpave those on upgrade...

Or... we could declare that's a not-good plan and the service account expects this directory to be here and owned by `irods`.

Ah, also... we could thread this needle by only changing the owner, not the group... so if it was being managed by 'others', then those would persist in the group permissions...  and a new install would have permission enough for the upgrade script to move any earlier scripts into place (like Tony's original migration from 4.1).

Okay... so, proposing...

```diff
chown $IRODS_SERVICE_ACCOUNT_NAME:$IRODS_SERVICE_GROUP_NAME $IRODS_HOME/VERSION*
+ chown $IRODS_SERVICE_ACCOUNT_NAME $IRODS_HOME/msiExecCmd_bin
chown $IRODS_SERVICE_ACCOUNT_NAME:$IRODS_SERVICE_GROUP_NAME $IRODS_HOME/msiExecCmd_bin/test_execstream.py
```

**Comment by tedgin** [comment]
Gotcha.

This is a tricky problem. Maybe it would be best to punt the decision to the installer. Would it be possible to have the installation detect the existence of the folder, and if it exists, ask the installer how its integration should be handled?

**Comment by trel** [comment]
Only the packager has root privileges (aka can run `chown`).

The installer runs as the service account and it would be too late to make any decisions.

I think we'll add the one-liner above ... an upgrade will enough permissions to migrate any existing scripts/executables.

**Comment by trel** [comment]
I've just tried an upgrade from:
 - vanilla 4.1.10 with
 - a single additional script in `iRODS/server/bin/cmd` and
 - a single repeating rule on the delay queue

After upgrade to packaged 4.2.8, before `./irodsctl start`... I noted these correct permissions set on `msiExecCmd_bin`:
```
drwxr-xr-x  2 irods irods 4096 May  5 21:00 msiExecCmd_bin
```

I applied only the fix for #5577 (removing the 'server' part of the incorrect new path).

The server came up correctly, no issues - my custom script (`tgrexec.sh`) was now available in `msiExecCmd_bin`:
```
irods@bison:~$ ls -al msiExecCmd_bin/
total 44
drwxr-xr-x  2 irods irods  4096 May  5 21:00 .
drwxr-xr-x 13 irods irods  4096 May  5 21:00 ..
-r-xr--r--  1 irods irods    99 May 14  2020 hello
-r-xr--r--  1 irods irods 19909 May 14  2020 irodsServerMonPerf
-r-xr--r--  1 irods irods  1489 May 14  2020 test_execstream.py
-r--r--r--  1 irods irods  5249 May 14  2020 univMSSInterface.sh.template
irods@bison:~$ ./irodsctl start
Updating /etc/irods/server_config.json...
Updating /etc/irods/hosts_config.json...
Updating /etc/irods/host_access_control_config.json...
Updating /var/lib/irods/.irods/irods_environment.json...
Updating /var/lib/irods/VERSION.json...
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Validating [/var/lib/irods/VERSION.json]... Success
Validating [/etc/irods/server_config.json]... Success
Validating [/etc/irods/host_access_control_config.json]... Success
Validating [/etc/irods/hosts_config.json]... Success
Updating /etc/irods/server_config.json...
Ensuring catalog schema is up-to-date...
Updating to schema version 5...
Updating to schema version 6...
Updating to schema version 7...
Catalog schema is up-to-date.
Starting iRODS server...
Success
irods@bison:~$ ls -al msiExecCmd_bin/
total 48
drwxr-xr-x  2 irods irods  4096 May  5 21:07 .
drwxr-xr-x 13 irods irods  4096 May  5 21:07 ..
-r-xr--r--  1 irods irods    99 May 14  2020 hello
-r-xr--r--  1 irods irods 19909 May 14  2020 irodsServerMonPerf
-r-xr--r--  1 irods irods  1489 May 14  2020 test_execstream.py
-rwxrwxr-x  1 irods irods    37 May  5 20:58 tgrexec.sh
-r--r--r--  1 irods irods  5249 May 14  2020 univMSSInterface.sh.template
```

So, it seems we don't need to apply a fix for migrating the command scripts for now.

**Comment by tedgin** [comment]
I'm glad to hear. Hopefully I did something boneheaded. I'll see if I can reproduce this issue.

**Comment by alanking** [comment]
I actually just ran into this while tinkering with the next-gen CI...

I observed that `/var/lib/irods/msiExecCmd_bin` - the directory itself, only - changes permissions from `irods:irods` to `root:root` on upgrade from 4.2.9 to 4.2.10+ on the `centos:7` docker image... only if the iRODS server is a catalog service consumer (CSC).

Sample output (modified for readability) from my installation script:
```
2021-08-13 14:54:34,222 WARNING - waiting for iRODS to finish setting up [centos-7-postgres-1012_irods-catalog-provider_1]
2021-08-13 14:54:43,452 WARNING - iRODS has been set up (waited [9.08281683921814] seconds)
2021-08-13 14:54:43,539 INFO - total 52
drwxr-xr-x 1 irods irods  4096 Aug 12 15:44 .
drwxr-xr-x 1 irods irods  4096 Aug 13 18:54 ..
<snip>
-r--r--r-- 1 irods irods  5249 Jul 25 21:19 univMSSInterface.sh.template

2021-08-13 14:54:43,550 WARNING - waiting for iRODS to finish setting up [centos-7-postgres-1012_irods-catalog-consumer-resource1_1]
2021-08-13 14:54:49,295 WARNING - iRODS has been set up (waited [5.615399599075317] seconds)
2021-08-13 14:54:49,398 INFO - total 52
drwxr-xr-x 1 irods irods  4096 Aug 12 15:47 .
drwxr-xr-x 1 irods irods  4096 Aug 13 18:54 ..
<snip>
-r--r--r-- 1 irods irods  5249 Jul 25 21:19 univMSSInterface.sh.template

... upgrade packages ...

<on provider>
2021-08-13 14:55:30,466 INFO - total 52
drwxr-xr-x 1 irods irods  4096 Aug 13 18:54 .
drwxr-xr-x 1 irods irods  4096 Aug 13 18:54 ..
<snip>
-r--r--r-- 1 irods irods  5249 Jun 26  2020 univMSSInterface.sh.template

<on consumer>
2021-08-13 14:55:30,960 INFO - total 52
drwxr-xr-x 1 root  root   4096 Aug 13 18:55 .
drwxr-xr-x 1 irods irods  4096 Aug 13 18:55 ..
<snip>
-r--r--r-- 1 irods irods  5249 Jun 26  2020 univMSSInterface.sh.template
```
For my purposes, I took @tedgin's cue (from this comment: https://github.com/irods/irods/issues/5586#issuecomment-832722393) and just ran a chown on the directory and my use case works. I haven't thought through all of the implications of changing the permissions to `irods:irods` on upgrade, but it certainly feels like a bug when it only happens on CSCs.

**Comment by trel** [comment]
Agreed, the solution works - but doesn't explain the underlying difference in behavior on Providers and Consumers.

That difference feels like the real bug... means... something *else* is healing only the Provider?
