### ISSUE TITLE
irodsctl stop always forcefully kills the local processes

### ISSUE THREAD

**Issue by tedgin** [irods/irods#5700]
- [x] master
- [x] 4-2-stable
--------

### iRODS Version, OS and Version

iRODS 4.2.8, CentOS 7

### What did you try to do?

I used `irodsctl stop` to shudown an iRODS service.

### Expected behavior

I expected the service to shutdown without error.

### Observed behavior (including steps to reproduce, if applicable)

`irodsctl` fails to shutdown the processes gracefully, so it kills the processes. In the log files, it complains that the hostname is invalid. This may be true. The server is running on an OpenStack VM that was given an autogenerated name. With the exception of `hosts_config.json`, the configuration only refers to the host by IP address. `hosts_config.json` identifies the hostname as an alias for the host. I would expect that irodsctl would use the contents of irods_environment.json to identify its host.

```bash
[irods@ds-dev-ies ~]$ ./irodsctl stop
Stopping iRODS server...
Error encountered in graceful shutdown.
iRODS server processes remain after "irods-grid shutdown".
irodsServer :
  Process 6462
  Process 6463
Killing forcefully...
Killing /usr/sbin/irodsServer, pid 6462
Killing /usr/sbin/irodsServer, pid 6463
iRODS child processes remain after "irods-grid shutdown".
irodsReServer :
  Process 6464
Killing forcefully...
Killing /usr/sbin/irodsReServer, pid 6464
Success
```

Here's `hosts_config.json`.

```json
{
    "host_entries": [
        {
            "address_type": "local", 
            "addresses": [
                {
                    "address": "128.196.65.86"
                }, 
                {
                    "address": "ds-dev-ies.novalocal"
                }, 
                {
                    "address": "172.16.6.73"
                }
            ]
        }
    ], 
    "schema_name": "hosts_config", 
    "schema_version": "v3"
}
```

The following is logged in rodsServerLog.

```
Jun 15 13:31:51 pid:6462 remote addresses: 127.0.0.1 ERROR: [-]	/irods_git_repo/server/core/src/irods_server_control_plane.cpp:1207:irods::error irods::server_control_executor::process_operation(const zmq::message_t &, std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [ds-dev-ies.novalocal]]
	[-]	/irods_git_repo/server/core/src/irods_server_control_plane.cpp:920:irods::error irods::server_control_executor::validate_host_list(const irods::server_control_executor::host_list_t &, const irods::server_control_executor::host_list_t &, irods::server_control_executor::host_list_t &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [ds-dev-ies.novalocal]]

Jun 15 13:31:51 pid:6462 remote addresses: 127.0.0.1 ERROR: [-]	/irods_git_repo/server/core/src/irods_server_control_plane.cpp:750:void irods::server_control_executor::operator()() :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [ds-dev-ies.novalocal]]
	[-]	/irods_git_repo/server/core/src/irods_server_control_plane.cpp:1207:irods::error irods::server_control_executor::process_operation(const zmq::message_t &, std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [ds-dev-ies.novalocal]]
		[-]	/irods_git_repo/server/core/src/irods_server_control_plane.cpp:920:irods::error irods::server_control_executor::validate_host_list(const irods::server_control_executor::host_list_t &, const irods::server_control_executor::host_list_t &, irods::server_control_executor::host_list_t &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [ds-dev-ies.novalocal]]
```

The following is logged in control_log.txt.

```
2021-06-15 20:31:51,709 -   DEBUG -                  controller.py: 148 - Calling stop on IrodsController
2021-06-15 20:31:51,710 -    INFO -                  controller.py: 149 - Stopping iRODS server...
2021-06-15 20:31:51,742 -   DEBUG -               configuration.py: 439 - Loading /etc/irods/server_config.json into dictionary
2021-06-15 20:31:51,745 -   DEBUG -                         lib.py:  56 - Calling ['irods-grid', 'shutdown', '--hosts=ds-dev-ies.novalocal'] with options:
{'shell': False, 'stderr': -1, 'stdout': -1}
2021-06-15 20:31:52,058 -   DEBUG -                         lib.py: 129 - Command ['irods-grid', 'shutdown', '--hosts=ds-dev-ies.novalocal'] returned with code 0.
stderr:
  server responded with an error
2021-06-15 20:32:12,005 -   ERROR -                  controller.py: 155 - Error encountered in graceful shutdown.
2021-06-15 20:32:12,006 -   DEBUG -                  controller.py: 156 - Exception:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 153, in stop
    self.irods_grid_shutdown(timeout=timeout)
  File "/var/lib/irods/scripts/irods/controller.py", line 143, in irods_grid_shutdown
    'receiving the "shutdown" command.'.format(timeout))
IrodsError: The iRODS server did not stop within 20 seconds of receiving the "shutdown" command.
2021-06-15 20:32:12,029 - WARNING -                  controller.py: 163 - iRODS server processes remain after "irods-grid shutdown".
2021-06-15 20:32:12,029 - WARNING -                  controller.py: 164 - irodsServer :
  Process 6462
  Process 6463
2021-06-15 20:32:12,030 - WARNING -                  controller.py: 165 - Killing forcefully...
2021-06-15 20:32:12,031 - WARNING -                  controller.py: 167 - Killing /usr/sbin/irodsServer, pid 6462
2021-06-15 20:32:12,032 -   DEBUG -                  controller.py: 233 - Deleting cache files for pid 6462...
2021-06-15 20:32:12,034 -   DEBUG -                  controller.py: 252 - Deleting /dev/shm/irods_re_cache_mutex_upgraded_irods_rule_language_rule_engine_pid6462_38c7657a01ab568940a9e54383d25f4311c4f72e1b92433ea040340e2b9339f0f09efddf5d9daeda
2021-06-15 20:32:12,034 -   DEBUG -                  controller.py: 252 - Deleting /dev/shm/irods_re_cache_shared_memory_upgraded_irods_rule_language_rule_engine_pid6462_38c7657a01ab568940a9e54383d25f4311c4f72e1b92433ea040340e2b9339f0f09efddf5d9daeda
2021-06-15 20:32:12,035 - WARNING -                  controller.py: 167 - Killing /usr/sbin/irodsServer, pid 6463
2021-06-15 20:32:12,035 -   DEBUG -                  controller.py: 233 - Deleting cache files for pid 6463...
2021-06-15 20:32:12,108 - WARNING -                  controller.py: 176 - iRODS child processes remain after "irods-grid shutdown".
2021-06-15 20:32:12,108 - WARNING -                  controller.py: 177 - irodsReServer :
  Process 6464
2021-06-15 20:32:12,109 - WARNING -                  controller.py: 178 - Killing forcefully...
2021-06-15 20:32:12,109 - WARNING -                  controller.py: 181 - Killing /usr/sbin/irodsReServer, pid 6464
2021-06-15 20:32:12,110 -   DEBUG -                  controller.py: 233 - Deleting cache files for pid 6464...
2021-06-15 20:32:12,111 -    INFO -                  controller.py: 191 - Success
```

**Comment by trel** [comment]
need to confirm this is still happening with 4.2.9

**Comment by korydraughn** [comment]
reproduced on 4.2.8 and tip of 4-2-stable.

i also came across what looks to be another bug.

given the following:
- a server with a hostname of **the-provider**
- a hosts_config.json with a local entry where the hostname ends with **the-provider** (e.g. **some.prefix.the-provider**)

`irods-grid shutdown --hosts=some.prefix.the-provider` shuts down **the-provider** successfully. the output of the command is:
```bash
{
    "hosts": [
        {
            "shutting down": "the-provider"
        }
    ]
}
```
it's as if the code is ignoring everything before **the-provider**.

@trel this should result in an error, right?

**Comment by trel** [comment]
that seems wrong - something is chopping a string / hostname from the 'wrong end'.

**Comment by trel** [comment]
checkboxed
