### ISSUE TITLE
irods-grid status produces errors in rodsServerLog (race condition?)

### ISSUE THREAD

**Issue by bh9** [irods/irods#5722]
### iRODS Version, OS and Version
4.2.7, Ubuntu 18.04 running 16.04 packages

### What did you try to do?
irods-grid --hosts="$HOSTNAME" status

### Expected behavior
irods-grid produces the json object, and does not put any errors into rodsServerLog (or anywhere else)

### Observed behavior (including steps to reproduce, if applicable)
irods-grid produces the json object, but produces the below error messages in rodsServerLog. The repeating pid_age.py block seems to be once per process which irods-grid thinks is running but which has ended, which suggests to me that it's a race condition where the process has ended before we check when it's started. We will be replacing our usage of irods-grid with an ips-based approach shortly, as all we're trying to do is find the number of running processes on a server, so ips is sufficient
```
Jun 29 09:45:21 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:1227:irods::error irods::server_control_executor::process_operation(const zmq::message_t &, std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [irods-humgen-ies1]]
        [-]     /irods/server/core/src/irods_server_control_plane.cpp:940:irods::error irods::server_control_executor::validate_host_list(const host_list_t &, const host_list_t &, host_list_t &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [irods-humgen-ies1]]
Traceback (most recent call last):
  File "/var/lib/irods/scripts/pid_age.py", line 13, in <module>
    p = psutil.Process(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 341, in __init__
    self._init(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 381, in _init
    raise NoSuchProcess(pid, None, msg)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess no process found with pid 9014
Jun 29 09:45:26 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:367:int irods::get_pid_age(pid_t) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
        [-]     /irods/server/core/src/miscServerFunct.cpp:3080:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
Traceback (most recent call last):
  File "/var/lib/irods/scripts/pid_age.py", line 13, in <module>
    p = psutil.Process(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 341, in __init__
    self._init(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 381, in _init
    raise NoSuchProcess(pid, None, msg)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess no process found with pid 9012
Jun 29 09:45:26 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:367:int irods::get_pid_age(pid_t) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
        [-]     /irods/server/core/src/miscServerFunct.cpp:3080:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
...
Traceback (most recent call last):
  File "/var/lib/irods/scripts/pid_age.py", line 13, in <module>
    p = psutil.Process(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 341, in __init__
    self._init(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 381, in _init
    raise NoSuchProcess(pid, None, msg)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess no process found with pid 8847
Jun 29 09:45:37 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:367:int irods::get_pid_age(pid_t) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
        [-]     /irods/server/core/src/miscServerFunct.cpp:3080:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
Traceback (most recent call last):
  File "/var/lib/irods/scripts/pid_age.py", line 13, in <module>
    p = psutil.Process(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 341, in __init__
    self._init(pid)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 381, in _init
    raise NoSuchProcess(pid, None, msg)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess no process found with pid 8843
Jun 29 09:45:37 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:367:int irods::get_pid_age(pid_t) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
        [-]     /irods/server/core/src/miscServerFunct.cpp:3080:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]
Jun 29 09:45:42 pid:15155 remote addresses: 127.0.0.1 ERROR: [-]        /irods/server/core/src/irods_server_control_plane.cpp:770:void irods::server_control_executor::operator()() :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [irods-humgen-ies1]]
        [-]     /irods/server/core/src/irods_server_control_plane.cpp:1227:irods::error irods::server_control_executor::process_operation(const zmq::message_t &, std::string &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [irods-humgen-ies1]]
                [-]     /irods/server/core/src/irods_server_control_plane.cpp:940:irods::error irods::server_control_executor::validate_host_list(const host_list_t &, const host_list_t &, host_list_t &) :  status [SYS_INVALID_INPUT_PARAM]  errno [] -- message [invalid server hostname [irods-humgen-ies1]]
```

**Comment by tedgin** [comment]
I have reproduced this on iRODS 4.2.8 running on CentOS 7.
