### ISSUE TITLE
irods breaks mysql 8 GTID replication

### ISSUE THREAD

**Issue by peterverraedt** [irods/irods#5729]
### iRODS Version, OS and Version

* IRODS 4.2.9
* Mysql 8 in HA mode with GTID replication

### Observed behavior (including steps to reproduce, if applicable)

When creating e.g. a collection, the query <https://github.com/irods/irods/blob/master/plugins/api/src/atomic_apply_metadata_operations.cpp#L286-L287> is called to insert metadata (possibly caused by the unified storage plugin adding a timestamp), but this fails with `Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement`.

The issue is that the query `insert into R_COLL_MAIN (coll_id, parent_coll_name, coll_name, coll_owner_name, coll_owner_zone, coll_type, coll_info1, coll_info2, create_ts, modify_ts) values (R_ObjectID_nextval(), ?, ?, ?, ?, ?, ?, ?, ?, ?)` uses `R_ObjectID_nextval()` as part of the statement - using `cllNextValueString` as elsewhere in the code will fix this.

**Comment by korydraughn** [comment]
@peterverraedt Moving the call to `R_ObjectID_nextval()` out of the insert statement fixes it?

Is it safe to call `R_ObjectID_nextval()` while executing multiple SQL statements in the same transaction?

For example:
```
while in transaction t:
    try:
        for op in operations:
            new_id = next_id() # invokes R_ObjectID_nextval()
            insert_using_id(new_id, op.data)

        t.commit()

    except:
        t.rollback()
```

**Comment by peterverraedt** [comment]
@korydraughn Yes, I believe moving it out of the insert, should fix this.

**Comment by korydraughn** [comment]
I tried standing up things using the repository you posted, but it failed.

I got the following after entering the iRODS container and running `./irodsctl -v start`.
```bash
iRODS user [irods]:                                           
iRODS group [irods]:                                                                                                                                  
iRODS server's role:                                                                      
1. provider                                                                                                                                                      
2. consumer                                                                                       
Please select a number or choose 0 to enter a new value [1]:                              
ODBC driver for mysql:                                                                                                                                                                                                                                                                                                                                                                   
1. MySQL                                                                                                                                                                                                                                                                                                                                                                
2. MySQL ODBC 8.0 Unicode Driver                                             
3. MySQL ODBC 8.0 ANSI Driver                                          
Please select a number or choose 0 to enter a new value [1]:                                                   
New value:                                                                                   
Database server's hostname or IP address [localhost]:                                                    
Database server's port [3306]:                                                    
Database name [ICAT]:                    
Database username [irods]:
                                                
-------------------------------------------                           
Database Type: mysql                                                                                           
ODBC Driver:   MySQL ODBC 8.0 Unicode Driver                                                                                                                                                                                                                                                                                                                                             
Database Host: mysql                                                                                                                                                                                                                                                                                                                                                    
Database Port: 3306                                                          
Database Name: irods                                                   
Database User: irods                                             
-------------------------------------------                                                  
                                                                                                         
Please confirm [yes]: Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.
Error encountered running setup_irods:                                                                                                                                                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                      
  File "/var/lib/irods/scripts/setup_irods.py", line 434, in main           
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "/var/lib/irods/scripts/setup_irods.py", line 116, in setup_server                                      
    database_interface.setup_database_config(irods_config)       
  File "/var/lib/irods/scripts/irods/database_interface.py", line 176, in setup_database_config
    if database_already_in_use_by_irods(irods_config):                                                   
  File "/var/lib/irods/scripts/irods/database_interface.py", line 73, in database_already_in_use_by_irods
    with contextlib.closing(database_connect.get_database_connection(irods_config)) as connection:
  File "/var/lib/irods/scripts/irods/database_connect.py", line 219, in get_database_connection
    sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/database_connect.py", line 202, in get_database_connection
    return pypyodbc.connect(connection_string.encode('ascii'), ansi=True)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 2452, in __init__
    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 2501, in connect
    check_success(self, ret)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 988, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "/var/lib/irods/scripts/irods/pypyodbc.py", line 964, in ctrl_err
    raise Error(state,err_text)
IrodsError: pypyodbc encountered an error connecting to the database:
('HY000', "[HY000] [unixODBC][MySQL][ODBC 8.0(w) Driver]Access denied for user 'irods'@'172.17.0.3' (using password: YES)")
```

I received these messages following the execution of `run.sh`.
```bash
starting up                                                                                                                                                                                                                                                                                                                                                                                  
starting up                                                                                                                                                                                                                                                                                                                                                                                  
starting up                                                                                                                                                                                                                                                                                                                                                                                  
starting up                                                                                                                                                                                                                                                                                                                                                                                  
starting up                                                                                                                                                                                                                                                                                                                                                                                  
starting up                                                                                                                                                                                                                                                                                                                                                                                  
Ncat: Connection refused.                                                                                                                                                                                                                                                                                                                                                                    
IRODS is not responding to HEATBEAT                                                                                                                                                                                                                                                                                                                                                          
Ncat: Connection refused.                                                                                                                                                                                                                                                                                                                                                                    
IRODS is not responding to HEATBEAT                                                                                                                                                                                                                                                                                                                                                          
Ncat: Connection refused.                                                                                                                                                                                                                                                                                                                                                                    
IRODS is not responding to HEATBEAT                                                                                                                                                                                                                                                                                                                                                          
Ncat: Connection refused.                                                                                                                                                                                                                                                                           
IRODS is not responding to HEATBEAT                                                                      
Ncat: Connection refused.                                                                     
IRODS is not responding to HEATBEAT                                                          
Ncat: Connection refused.                                          
IRODS is not responding to HEATBEAT                                                                    
Ncat: Connection refused.                                                                                                                                                                                                                                                                                                                                                                    
IRODS is not responding to HEATBEAT
```

Are you able to stand up the containers? Could there be something else that needs to be tweaked in the Dockerfile and/or scripts?

**Comment by peterverraedt** [comment]
I added some healthchecks for mysql, I think the database was not created at this point. Can you retest with the latest commit?

For further debugging, /var/lib/irods/log in the irods container can be checked.

**Comment by korydraughn** [comment]
sure. i'll pull in the latest commits and see if anything changes.

**Comment by korydraughn** [comment]
it worked!

creating a collection resulted in the database logging the GTID warning.

now all i need to do is verify that my changes fix it.

**Comment by korydraughn** [comment]
I've tried creating a collection using my PR which includes the [GTID fix](https://github.com/irods/irods/pull/6159/commits/ee5930ba5a904be8a4c538d9039663a4f414ba4f) and I still got the warning message.

Even though execution of `select R_OBJECTID_nextval()` happens first/separately, we're still performing all of these queries inside of a single transaction.

Based on documentation around GTID, could it be that your database has a mixture of tables using different storage engines?

In the docker project you shared, the `R_ObjectId_seq_tbl` table uses `MyISAM` while other tables such as `R_META_MAIN` and `R_OBJT_METAMAP` use `InnoDB`.

Using the following SQL to change the storage engine type of `R_ObjectId_seq_tbl` to `InnoDB` makes it so that the warning is no longer produced.
```sql
alter table R_ObjectId_seq_tbl engine=InnoDB;
```

Can you verify the engine types for the tables mentioned above?

**Comment by korydraughn** [comment]
Cool. Does that resolve the issue for you?

**Comment by peterverraedt** [comment]
I'll tell the definite answer in a week.

**Comment by peterverraedt** [comment]
I can confirm the issue is resolved. Thanks for the efforts!

**Comment by korydraughn** [comment]
Excellent!
