### ISSUE TITLE
cannot open two write connections to non unique replica using Token and Hierarchy keywords

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5848]
- [x] 4-2-stable
- [x] master
---
### iRODS Version, OS and Version

iRODS 4-2-stable
Ubuntu 18

### What did you try to do?

From a Python client, open two write descriptors to a replica ( in separate server connections)  to a single data object having more than one replica on the system 

### Expected behavior

Logical locking should permit this when REPLICA_TOKEN_KW and {DEST_,}RESC_HIER_STR_KW are appropriately set.

### Observed behavior (including steps to reproduce, if applicable)

Logical locking permits it when only one replica exists in the catalog, but a LOCKED_DATA_OBJECT_ACCESS is raised if more than one replica exists.

```
 $ git clone -b conn_track.285 http://github.com/d-w-moore/python-irodsclient     ###----> test branch ( adds test and logging)
 $ python3 -m pip install ./python-irodsclient ; cd ./python-irodsclient/irods/test
 $ iadmin mkresc pt passthru
 $ iadmin mkresc leaf unixfilesystem `hostname`:/tmp/leaf
 $ iadmin addchildtoresc pt leaf
 $ truncate -s0 0m ; irm -fr 0m ; iput -R pt 0m ; python3 reproduce_285.py -R pt  --pass rods `ipwd`/0m
INFO:root:Data Object open yielding raw fd: <irods.data_object.iRODSDataObjectFileRaw object at 0x7f88e7bd0ef0>
INFO:root:                 from connection: <irods.connection.Connection object at 0x7f88e7bd0828>
INFO:root:token  = 2dd404f5-fe60-4bdf-bb00-af8090c6288a
INFO:root:hier   = pt;leaf
INFO:root:Data Object open yielding raw fd: <irods.data_object.iRODSDataObjectFileRaw object at 0x7f88e7bd0da0>
INFO:root:                 from connection: <irods.connection.Connection object at 0x7f88e7bd0748>
INFO:root:Data Object write  using  raw fd: <irods.data_object.iRODSDataObjectFileRaw object at 0x7f88e7bd0da0>
INFO:root:                 from connection: <irods.connection.Connection object at 0x7f88e7bd0748>
INFO:root:Data Object write  using  raw fd: <irods.data_object.iRODSDataObjectFileRaw object at 0x7f88e7bd0ef0>
INFO:root:                 from connection: <irods.connection.Connection object at 0x7f88e7bd0828>
```
The above shows a successful open and write to the replica on pt;leaf using two independent agents (ie connections).
Now repeat, ensuring two replicas prior to running reproduction test script :
```
 $  irm -fr 0m ; iput -R pt 0m ; irepl -R demoResc 0m
 $ ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-14.09:47 & 0m
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-14.09:47 & 0m
        generic    /var/lib/irods/Vault/home/rods/0m
$  python3 reproduce_285.py -R pt  --pass rods `ipwd`/0m
>
INFO:root:Data Object open yielding raw fd: <irods.data_object.iRODSDataObjectFileRaw object at 0x7fa0835b5f98>
INFO:root:                 from connection: <irods.connection.Connection object at 0x7fa0835b5e10>
INFO:root:token  = 144d568a-af3a-41ef-8e50-7362a609ea10
INFO:root:hier   = pt;leaf
Traceback (most recent call last):
  File "/home/daniel/t/python-irodsclient/irods/connection.py", line 103, in recv
    err_msg = iRODSMessage(msg=msg.error).get_main_message(Error).RErrMsg_PI[0].msg
  File "/home/daniel/t/python-irodsclient/irods/message/__init__.py", line 213, in get_main_message
    msg.unpack(ET.fromstring(self.msg))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
TypeError: a bytes-like object is required, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reproduce_285.py", line 41, in <module>
    fd2 = ses.data_objects.open(objName,'a',finalize_on_close = False,**open2_opts)
  File "/home/daniel/t/python-irodsclient/irods/manager/data_object_manager.py", line 262, in open
    desc = conn.recv().int_info
  File "/home/daniel/t/python-irodsclient/irods/connection.py", line 105, in recv
    raise get_exception_by_code(msg.int_info)
  File "/home/daniel/t/python-irodsclient/irods/exception.py", line 92, in get_exception_by_code
    return iRODSExceptionMeta.codes[code](message)
KeyError: -406000
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.
ERROR:irods.connection:Unable to send message. Connection to remote host may have closed. Releasing connection from pool.

```
The following log message is in the rodsServerLog as a result of the attempt:
```
Sep 14 09:49:18 pid:9132 NOTICE: [try_lock_for_locked_data_object:304] - data object is locked. [path=[/tempZone/home/rods/0m], hierarchy=[demoResc]]


```

**Comment by trel** [comment]
confirmed this is real - discussing correct way to fix this.

**Comment by alanking** [comment]
I believe I have the change for fixing this. For posterity...
```python
#!/usr/bin/env python
from __future__ import print_function
from irods.session import iRODSSession
import sys
import logging
import irods.keywords as kw
logging.basicConfig(level = logging.INFO)
import getopt

# repro285.py
# put a local file to a replica in irods, specified by DEST_RESC name
# usage: python ./repro285.py [-R DEST_RESC] filename

opt,arg = getopt.getopt(sys.argv[1:],'R:',['user=','zone=','pass=','host=','port='])

optD=dict(opt)

port_ = int(optD.get('--port','1247'))
host_ = optD.get('--host','localhost')
zone_ = optD.get('--zone','tempZone')
user_ = optD.get('--user','rods')
pass_ = optD.get('--pass')
assert type(pass_) is str

open1_opts={}

if '-R' in optD:
    open1_opts [kw.DEST_RESC_NAME_KW] = optD['-R']

objName = arg[0]

with iRODSSession(user=user_ , host=host_ , port=port_, zone=zone_ , password = pass_) as ses:
    fd1 = ses.data_objects.open(objName,'w',**open1_opts)
    token,hier = fd1.raw.replica_access_info()
    logging.info('token  = %s',token)
    logging.info('hier   = %s',hier)
    open2_opts = { kw.REPLICA_TOKEN_KW : token,
                   kw.DEST_RESC_HIER_STR_KW : hier,  
                   kw.RESC_HIER_STR_KW : hier        # read only ?
    }
    fd2 = ses.data_objects.open(objName,'a',finalize_on_close = False,**open2_opts)
    #print("{} {}".format(fd1.raw.conn,fd2.raw.conn))
    fd2.seek(4) ; fd2.write(b's\n')
    fd1.write(b'book')

    fd2.close()
    fd1.close()
    pass #1
pass #0
```

Here is the output I got:
```bash
$ # target the non-default hierarchy
$ irm -fr 0m ; iput -R pt 0m ; irepl -R demoResc 0m ; ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-15.17:15 & 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-15.17:15 & 0m 
        generic    /var/lib/irods/Vault/home/rods/0m
$ python3 reproduce_285.py -R pt  --pass rods ipwd/0m
INFO:root:token  = 75943478-7cd1-4455-acd0-f1b79b8bab9d
INFO:root:hier   = pt;leaf
$ ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            6 2021-09-15.17:15 & 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-15.17:15 X 0m 
        generic    /var/lib/irods/Vault/home/rods/0m

$ # target the default hierarchy
$ irm -fr 0m ; iput -R pt 0m ; irepl -R demoResc 0m ; ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-15.16:57 & 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-15.16:58 & 0m 
        generic    /var/lib/irods/Vault/home/rods/0m
$ python3 reproduce_285.py -R demoResc  --pass rods ipwd/0m
INFO:root:token  = eb7beb1d-ada8-4d43-834b-e32342c5777c
INFO:root:hier   = demoResc
$ ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-15.16:57 X 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            6 2021-09-15.16:58 & 0m 
        generic    /var/lib/irods/Vault/home/rods/0m

$ # no write does not affect the replica system metadata
$ diff reproduce_285.py reproduce_285_with_no_write.py 
43,44c43,44
<     fd2.seek(4) ; fd2.write(b's\n')
<     fd1.write(b'book')
---
>     fd2.seek(4) #; fd2.write(b's\n')
>     #fd1.write(b'book')
$ ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-15.17:21 & 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-15.17:21 & 0m 
        generic    /var/lib/irods/Vault/home/rods/0m
$ python3 reproduce_285_with_no_write.py -R pt  --pass rods ipwd/0m
INFO:root:token  = cba0ea3c-ad1e-4312-a849-0c4d3547b74e
INFO:root:hier   = pt;leaf
$ ils -L
/tempZone/home/rods:
  rods              0 pt;leaf            0 2021-09-15.17:21 & 0m 
        generic    /tmp/leaf/home/rods/0m
  rods              1 demoResc            0 2021-09-15.17:21 & 0m 
        generic    /var/lib/irods/Vault/home/rods/0m
```

**Comment by trel** [comment]
can you target a new third replica?

**Comment by alanking** [comment]
If you target a new replica on a locked data object, the error code `LOCKED_DATA_OBJECT_ACCESS` is returned even if a replica token is provided. This is the expected behavior. I have added a unit test for this.

**Comment by d-w-moore** [comment]
Output looks right.  @alanking  - you've made these changes in **irods/irods** ?
