### ISSUE TITLE
irodsctl needs icommands to be in the PATH environment variable

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods#5966]
## Bug Report

In master branch `irodsctl` requires the icommands to be in PATH eg. if the icommands are not in the "standard" place ( `/usr/bin` ) or their userspace-tarball is not in PATH, irodsctl malfunctions when trying to stop or restart the irods server.

### iRODS Version, OS and Version

ubuntu:18.04 on Docker
iRODS **master** branch, built from [this commit](https://github.com/irods/irods/commit/970a4286ef2096a59707f415a00bf7e07f2dbbeb)
icommands built and installed from userspace-tarball target

### What did you try to do?
use `irodsctl` to stop or bounce the server

### Expected behavior
silent and error-free **stop** and/or **restart**
as when the icommands are either installed or otherwise in the PATH:
```
root@1d84351471be:/# service postgresql  start
 * Starting PostgreSQL 10 database server                                                                                                                                                            [ OK ] 
root@1d84351471be:/# sudo su - irods      
root@1d84351471be:/#  ## we now place icommands into the PATH -_-_-------- v v v
irods@1d84351471be:~$ PATH=~dan/bin/irods-icommands-4.3.0/usr/bin/:$PATH  ## __userspace __ tarball __ location__
irods@1d84351471be:~$ ./irods start
-su: ./irods: No such file or directory
irods@1d84351471be:~$ ./irodsctl start
irods@1d84351471be:~$ pgrep irods'.*S' -afl
81 /usr/sbin/irodsServer
82 /usr/sbin/irodsServer
84 irodsReServer
irods@1d84351471be:~$ ./irodsctl restart
irods@1d84351471be:~$ pgrep irods'.*S' -afl
121 /usr/sbin/irodsServer
122 /usr/sbin/irodsServer
124 irodsReServer
irods@1d84351471be:~$ ./irodsctl stop
irods@1d84351471be:~$ pgrep irods'.*S' -afl
irods@1d84351471be:~$ 
```
### Observed behavior (including steps to reproduce, if applicable)

If we try `irodsctl restart` without icommands in the PATH , we can end up with forced kill, two new `irodsServer`s but no `irodsReServer`:
```
daniel@canute-nl:~$ docker start -ia 1d8
root@1d84351471be:/# service postgresql  start
 * Starting PostgreSQL 10 database server                                                                                                                                                            [ OK ] 
root@1d84351471be:/# su - irods
irods@1d84351471be:~$ which ils
irods@1d84351471be:~$ pgrep irods'.*S' -afl^C
irods@1d84351471be:~$ ./irodsctl start
irods@1d84351471be:~$ pgrep irods'.*S' -afl
81 /usr/sbin/irodsServer
82 /usr/sbin/irodsServer
84 irodsReServer
irods@1d84351471be:~$ ./irodsctl restart
Error encountered in graceful shutdown.
iRODS server processes remain after "irods-grid shutdown".
irodsServer :
  Process 82
Killing forcefully...
Killing /usr/sbin/irodsServer, pid 82
iRODS child processes remain after "irods-grid shutdown".
irodsServer :
  Process 82
irodsReServer :
  Process 84
Killing forcefully...
Killing /usr/sbin/irodsServer, pid 82
Killing /usr/sbin/irodsReServer, pid 84
Error encountered running irods_control restart:
Traceback (most recent call last):
  File "./scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "./scripts/irods_control.py", line 73, in <lambda>
    operations_dict['restart'] = lambda: irods_controller.restart(write_to_stdout=options.write_to_stdout, test_mode=options.test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 248, in restart
    self.start(write_to_stdout, test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 73, in start
    raise IrodsError('iRODS already running')
IrodsError: iRODS already running
irods@1d84351471be:~$ pgrep irods'.*S' -afl
81 /usr/sbin/irodsServer
111 /usr/sbin/irodsServer
```

And if we try `irodsctl stop` , we can end up with two new `irodsServer` instances running as well as two `irodsReServer`'s
```
$ docker start -ia 1d8
root@1d84351471be:/# service postgresql  start
 * Starting PostgreSQL 10 database server                                                                                                                                                            [ OK ] 
root@1d84351471be:/# sudo su - irods
irods@1d84351471be:~$ which ils
irods@1d84351471be:~$ echo $?
1
irods@1d84351471be:~$ ./irodsctl start
irods@1d84351471be:~$ pgrep irods'.*S' -afl
80 /usr/sbin/irodsServer
81 /usr/sbin/irodsServer
83 irodsReServer
irods@1d84351471be:~$ ./irodsctl stop 
Error encountered in graceful shutdown.
iRODS server processes remain after "irods-grid shutdown".
irodsServer :
  Process 81
Killing forcefully...
Killing /usr/sbin/irodsServer, pid 81
iRODS child processes remain after "irods-grid shutdown".
irodsServer :
  Process 81
irodsReServer :
  Process 83
Killing forcefully...
Killing /usr/sbin/irodsServer, pid 81
Killing /usr/sbin/irodsReServer, pid 83
irods@1d84351471be:~$ pgrep irods'.*S' -afl
80 /usr/sbin/irodsServer
109 /usr/sbin/irodsServer
110 irodsReServer
115 /usr/sbin/irodsServer
irods@1d84351471be:~$ 

```

**Comment by trel** [comment]
related to #5978
