### ISSUE TITLE
setup fails when service user homedir doesn't exist

### ISSUE THREAD

**Issue by kript** [irods/irods#6066]
### iRODS Version, OS and Version

4.2.7
Ubuntu 18.04

### What did you try to do?

Install iRODS (which, unbeknownst to me at the time, the service users home dir didn't exist and/or wasn't writeable by the user)

### Expected behaviour

Failure with an error tat basically says 'can't write to dir'

### Observed behaviour (including steps to reproduce, if applicable)

```
Updating /etc/irods/server_config.json...
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 438, in main
    setup_server(irods_config, json_configuration_file=options.json_configuration_file)
  File "/var/lib/irods/scripts/setup_irods.py", line 116, in setup_server
    database_interface.setup_database_config(irods_config)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 176, in setup_database_config
    if database_already_in_use_by_irods(irods_config):
  File "/var/lib/irods/scripts/irods/database_interface.py", line 73, in database_already_in_use_by_irods
    with contextlib.closing(database_connect.get_database_connection(irods_config)) as connection:
  File "/var/lib/irods/scripts/irods/database_connect.py", line 193, in get_database_connection
    sync_odbc_ini(irods_config)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 309, in sync_odbc_ini
    env={'ODBCINI': irods_config.odbc_ini_path, 'ODBCSYSINI': '/etc'})
  File "/var/lib/irods/scripts/irods/lib.py", line 134, in execute_command
    check_command_return(args, out, err, returncode, **kwargs)
  File "/var/lib/irods/scripts/irods/lib.py", line 117, in check_command_return
    indent(err))]))
IrodsError: Call to open process with ['odbcinst', '-i', '-s', '-h', '-r'] returned an error:
  Options passed to Popen:
    input: [iRODS Catalog]
    Driver=PostgreSQL Unicode
    Description=iRODS Catalog
    Trace=No
    Database=ICAT
    TraceFile=
    Servername=localhost
    FakeOidIndex=No
    ShowOidColumn=No
    RowVersioning=No
    CommLog=0
    ReadOnly=No
    Debug=0
    ConnSettings=
    Port=5432
    Ksqo=0
    ShowSystemTables=No
    env: HIDDEN
  Return code: 1
  Standard output:
    odbcinst: SQLWritePrivateProfileString failed with General error request failed.
    odbcinst: SQLWritePrivateProfileString failed with General error request failed.
  Error output:

Exiting...
```

**Comment by trel** [comment]
So, you'd just like a cleaner error message?

I think that would mean we have to interpret any message(s) coming back from `odbcinst`... rather than just print it out.
