### ISSUE TITLE
Latest `jsonschema` version seems unhappy with iRODS JSON schemas

### ISSUE THREAD

**Issue by alanking** [irods/irods#6160]
### iRODS Version, OS and Version
main, centos, 7

### What did you try to do?
Start iRODS server

### Expected behavior
Flawless success

### Observed behavior (including steps to reproduce, if applicable)
Some warnings print out whenever the server is started:
```
$ ./irodsctl start
WARNING: Validation Failed for [/etc/irods/server_config.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/server_config.json]
        RefResolutionError: unknown url type: 'host_access_control.json'
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/service_account_environment.json]
        RefResolutionError: unknown url type: 'client_environment.json'
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 94, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 282, in validate_configuration
    lib.indent(*skipped)))
irods.exceptions.IrodsWarning: Skipped validation for the following files:
  /etc/irods/server_config.json
  /var/lib/irods/.irods/irods_environment.json
```
The server starts fine, but I think this should be investigated.

```bash
$ jsonschema --version
4.0.0
```

This is not observed with earlier versions of `jsonschema`; specifically, the version packaged by Canonical for ubuntu:18.04:
```bash
$ pip freeze | grep jsonschema # for some reason jsonschema --version doesn't work for this version
jsonschema==2.6.0
```

**Comment by trel** [comment]
I think this is about how jsonschema does dereferencing...
`RefResolutionError: unknown url type: 'client_environment.json`

So... yes, we fix that and I think we're in business again.

**Comment by alanking** [comment]
I believe this is a duplicate of #5930
