### ISSUE TITLE
setup error - IrodsError: post-install test failed.

### ISSUE THREAD

**Issue by xkdzml** [irods/irods#6312]
### iRODS Version, OS and Version
ubuntu 20.04

### What did you try to do?
python /var/lib/irods/scripts/setup_irods.py

### Expected behavior
setup_irods success.

### Observed behavior (including steps to reproduce, if applicable)
I installed it on other computers in the same way.
However, there is an error only on this computer, so I can't proceed anymore.
Is there a way to solve this?

```
syslab@cluster1:~/workspace_chu$ sudo python3 /var/lib/irods/scripts/setup_irods.py < /var/lib/irods/packaging/localhost_setup_postgres.input 
Warning: Hostname `cluster1` should be a fully qualified domain name.
iRODS user [irods]: 
iRODS group [irods]: 
iRODS server's role:
1. provider
2. consumer
Please select a number or choose 0 to enter a new value [1]: 
ODBC driver for postgres:
1. PostgreSQL ANSI
2. PostgreSQL Unicode
Please select a number or choose 0 to enter a new value [1]: 
Database server's hostname or IP address [localhost]: 
Database server's port [5432]: 
Database name [ICAT]: 
Database username [irods]: 

-------------------------------------------
Database Type: postgres
ODBC Driver:   PostgreSQL ANSI
Database Host: localhost
Database Port: 5432
Database Name: ICAT
Database User: irods
-------------------------------------------

Please confirm [yes]: 
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.


+-----------------------------------------------------+
| WARNING:                                            |
| The database specified is an already-configured     |
| iRODS database, so first-time database setup will   |
| not be performed. Providing different inputs from   |
| those provided the first time this script was run   |
| will result in unspecified behavior, and may put    |
| a previously working zone in a broken state. It's   |
| recommended that you exit this script now if you    |
| are running it manually. If you wish to wipe out    |
| your current iRODS installation and associated data |
| catalog, drop the database and recreate it before   |
| re-running this script.                             |
+-----------------------------------------------------+

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

iRODS server's zone name [tempZone]: 
iRODS server's port [1247]: 
iRODS port range (begin) [20000]: 
iRODS port range (end) [20199]: 
Control Plane port [1248]: 
Schema Validation Base URI (or off) [file:///var/lib/irods/configuration_schemas]: 
iRODS server's administrator username [rods]: 

-------------------------------------------
Zone name:                  tempZone
iRODS server port:          1247
iRODS port range (begin):   20000
iRODS port range (end):     20199
Control plane port:         1248
Schema validation base URI: file:///var/lib/irods/configuration_schemas
iRODS server administrator: rods
-------------------------------------------

Please confirm [yes]: 
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.


Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.


iRODS Vault directory [/var/lib/irods/Vault]: 
WARNING: Validation Failed for [/etc/irods/server_config.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/server_config.json]
        RefResolutionError: unknown url type: 'host_access_control.json'
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/service_account_environment.json]
        RefResolutionError: unknown url type: 'client_environment.json'
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 94, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 280, in validate_configuration
    raise IrodsWarning('%s\n%s' % (
irods.exceptions.IrodsWarning: Skipped validation for the following files:
  /etc/irods/server_config.json
  /var/lib/irods/.irods/irods_environment.json
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 445, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 134, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 155, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
```

And I have one more question.
I want to use this computer as a **client** and use another computer as a **server**, but I don't know what to do.
Do you have a **document or link** that shows how to do it?

**Comment by korydraughn** [comment]
Q. Is the server running and accepting connections?

You can test this by running the following:
```bash
sudo su - irods    # Become the irods service account user.
iput VERSION.json  # Put a file into iRODS.
ils                # If "iput" didn't produce an error, show that the file is in iRODS.
```

If `iput` failed, check the following:

Q. Does `/etc/irods/server_config.json` exist?
Q. Does `/var/lib/irods/.irods/irods_environment.json` exist?

If the answer is yes, try comparing those files to one of the other 4.3.0 server's config files.

If these files do not exist, try rerunning the setup script.

---
To run a client, you only need to install the icommands package. With that, you'd run `iinit`. `iinit` will prompt you for information like the hostname of the server to connect to.

If all goes well, you should be able to run other icommands.

**Comment by xkdzml** [comment]
I checked that there are server_config.json and irods_evironment.json.

I compared the contents with what I installed on another computer, and it was written the same way.

I got an error when I asked to try iput.

```
syslab@cluster1:~/workspace_chu/irods$ iput sample.json 
remote addresses: 127.0.0.1 ERROR: putUtil: put error for /tempZone/home/rods/sample.json, status = -520013 status = -520013 UNIX_FILE_MKDIR_ERR, Permission denied
```

**Comment by trel** [comment]
Check `/var/lib/irods/log/rodsLog*` for the reason you're getting the Unix permission error (`UNIX_FILE_MKDIR_ERR`).   

Guessing your vault location is not owned/operated by your service account.

**Comment by xkdzml** [comment]
i can't found ```/var/lib/irods/log/rodsLog*```.

Own of vault location is irods.

I compared owned for directories but it is the same with a different computer. 

If I reinstall irods, it is a well operate?

**Comment by trel** [comment]
just in case... the logfile does not literally end with `*`...

this is probably your logfile of interest...

```
/var/lib/irods/log/rodsLog.2022.04.11
```

**Comment by xkdzml** [comment]
I checked directory /var/lib/irods/log, but I don't find rodsLogs.

My computer has only these files.

```
syslab@cluster1:/var/lib/irods/log$ ls
control_log.txt  proc  setup_log.txt
```

**Comment by trel** [comment]
Okay, so the server really never got installed or stood up.

You say you've installed this on other machines, without any trouble?

**Comment by xkdzml** [comment]
yes, other machines are well operated.

**Comment by xkdzml** [comment]
I solved it by creating a new resource with ```iadmin mkresc```.

Thank you for your help.

**Comment by trel** [comment]
Excellent - it sounds like perhaps there was a typo in your original vault path or hostname.

Closing this issue.
