### ISSUE TITLE
irods setup fails on centOS 7

### ISSUE THREAD

**Issue by xkdzml** [irods/irods#6419]
## Bug Report
```
$ sudo python3 ./scripts/setup_irods.py < ./packaging/localhost_setup_postgres.input 

iRODS Vault directory [/var/lib/irods/Vault]: 
WARNING: Validation failed for /etc/irods/server_config.json -- jsonschema not installed
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation failed for /var/lib/irods/VERSION.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/VERSION.json, skipping validation...
WARNING: Validation failed for /var/lib/irods/.irods/irods_environment.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 94, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 282, in validate_configuration
    lib.indent(*skipped)))
irods.exceptions.IrodsWarning: Skipped validation for the following files:
  /etc/irods/server_config.json
  /var/lib/irods/VERSION.json
  /var/lib/irods/.irods/irods_environment.json
Error encountered running setup_irods:
Traceback (most recent call last):
  File "./scripts/setup_irods.py", line 447, in main
    test_mode=options.test_mode)
  File "./scripts/setup_irods.py", line 129, in setup_server
    IrodsController(irods_config).start(test_mode=test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 170, in start
    env=self.config.execution_environment)
  File "/var/lib/irods/scripts/irods/execute.py", line 117, in execute_command
    check_command_return(args, out, err, returncode, input=input, **kwargs)
  File "/var/lib/irods/scripts/irods/execute.py", line 113, in check_command_return
    indent(*deets)]))
irods.exceptions.IrodsError: Call to open process with ['/usr/sbin/irodsServer'] returned an error:
  Options passed to Popen:
    cwd: /usr/sbin
    env: HIDDEN
  Return code: 127
  Error output:
    /usr/sbin/irodsServer: error while loading shared libraries: libavrocpp.so.1.11.0: cannot open shared object file: No such file or directory
```
### iRODS Version, OS and Version
iRODS : 4.3.0
OS : centOS 7

I tried to fix the error, but I couldn't find a solution.
How can iRODS setup be successful?

**Comment by xkdzml** [comment]
Yes, ``irods-externals-avro1.11.0-1.x86.64`` is installed on the machine.

I was installed ``irods-externals-avro1.11.0-1.x86.64.rpm``

```
sudo yum install irods-externals-avro1.11.0-1.x86.64.rpm
```

**Comment by trel** [comment]
What SHA are you running?  4.3.0 isn't quite released yet.

**Comment by xkdzml** [comment]
The code downloaded from GitHub was executed.

When I ran the same file on ubuntu 20.02 and checked it, it came out as 4.3.0
```
syslab@chu:~$ ienv
irods_version - 4.3.0
irods_session_environment_file - /home/syslab/.irods/irods_environment.json.172274
irods_environment_file - /home/syslab/.irods/irods_environment.json
irods_host - 127.0.0.1
irods_port - 1247
irods_zone_name - tempZone
irods_user_name - rods
```
 
And I modified the pg_hba.conf
```
$ sudo vim /var/lib/pgsql/data/pg_hba.conf
```
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            ident
# IPv6 local connections:
host    all             all             ::1/128                 ident
```
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```

**Comment by trel** [comment]
Can you share the contents of `/var/lib/irods/VERSION.json.dist`?

**Comment by xkdzml** [comment]
Yes, I can share the contests of `/var/lib/irods/VERSION.json.dist`.
```
{
    "irods_version": "4.3.0",
    "catalog_schema_version": 8,
    "commit_id": "e53e8daa66005cc2fd6617979339ac6d1d0f30ab",
    "configuration_schema_version": 4
}
```

**Comment by trel** [comment]
e53e8daa66005cc2fd6617979339ac6d1d0f30ab Is from Feb 23.   Can you try a newer commit?

**Comment by xkdzml** [comment]
I solved the problem, but another problem came up.

```
Please confirm [yes]: 
Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.

Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.


Warning: Cannot control echo output on the terminal (stdin is not a tty). Input may be echoed.


WARNING: Validation failed for /etc/irods/server_config.json -- jsonschema not installed
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation failed for /var/lib/irods/version.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/version.json, skipping validation...
WARNING: Validation failed for /var/lib/irods/.irods/irods_environment.json -- jsonschema not installed
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 94, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 296, in validate_configuration
    lib.indent(*skipped)))
irods.exceptions.IrodsWarning: Skipped validation for the following files:
  /etc/irods/server_config.json
  /var/lib/irods/version.json
  /var/lib/irods/.irods/irods_environment.json
Error encountered running setup_irods:
Traceback (most recent call last):
  File "./scripts/setup_irods.py", line 517, in main
    test_mode=options.test_mode)
  File "./scripts/setup_irods.py", line 139, in setup_server
    IrodsController(irods_config).start(test_mode=test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 189, in start
    raise IrodsError('iRODS server failed to start.')
irods.exceptions.IrodsError: iRODS server failed to start.
```

**Comment by trel** [comment]
Great - so... what did you do to fix the first problem?

And, what, if anything, is in the log file for this new problem?

**Comment by xkdzml** [comment]
```
[cau@aida_dev irods]$ cat /etc/ld.so.conf.d/irods.conf 
/opt/irods-externals/avro1.11.0-1/lib
/opt/irods-externals/boost1.78.0-0/lib
/opt/irods-externals/fmt8.1.1-0/lib
/opt/irods-externals/zeromq4-14.1.8-0/lib
/opt/irods-externals/clang-runtime13.0.0-0/lib
/opt/irods-externals/nanodbc2.13.0-1/lib
[cau@aida_dev irods]$ sudo ldconfig
```

I saw /var/lib/irods/log/control_log.txt, and it was written like this at the end.

```
2022-05-26T03:11:40.579Z -    INFO -                  controller.py: 196 - Failure
2022-05-26T03:11:40.580Z -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start(write_to_stdout=options.write_to_stdout, test_mode=options.test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 189, in start
    raise IrodsError('iRODS server failed to start.')
irods.exceptions.IrodsError: iRODS server failed to start.
2022-05-26T03:11:40.581Z -    INFO -               irods_control.py: 128 - Exiting...
2022-05-26T04:01:37.039Z -   DEBUG -                  controller.py: 218 - Calling stop on IrodsController
2022-05-26T04:01:37.039Z -    INFO -                  controller.py: 219 - Stopping iRODS server...
2022-05-26T04:01:37.040Z - WARNING -                  controller.py: 224 - Server pidfile missing or stale. No iRODS server running?
2022-05-26T04:01:37.041Z -    INFO -                  controller.py: 253 - Success
2022-05-26T04:01:47.923Z -   DEBUG -                  controller.py: 263 - Calling status on IrodsController
2022-05-26T04:01:47.924Z -    INFO -                  controller.py: 267 - No iRODS servers running.
```

**Comment by xkdzml** [comment]
I tried to install version 4.2.11 but I needed version 6 of clang.

So I tried to install version 4.2.7 of externals, but it was not installed from externals.

Eventually, I tried to install the recently updated irods again, but this time a new error occurred. 

How can we solve this?
```
$ sudo python3 ./scripts/setup_irods.py < ./packaging/localhost_setup_postgres.input

Error encountered running setup_irods:
Traceback (most recent call last):
  File "./scripts/setup_irods.py", line 447, in main
    test_mode=options.test_mode)
  File "./scripts/setup_irods.py", line 129, in setup_server
    IrodsController(irods_config).start(test_mode=test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 143, in start
    database_interface.server_launch_hook(self.config)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 70, in server_launch_hook
    update_catalog_schema(irods_config, cursor)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 58, in update_catalog_schema
    schema_version_in_database, irods_config.version['catalog_schema_version'])
irods.exceptions.IrodsError: ('Schema version in catalog (%d) is newer than schema version in the version file (%d); downgrading of catalog schema risks losing data and is unsupported.', 9, 8)
```

**Comment by xkdzml** [comment]
Irods was executed yesterday, but suddenly, Irods is not executed.

```
$ python3 ./scripts/setup_irods.py < ./packaging/localhost_setup_postgres.input

Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 134, in start
    s.bind(('127.0.0.1', irods_port))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/setup_irods.py", line 517, in main
    test_mode=options.test_mode)
  File "./scripts/setup_irods.py", line 139, in setup_server
    IrodsController(irods_config).start(test_mode=test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 138, in start
    sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 671, in reraise
    raise value.with_traceback(tb)
  File "/var/lib/irods/scripts/irods/controller.py", line 134, in start
    s.bind(('127.0.0.1', irods_port))
irods.exceptions.IrodsError: Could not bind port 1247.
```

**Comment by korydraughn** [comment]
Seems you may have a left over iRODS process running.

Run `ps` and see if there is an `irodsServer` process listed. If so, kill it and try running the setup script again.

**Comment by xkdzml** [comment]
One computer succeeded in installing iRODS, but the other did not. It's the same centos7.
```
$ sudo python3 ./scripts/setup_irods.py < ./packaging/localhost_setup_postgres.input

Error encountered running setup_irods:
Traceback (most recent call last):
  File "./scripts/setup_irods.py", line 517, in main
    test_mode=options.test_mode)
  File "./scripts/setup_irods.py", line 139, in setup_server    IrodsController(irods_config).start(test_mode=test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 189, in start
    raise IrodsError('iRODS server failed to start.')
irods.exceptions.IrodsError: iRODS server failed to start.

```
When I looked at the log, I saw this error.
```
$ vim /var/lib/irods/log/control_log.txt
2022-06-07T03:19:14.677Z -   DEBUG -                  controller.py: 176 - Attempting to connect to iRODS server on port 1247. Attempt #100
2022-06-07T03:19:14.678Z -    INFO -                  controller.py: 196 - Failure
2022-06-07T03:19:14.678Z -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start(write_to_stdout=options.write_to_stdout, test_mode=options.test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 197, in start
    six.reraise(IrodsError, e, sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 672, in reraise
    raise value
  File "/var/lib/irods/scripts/irods/controller.py", line 189, in start
    raise IrodsError('iRODS server failed to start.')
irods.exceptions.IrodsError: iRODS server failed to start.
2022-06-07T03:19:14.680Z -    INFO -               irods_control.py: 128 - Exiting...
```

**Comment by trel** [comment]
This does not feel like a code issue in need of a fix.   Closing.

Please send configuration and discussion topics to our Google Group:   https://groups.google.com/g/irod-chat
