### ISSUE TITLE
iRODS v4.3 test installation on Rocky Linux v8.6

### ISSUE THREAD

**Issue by ll4strw** [irods/irods#6442]
## Bug Report

I am testing iRODS on Rocky Linux OS v8.6. Eventually I get the iRODS server to run as a provider even though the  ``Post-install test`` fails with error
```
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 517, in main
    test_mode=options.test_mode)
  File "/var/lib/irods/scripts/setup_irods.py", line 150, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
```
iRODS logs show

```
{"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[rsDataObjOpen_impl:904] - [HIERARCHY_ERROR: no valid resource found for data object\n\n] [error_code=[-1803000], path=[/IL/home/rods/post_install_test.1655384066604924.txt], hierarchy=[]","request_api_name":"","request_api_number":20003,"request_api_version":"d","request_client_user":"rods","request_host":"YYYY","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"xxxxx","server_pid":224669,"server_timestamp":"2022-06-16T12:54:26.927Z","server_type":"agent"}
{"log_category":"api","log_facility":"local0","log_level":"error","log_message":"Could not open replica [error_code=-1803000]","request_api_name":"","request_api_number":20003,"request_api_version":"d","request_client_user":"rods","request_host":"YYYYY","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"XXXXX","server_pid":224669,"server_timestamp":"2022-06-16T12:54:26.927Z","server_type":"agent"}

```

### iRODS Version, OS and Version
iRODS v4.3.0-1
Rocky Linux v8.6
MySQL  v8.0.26

### What did you try to do?

```
rpm --import https://packages.irods.org/irods-signing-key.asc
wget -qO - https://packages.irods.org/renci-irods.yum.repo | sudo tee /etc/yum.repos.d/renci-irods.yum.repo
yum install epel-release
yum install mysql-server.x86_64
yum install rsyslog.x86_64
yum install python3-jsonschema.noarch
service mysqld start
mysql_secure_installation
python3 /var/lib/irods/scripts/setup_irods.py

            iRODS user [irods]:
            iRODS group [irods]:
            iRODS server's role:
            1. provider
            2. consumer
            Please select a number or choose 0 to enter a new value [1]: 1
            ODBC driver for mysql [MySQL]: mariadb
            Database server's hostname or IP address [localhost]:
            Database server's port [3306]:
            Database name [ICAT]:
            Database username [irods]:

            -------------------------------------------
            Database Type: mysql
            ODBC Driver:   mariadb
            Database Host: localhost
            Database Port: 3306
            Database Name: ICAT
            Database User: irods
            -------------------------------------------

            Please confirm [yes]:
            Database password:
            Salt for passwords stored in the database:
            Local storage on this server [yes]:
            Default resource [ILResc]:
            iRODS Vault directory [/var/lib/irods/Vault]:
            iRODS server's zone name [IL]:
            iRODS server's port [1247]:
            iRODS port range (begin) [20000]:
            iRODS port range (end) [20199]:
            Control Plane port [1248]:
            Schema Validation Base URI (or off) [file:///var/lib/irods/configuration_schemas]:
            iRODS server's administrator username [rods]:

            -------------------------------------------
            Zone name:                  IL
            iRODS server port:          1247
            iRODS port range (begin):   20000
            iRODS port range (end):     20199
            Control plane port:         1248
            Schema validation base URI: file:///var/lib/irods/configuration_schemas
            iRODS server administrator: rods
            -------------------------------------------
            Please confirm [yes]:
            iRODS server's zone key:
            iRODS server's negotiation key (32 characters):
            Control Plane key (32 characters):

            iRODS server's administrator password:



Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 517, in main
    test_mode=options.test_mode)
  File "/var/lib/irods/scripts/setup_irods.py", line 150, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.

```
The iCAT database was set up in the following manner
```
CREATE database ICAT
CREATE USER 'irods'@'localhost' IDENTIFIED BY 'xxxxxx';
GRANT ALL PRIVILEGES ON ICAT.* to 'irods'@'localhost';
SET GLOBAL log_bin_trust_function_creators = 1;
flush privileges;
```

### Expected behavior

Post installation tests should complete successfully instead of terminating with an error.

Also, while ``izonereport`` successfully displays my zone info, the iRODS logs show the following error
```
{"log_category":"legacy","log_facility":"local0","log_level":"error","log_message":"[-]\t/irods_source/server/api/src/rsServerReport.cpp:261:irods::error get_host_system_information(json &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]\n\t[-]\t/irods_source/server/core/src/miscServerFunct.cpp:3008:irods::error get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &) :  status [FILE_READ_ERR]  errno [] -- message [fgets() failed. feof[1] ferror[0] pclose[256]]\n\n","request_api_name":"ZONE_REPORT_AN","request_api_number":10205,"request_api_version":"d","request_client_user":"rods","request_host":"Y.Y.Y.Y","request_proxy_user":"rods","request_release_version":"rods4.3.0","server_host":"xxxxxxx","server_pid":224507,"server_timestamp":"2022-06-16T12:47:24.170Z","server_type":"agent"}
```

### Observed behavior (including steps to reproduce, if applicable)

See above. Any idea of what the problem is? Thanks in advance.

**Comment by trel** [comment]
I notice that many of the answers are prepopulated when the `setup_irods.py` script is run... this suggests it has been run at least once prior...

Since the error is `no valid resource found for data object`, did you use a different resource name the 'first' time you ran this script?   Maybe it's remembering something incorrectly - consider a clean install after removing the database, the packages, `/var/lib/irods`, `/tmp/irods`, `/etc/irods`.

If that works - we're very interested in the original steps to reproduce this erroneously-remembered information by the setup script.

**Comment by trel** [comment]
Do you happen to have a non-default umask?

The `FILE_READ_ERR` suggests the server just can't see/read the files it's supposed to be in charge of...
- first, the test file in the vault during setup, and
- second, the `scripts/system_identification.py` to populate a zone report.

Can you share `ls -l /var/lib/irods` and `ls -l /etc/irods`?

**Comment by trel** [comment]
All of that output looks normal and good - until the error.

`/usr/sbin/irodsTestPutGet` is run as the service account.

What happens when you run it manually as the `irods` service account?

**Comment by trel** [comment]
Well, so it's reproducible - at least on your machine.     We'll try here too.

**Comment by SwooshyCueb** [comment]
It's in here https://github.com/irods/irods/tree/4-3-stable/test/post_install_test

**Comment by trel** [comment]
Getting closer.

So it seems the zone report still cannot read the configuration file...

**Comment by alanking** [comment]
Also, `izonereport` worked for me with the testing environment with the above-linked configuration and no additional effort, so I imagine there is something else in the configuration which may need adjusting.

**Comment by korydraughn** [comment]
That error could also be due to the implementation of `get_script_output_single_line(const std::string &, const std::string &, const std::vector<std::string> &, std::string &)`.

I have seen situations where it is invoked and while the output appears correct, an error message is written to the log. That is one of the reasons for issue https://github.com/irods/irods/issues/6273

**Comment by trel** [comment]
Ah, okay - so if you don't define any local storage, the next question it asks about the default resource is expected/assumed to exist on *another* iRODS server in the same zone.  So, that could explain the `CAT_NO_ROWS_FOUND` - as it's looking for the defined resource in the catalog to resolve the location, and ... can't find it.

It appears #6273 is more common than we had seen ourselves if you're getting it repeatedly.   We'll get that fixed - and we're going to add Rocky to our test matrix.

**Comment by trel** [comment]
@SwooshyCueb @alanking can we think about this for 4.3.1 as well?   Not sure there is anything to do other than confirm things are behaving.

**Comment by alanking** [comment]
We can try running Rocky Linux 8 through tests with our AlmaLinux 8 packages but otherwise I'm not sure what else there is to do...

**Comment by trel** [comment]
Our packaging is now tested and working as designed on EL8 and EL9 for the latest releases.

Candidate for closing.

**Comment by SwooshyCueb** [comment]
Yes, 4.3 is working on EL8 now
