### ISSUE TITLE
`test_ifsck__2650` test failure

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#6705]
- [ ] `main`
- [ ] `4-3-stable`

---

the `irods.test.test_resource_types.Test_Resource_Unixfilesystem.test_ifsck__2650` test fails with iRODS built from 9dc367a7c4b22f482a80eb9efd9cae2c13b28f4b:

```
 --- IrodsSession: icommand executed by [otherrods] [iput -K /tmp/fsckfile.txt /tempZone/home/otherrods/2022-11-07Z17:54:07--irods-testing-mjbfm5b3/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt] --- 
Assert Command: iput -K /tmp/fsckfile.txt /tempZone/home/otherrods/2022-11-07Z17:54:07--irods-testing-mjbfm5b3/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | remote addresses: 172.17.0.2 ERROR: putUtil: put error for /tempZone/home/otherrods/2022-11-07Z17:54:07--irods-testing-mjbfm5b3/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt, status = -526036 status = -526036 UNIX_FILE_GET_FS_FREESPACE_ERR, File name too long
Unexpected output on stderr

FAILED TESTING ASSERTION
```

```
irods.test.test_resource_types.Test_Resource_Unixfilesystem.test_ifsck__2650 ... FAIL

======================================================================
FAIL: test_ifsck__2650 (irods.test.test_resource_types.Test_Resource_Unixfilesystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_resource_types.py", line 571, in test_ifsck__2650
    self.admin.assert_icommand('iput -K ' + filepath + ' ' + full_logical_path)  # iput
  File "/var/lib/irods/scripts/irods/test/session.py", line 160, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError

```

**Comment by alanking** [comment]
This test passes for me using the esting environment. I then ran the test manually in a Debian 11 container from the testing environment with a build based on 084e1dabe017abb71f7658f8280d0361bf8a2cb1 and it passed 100 times. 

Do we know on which platform / database this failure occurred? Was it a debug build or a release build? Was PREP involved in any way?

If we do not know the answers to these questions, I think we should just close this.

**Comment by SwooshyCueb** [comment]
Almost certainly postgres, probably a debug build, maybe was Ubuntu 18.04, don't know if PREP was involved

**Comment by alanking** [comment]
It has been several releases since this was opened. We can open a new issue if it resurfaces.
