### ISSUE TITLE
Getting parsing and SSL connection errors with the logical quota plugin configured if there is unspecified rule instance call

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#6831]
- [x] main
- [x] 4-2-stable

\* Logical quotas repo does not have a 4-3-stable branch

---
### iRODS Version, OS and Version
iRODS 4.2.11 centos7

### What did you try to do?
I called a python rule with a rule file without specifying the python rule engine instance.

### Expected behavior
Not to see any crashes/error on the client side and might expect to see a parsing error in the log.

### Observed behavior (including steps to reproduce, if applicable)
I guess I encountered a similar thing at the discussion [here ](https://github.com/irods/irods/issues/6286)

the order of the existing rule engine plugins:
```
-bash-4.2$ irule -a
Level 0: Available rule engine plugin instances:
        irods_rule_engine_plugin-logical_quotas-instance
        irods_rule_engine_plugin-irods_rule_language-instance
        irods_rule_engine_plugin-cpp_default_policy-instance
        irods_rule_engine_plugin-python-instance
```

a python rule in the core.py:
```
def testZone(rule_args, callback, rei):
    callback.writeLine("serverLog", "Hello, the zone - {} - is being tested.".format(rei.rsComm.proxyUser.rodsZone))
```

calling this said rule by `irule` without specifying the python rule engine:
```
-bash-4.2$ irule -F test_py.r
remote addresses: 10.0.2.100 ERROR: rcExecMyRule error.  status = -154000 SYS_INTERNAL_ERR
 ERROR: [-]     /work/lib/core/src/rcConnect.cpp:279:int rcDisconnect(rcComm_t *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
        [-]     /work/lib/core/src/sockComm.cpp:98:irods::error sockClientStop(irods::network_object_ptr, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [failed to call 'client stop']
                [-]     /work/plugins/network/ssl/libssl.cpp:645:irods::error ssl_client_stop(irods::plugin_context &, rodsEnv *) :  status [SSL_SHUTDOWN_ERROR]  errno [] -- message [error shutting down the SSL connection]
```
in the logs:
`rsyslogd stdout | 2023-01-06T17:15:33.867405+01:00 dev-u0137480-instance1 rodsServer[136]: (null) -  ERROR: Agent process [3744] exited with status [6]
`
calling the same python rule by PRC:
```
>>> import os, os.path
>>> from irods.session import iRODSSession
>>> from irods.rule import Rule
>>> env_file = os.getenv('IRODS_ENVIRONMENT_FILE', os.path.expanduser('~/.irods/irods_environment.json'))
>>> with iRODSSession(irods_env_file=env_file) as session:
...     Rule( session, rule_file = 'test_py.r').execute()
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/irods/rule.py", line 157, in execute
    response = conn.recv(acceptable_errors = acceptable_errors, return_message = return_message)
  File "/usr/lib/python2.7/site-packages/irods/connection.py", line 124, in recv
    raise NetworkException("Could not receive server response")
irods.exception.NetworkException: Could not receive server response
```
However calling a native rule by a rule file without specifying the rule instance throws parsing errors in logs  - nothing on the client end:

```
-bash-4.2$ irule -F test_native.r
-bash-4.2$
```
in the logs:
```
rsyslogd stdout | 2023-01-06T17:18:27.155163+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: [logical_quotas] error => [json.exception.parse_error.101] parse error at line 2, column 3: syntax error while parsing object key - invalid literal; last read: '{<U+000A>  m'; expected string literal
rsyslogd stdout | 2023-01-06T17:18:27.155313+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: Rule Engine Plugin returned [-349000].
rsyslogd stdout | 2023-01-06T17:18:27.155452+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - NOTICE: writeLine: inString = TEST
rsyslogd stdout | 2023-01-06T17:18:27.155674+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: [addMsParamToArray] - type is null for [ruleExecOut]
rsyslogd stdout | 2023-01-06T17:18:27.155986+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: caught python exception:   File "<string>", line 1#012    myCaller {#012             ^#012SyntaxError: invalid syntax

```

**Comment by korydraughn** [comment]
I would expect Logical Quotas to produce the following for both cases:
```
rsyslogd stdout | 2023-01-06T17:18:27.155163+01:00 dev-u0137480-instance1 rodsServer[3757]: u0137480_instance1 - remote addresses: 10.0.2.100, 2a02:2c40:0:51:177:0:a:c6f6 ERROR: [logical_quotas] error => [json.exception.parse_error.101] parse error at line 2, column 3: syntax error while parsing object key - invalid literal; last read: '{<U+000A>  m'; expected string literal
```

For the most part, invoking `irule` without a target REP instance is probably not what you want.

We'll tighten up the REPs so that they fail gracefully.

**Comment by korydraughn** [comment]
After some investigation, the Logical Quotas REP did contain a bug around the handling of `irule -F`.

I've created a PR that resolves the issue here: irods/irods_rule_engine_plugin_logical_quotas/pull/87

Only the Hard Links REP shares this problem, but we can ignore that REP for now as it won't see a release any time soon.
