### ISSUE TITLE
`UnicodeEncodeError` during setup of `test_targeting_specific_replica_number.test_targeting_specific_replica_number__issue_6896` causes cascading test failures

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7063]
- [x] main
- [x] 4-3-stable
---
While running tests for #7005, I ran into unrelated test failures in `test_targeting_specific_replica_number`.

The `setUp` method of `test_targeting_specific_replica_number__issue_6896` fails with a `UnicodeEncodeError` exception on line 38:
https://github.com/irods/irods/blob/25d8f67df6c123ee6f0b3fe4695e4042b52cdb59/scripts/irods/test/test_targeting_specific_replica_number.py#L38
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 164-166: ordinal not in range(128)
Call stack:
  File "/var/lib/irods/scripts/run_tests.py", line 206, in <module>
    results = run_tests_from_names(test_identifiers, options.buffer_test_output, options.xml_output, options.skip_until)
  File "/var/lib/irods/scripts/run_tests.py", line 127, in run_tests_from_names
    results = runner.run(super_suite)
  File "/usr/local/lib/python3.6/dist-packages/xmlrunner/runner.py", line 67, in run
    test(result)
  File "/usr/lib/python3.6/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.6/unittest/case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/unittest/case.py", line 601, in run
    self.setUp()
  File "/var/lib/irods/scripts/irods/test/test_targeting_specific_replica_number.py", line 38, in setUp
    self.admin.assert_icommand('ilsresc', 'STDOUT') # debugging
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 84, in _assert_helper
    out, err, rc = lib.execute_command_permissive(command_arg, **kwargs)
  File "/var/lib/irods/scripts/irods/execute.py", line 90, in execute_command_permissive
    out, err = communicate_and_log(p, args, input)
  File "/var/lib/irods/scripts/irods/execute.py", line 37, in communicate_and_log
    l.debug('\n'.join(message))
Message: 'Command ilsresc returned with code 0.\nstdout:\n  demoResc:unixfilesystem\n  pt1:passthru\n  └── ufs1:unixfilesystem\n  pt2:passthru\n  └── ufs2:unixfilesystem'
Arguments: ()
```

This causes all tests in `test_targeting_specific_replica_number__issue_6896` to error out before the tests themselves can run, and leaves the irods server partially set-up for the tests in this class, which causes cascading test errors/failures, like so:
```
--- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser otherrods rodsadmin] --- 
Assert Command: iadmin mkuser otherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | Level 0: Error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME
    | Level 1: DEBUG: 
    | 
  stderr:
    | remote addresses: 172.29.0.5 ERROR: rcGeneralAdmin failed with error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME 
Unexpected output on stderr

FAILED TESTING ASSERTION
```

**Comment by alanking** [comment]
What platform were these tests running on?
