### ISSUE TITLE
Agent crashes when rule input is mishandled

### ISSUE THREAD

**Issue by alanking** [irods/irods#7074]
### iRODS Version, OS and Version
4.2.12ish (probably affects all versions)

### What did you try to do?
I had the following rule:
```python
# rule.r
check_access {
    *access = 0;
    msiCheckAccess("*logical_path", "read object", *access);
}
INPUT *logical_path="/tempZone/home/alan/foo"
OUTPUT ruleExecOut
```
And I executed the rule file via `irule` as user `alan`:
```bash
$ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F rule.r /tempZone/home/rods/foo
```

### Expected behavior
Regardless of whether the rule is correct or the invocation of `irule` is correct, I expect agents not to crash.

### Observed behavior (including steps to reproduce, if applicable)
The agent crashes with the following stacktrace:
```
Caught signal [11]. Dumping stacktrace and exiting

Dumping stack trace
<0>     Offset:         Address: 0x7f5b7e2f1143 /usr/lib/libirods_server.so.4.2.11(+0xb52143) [0x7f5b7e2f1143]
<1>     Offset:         Address: 0x7f5b7b472980 /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f5b7b472980]
<2>     Offset: 0x137   Address: 0x7f5b787f1437 nextRuleGenStringExpression(pointer*, ParserContext*, token*)
```
And the output from `irule`:
```
remote addresses: 127.0.0.1 ERROR: rcExecMyRule error.  status = -154000 SYS_INTERNAL_ERR
```
Please investigate.

**Comment by alanking** [comment]
Just in case I don't finish in time, here's the function mentioned in the stacktrace (the name is generated via macros):
https://github.com/irods/irods/blob/3af66900a0189690deaece96d61f26a52b6c3f7b/plugins/rule_engines/irods_rule_language/src/parser.cpp#L1273-L1338

**Comment by korydraughn** [comment]
How did we end up in NREP parser code? Does the crash happen in there?

**Comment by trel** [comment]
so ... we could easily rr this?   and see where it breaks?

**Comment by alanking** [comment]
> How did we end up in NREP parser code? Does the crash happen in there?

I suppose so, based on the stacktrace.

> so ... we could easily rr this? and see where it breaks?

The plan is to sniff things out with address sanitizer first, yes.

**Comment by alanking** [comment]
Thanks to ASAN, I was able to find the following when running the steps to reproduce...

First, and less importantly, two leaks in `irule`:
```bash
$ irule -r irods_rule_engine_plugin-irods_rule_language-instance -F rule.r /tempZone/home/rods/foo
remote addresses: 192.168.16.3 ERROR: rcExecMyRule error.  status = -154000 SYS_INTERNAL_ERR

=================================================================
==4888==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 11968 byte(s) in 1 object(s) allocated from:
    #0 0x4ddb07 in malloc /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7fe2537e9662 in resizeStrArray /irods_source/lib/core/src/rcMisc.cpp:1000:31
    #2 0x51e5af in parseParameters(boost::program_options::variables_map, int, ExecMyRuleInp*, char*) /icommands_source/src/irule.cpp:576:5
    #3 0x51c742 in main /icommands_source/src/irule.cpp:348:21
    #4 0x7fe252dbad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4a1e07 in strdup /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:439:3
    #1 0x520e6e in quoteString(char const*, int, int) /icommands_source/src/irule.cpp:525:16
    #2 0x520193 in parseParameters(boost::program_options::variables_map, int, ExecMyRuleInp*, char*) /icommands_source/src/irule.cpp:705:31
    #3 0x51c742 in main /icommands_source/src/irule.cpp:348:21
    #4 0x7fe252dbad8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: 11992 byte(s) leaked in 2 allocation(s).
```
More importantly, we have some line numbers...
```
==4889==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff6b701760 at pc 0x7fdc636f7f6d bp 0x7fff6b7012f0 sp 0x7fff6b7012e8                                                                                                                                       
WRITE of size 4 at 0x7fff6b701760 thread T0                                                                                                                                                                                                                                     
    #0 0x7fdc636f7f6c in nextRuleGenStringExpression(pointer*, ParserContext*, token*) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1304:14                                                                                                            
    #1 0x7fdc63728c3c in nextRuleGenPathExpression(pointer*, ParserContext*) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1351:1                                                                                                                       
    #2 0x7fdc63709994 in nextRuleGenValue(pointer*, ParserContext*, int) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1422:1                                                                                                                           
    #3 0x7fdc6368a01d in nextRuleGenTerm(pointer*, ParserContext*, int, int) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1216:1                                                                                                                       
    #4 0x7fdc63741ae4 in parseTermRuleGen(pointer*, int, ParserContext*) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:3386:5                                                                                                                           
    #5 0x7fdc637523a7 in parseAndComputeExpression(char*, env*, RuleExecInfo*, int, ErrorStack*, region*) /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:521:16                                                                                           
    #6 0x7fdc63752088 in parseAndComputeMsParamArrayToEnv(MsParamArray*, env*, RuleExecInfo*, int, ErrorStack*, region*) /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:85:15                                                                             
    #7 0x7fdc637529eb in parseAndComputeRuleAdapter(char*, MsParamArray*, RuleExecInfo*, int, region*) /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:119:23                                                                                              
    #8 0x7fdc6363af4d in execMyRuleWithSaveFlag(char*, MsParamArray*, char const*, RuleExecInfo*, int) /irods_source/plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp:316:9                                                                                          
    #9 0x7fdc6363ac5b in execMyRule(char*, MsParamArray*, char const*, RuleExecInfo*) /irods_source/plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp:243:12                                                                                                          
    #10 0x7fdc63790fb4 in exec_rule_text(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback) /irods_s
ource/plugins/rule_engines/irods_rule_language/src/irods_rule_language.cpp:357:24                                                                                                                                                                                               
    #11 0x7fdc637c7198 in irods::error std::__invoke_impl<irods::error, irods::error (*&)(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::al
locator<char> > const&, irods::callback), std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback>(std::__
invoke_other, irods::error (*&)(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback), std::tuple<>&, s
td::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/b
its/invoke.h:61:14                                                                                                                                                                                                                                                              
    #12 0x7fdc637c7198 in std::enable_if<is_invocable_r_v<irods::error, irods::error (*&)(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::al
locator<char> > const&, irods::callback), std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback>, irods:
:error>::type std::__invoke_r<irods::error, irods::error (*&)(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irod
s::callback), std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback>(irods::error (*&)(std::tuple<>&, st
d::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback), std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<
char>, std::allocator<char> > const&, MsParamArray*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:114:9
    #13 0x7fdc637c7198 in std::_Function_handler<irods::error (std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, iro
ds::callback), irods::error (*)(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback)>::_M_invoke(std::
_Any_data const&, std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback&&) /usr/lib/gcc/x86_64-linux-g
nu/11/../../../../include/c++/11/bits/std_function.h:290:9
    #14 0x7fdc6b7d970f in std::function<irods::error (std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callb
ack)>::operator()(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, irods::callback) const /usr/lib/gcc/x86_64-linux
-gnu/11/../../../../include/c++/11/bits/std_function.h:590:9
    #15 0x7fdc6b7d970f in irods::pluggable_rule_engine<std::tuple<> >::exec_rule_text(std::tuple<>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::alloca
tor<char> > const&, irods::callback) /irods_source/server/re/include/irods/irods_re_plugin.hpp:253:24
    #16 0x7fdc6b7d72a3 in irods::rule_engine_context_manager<std::tuple<>, RuleExecInfo*, (irods::rule_execution_manager_pack)0>::exec_rule_text(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::c
har_traits<char>, std::allocator<char> > const&, MsParamArray*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /irods_source/server/re/include/irods/irods_re_plugin.hpp:606:41
    #17 0x7fdc6b7d5f4b in rsExecMyRule(RsComm*, ExecMyRuleInp*, MsParamArray**) /irods_source/server/api/src/rsExecMyRule.cpp:96:35
    #18 0x7fdc6c13ae2e in int std::__invoke_impl<int, int (*&)(RsComm*, ExecMyRuleInp*, MsParamArray**), RsComm*, ExecMyRuleInp*, MsParamArray**>(std::__invoke_other, int (*&)(RsComm*, ExecMyRuleInp*, MsParamArray**), RsComm*&&, ExecMyRuleInp*&&, MsParamArray**&&) /usr/li
b/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:14
    #19 0x7fdc6c13ae2e in std::enable_if<is_invocable_r_v<int, int (*&)(RsComm*, ExecMyRuleInp*, MsParamArray**), RsComm*, ExecMyRuleInp*, MsParamArray**>, int>::type std::__invoke_r<int, int (*&)(RsComm*, ExecMyRuleInp*, MsParamArray**), RsComm*, ExecMyRuleInp*, MsParamA
rray**>(int (*&)(RsComm*, ExecMyRuleInp*, MsParamArray**), RsComm*&&, ExecMyRuleInp*&&, MsParamArray**&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:114:9
    #20 0x7fdc6c13ae2e in std::_Function_handler<int (RsComm*, ExecMyRuleInp*, MsParamArray**), int (*)(RsComm*, ExecMyRuleInp*, MsParamArray**)>::_M_invoke(std::_Any_data const&, RsComm*&&, ExecMyRuleInp*&&, MsParamArray**&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../
include/c++/11/bits/std_function.h:290:9
    #21 0x7fdc6bec2e55 in std::function<int (RsComm*, ExecMyRuleInp*, MsParamArray**)>::operator()(RsComm*, ExecMyRuleInp*, MsParamArray**) const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590:9
    #22 0x7fdc6bec2e55 in irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**>::operator()(irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**) /irods_source/lib/core/include/irods/apiHandler.hpp:125:23
    #23 0x7fdc6bec2a09 in irods::error std::__invoke_impl<irods::error, irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**>&, irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**>(std::__invoke_other, irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**>&
, irods::plugin_context&, RsComm*&&, ExecMyRuleInp*&&, MsParamArray**&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:14
    #24 0x7fdc6bec2a09 in std::enable_if<is_invocable_r_v<irods::error, irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**>&, irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**>, irods::error>::type std::__invoke_r<irods::error, irods::api_call_adaptor<Ex
ecMyRuleInp*, MsParamArray**>&, irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**>(irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**>&, irods::plugin_context&, RsComm*&&, ExecMyRuleInp*&&, MsParamArray**&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../i
nclude/c++/11/bits/invoke.h:114:9
    #25 0x7fdc6bec2a09 in std::_Function_handler<irods::error (irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**), irods::api_call_adaptor<ExecMyRuleInp*, MsParamArray**> >::_M_invoke(std::_Any_data const&, irods::plugin_context&, RsComm*&&, ExecMyRuleInp*&&
, MsParamArray**&&) /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290:9
    #26 0x7fdc6bb9fd81 in std::function<irods::error (irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**)>::operator()(irods::plugin_context&, RsComm*, ExecMyRuleInp*, MsParamArray**) const /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_
function.h:590:9
    #27 0x7fdc6bb9fd81 in int irods::api_entry::call_handler<ExecMyRuleInp*, MsParamArray**>(RsComm*, ExecMyRuleInp*, MsParamArray**) /irods_source/lib/core/include/irods/apiHandler.hpp:227:30
    #28 0x7fdc6ba4b5e8 in call_execMyRuleInp_msParamArrayOut(irods::api_entry*, RsComm*, ExecMyRuleInp*, MsParamArray**) /irods_source/server/core/src/irods_api_calling_functions.cpp:701:18
    #29 0x7fdc6c23851d in rsApiHandler(RsComm*, int, BytesBuf*, BytesBuf*) /irods_source/server/core/src/rsApiHandler.cpp:213:18
    #30 0x7fdc6c23f082 in readAndProcClientMsg(RsComm*, int) /irods_source/server/core/src/rsApiHandler.cpp:601:18
    #31 0x7fdc6c1f517b in agentMain(RsComm*) /irods_source/server/core/src/rodsAgent.cpp:860:18
    #32 0x7fdc6c1f06e6 in runIrodsAgentFactory(sockaddr_un) /irods_source/server/core/src/rodsAgent.cpp:723:14
    #33 0x5683d9 in main::$_1::operator()() const /irods_source/server/main_server/src/rodsServer.cpp:1320:37
    #34 0x55b67d in main /irods_source/server/main_server/src/rodsServer.cpp:1387:5
    #35 0x7fdc68dfcd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #36 0x7fdc68dfce3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #37 0x473494 in _start (/usr/sbin/irodsServer+0x473494)

Address 0x7fff6b701760 is located in stack of thread T0 at offset 928 in frame
    #0 0x7fdc636f2b3f in nextRuleGenStringExpression(pointer*, ParserContext*, token*) /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1273

  This frame has 5 object(s):
    [32, 48) 'pos' (line 1273)
    [64, 464) 'st' (line 1287)
    [528, 928) 'end' (line 1288) <== Memory access at offset 928 overflows this variable
    [992, 66528) 'sbuf' (line 1309)
    [66784, 66785) 'delim' (line 1310)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1304:14 in nextRuleGenStringExpression(pointer*, ParserContext*, token*)
```

https://github.com/irods/irods/blob/669a726968dcdd7c4dab7d52761095119511c182/plugins/rule_engines/irods_rule_language/src/parser.cpp#L1304

Investigation ongoing...

**Comment by trel** [comment]
love those minus 1s.    go go go.

**Comment by MartinFlores751** [comment]
An initial look at the segfault using gdb showed that we were writing past the end of a buffer in `st`, and this was overwriting `str`. This led to the segfault when accessed:
https://github.com/irods/irods/blob/669a726968dcdd7c4dab7d52761095119511c182/plugins/rule_engines/irods_rule_language/src/parser.cpp#L1286-L1287

gdb view:
```sh
(gdb) bt
#0  0x000072a791a72f4c in nextRuleGenStringExpression (e=0x17c2e70, context=0x1847730, tk=0x184ab78) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1296
#1  0x000072a791a819bf in nextRuleGenPathExpression (e=0x17c2e70, context=0x1847730) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1351
#2  0x000072a791a79d61 in nextRuleGenValue (e=0x17c2e70, context=0x1847730, rulegen=1) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1422
#3  0x000072a791a62283 in nextRuleGenTerm (e=0x17c2e70, context=0x1847730, rulegen=1, prec=0) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1216
#4  0x000072a791a8a5f5 in parseTermRuleGen (expr=0x17c2e70, rulegen=1, pc=0x1847730) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:3386
#5  0x000072a791a95086 in parseAndComputeExpression (expr=0x17a2bf8 "/tempZone/home/rods/foo", env=0x17a2a78, rei=0x7ffc838f8560, reiSaveFlag=0, errmsg=0x7ffc838f6f98, r=0x174c210) at /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:521
#6  0x000072a791a94f08 in parseAndComputeMsParamArrayToEnv (var=0x1790230, env=0x17a2a78, rei=0x7ffc838f8560, reiSaveFlag=0, errmsg=0x7ffc838f6f98, r=0x174c210) at /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:85
#7  0x000072a791a9548e in parseAndComputeRuleAdapter (rule=0x176d890 "@external\n# rule.r\ncheck_access {\n    *access = 0;\n    msiCheckAccess(\"*logical_path\", \"read object\", *access);\n}\n", msParamArray=0x1790230, rei=0x7ffc838f8560, reiSaveFlag=0, r=0x174c210) at /irods_source/plugins/rule_engines/irods_rule_language/src/rules.cpp:119
#8  0x000072a791a4477b in execMyRuleWithSaveFlag (ruleDef=0x176d890 "@external\n# rule.r\ncheck_access {\n    *access = 0;\n    msiCheckAccess(\"*logical_path\", \"read object\", *access);\n}\n", inMsParamArray=0x1790230, outParamsDesc=0x7ffc838f8528 "ruleExecOut", rei=0x7ffc838f8560, reiSaveFlag=0)
      at /irods_source/plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp:316
#9  0x000072a791a44670 in execMyRule (ruleDef=0x176d890 "@external\n# rule.r\ncheck_access {\n    *access = 0;\n    msiCheckAccess(\"*logical_path\", \"read object\", *access);\n}\n", inMsParamArray=0x1790230, outParamsDesc=0x7ffc838f8528 "ruleExecOut", rei=0x7ffc838f8560) at /irods_source/plugins/rule_engines/irods_rule_language/src/nre.reLib1.cpp:243
  <BACKTRACE TRIMMED>
(gdb) info locals
vs = 0
ve = 9
str = 0x9 <error: Cannot access memory at address 0x9>
end = {0 <repeats 100 times>}
noi = 103
rulegen = 0
k = 0
sbuf = '\000' <repeats 16 times>, "\220\nx\001\000\000\000\000\000\000\000\000\377\377\377\377\360\305\215\203\374\177\000\000\060w\204\001\000\000\000\000\220\nx\001\000\000\000\000\260\306\215\203\377\377\377\377\360\306\215\203\374\177\000\000o\255\244\221\247r", '\000' <repeats 34 times>, "\004\000\000\000\004", '\000' <repeats 59 times>, "\230Gv\001\000\000\000\000\230Gv\001
\000\000\000\000\002\000\000\000\001\000\000\000"...
delim = ""
strToken = 0x184ab78
i = 103
startLoc = 0
st = {0, 0, 23, 9 <repeats 97 times>}
startloc = 0
start = {exprloc = 23, base = 0x17a85a0 "s/tempZone/home/rods/foo"}
pos = {exprloc = 0, base = 0x17a85a0 "s/tempZone/home/rods/foo"}
token = 0x0
(gdb) p *strToken
$12 = {type = TK_PATH, text = "/tempZone/home/rods/foo", '\000' <repeats 1000 times>, vars = {0 <repeats 100 times>}, exprloc = 0}
```

A naive solution of capping the `while(...)` loop in the following line:
https://github.com/irods/irods/blob/669a726968dcdd7c4dab7d52761095119511c182/plugins/rule_engines/irods_rule_language/src/parser.cpp#L1292
To `while ( strToken->vars[i] != -1 && noi <= 100 ) {` resulted in execution up to the following line:
https://github.com/irods/irods/blob/669a726968dcdd7c4dab7d52761095119511c182/plugins/rule_engines/irods_rule_language/src/parser.cpp#L1312

Where the following was displayed in gdb:
```sh
(gdb) n

Thread 2.1 "irodsServer" received signal SIGSEGV, Segmentation fault.
__strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:1672
1672    ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strncpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:1672
#1  0x00007a35c3c3b0b3 in nextRuleGenStringExpression (e=0x0, context=0x0, tk=0x0) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1312
#2  0x0000000000000000 in ?? ()
(gdb) up
#1  0x00007a35c3c3b0b3 in nextRuleGenStringExpression (e=0x0, context=0x0, tk=0x0) at /irods_source/plugins/rule_engines/irods_rule_language/src/parser.cpp:1312
1312    strncpy( sbuf, str + st[0], end[0] - st[0] );
(gdb) info locals
str = 0x0
end = {0 <repeats 100 times>}
noi = 0
rulegen = 0
k = 0
sbuf = '\000' <repeats 65535 times>
delim = ""
strToken = 0x0
i = 0
startLoc = 0
st = {0 <repeats 100 times>}
startloc = 0
start = {exprloc = 0, base = 0x0}
pos = {exprloc = 0, base = 0x0}
token = 0x0
```
What this shows is that there was likely garbage data in `end` and `st`, leading to a negative int that is converted to a very large `size_t` for the `strncpy(...)`. Hence, everything is zeroed.

This shows that a naive solution is likely not an option, instead, whatever sets `strToken->vars` to the special `-1` sentinel value is likely the real issue.

---

In a group gdb/rr session this morning, several discoveries were made, following is a short list of what I captured:
- Manually setting `strToken->vars[0] = -1` in gdb allowed for execution without crashing
- `token`, is a function local variable that comes from a macro, it is not a global
- "Successful" executions have a `token->type` of `TK_STRING`, where the unsuccessful executions have `TK_PATH`
- In gdb, successful executions have a `token->text` in gdb ending with `\000`
- Additionally, only the first element in `token->vars` was set to `-1`, the rest of the elements were `0`.
- Wrapping the irule string in quotes allows for successful execution (e.g. `irule ... "'/tempZone/home/rods/foo'"`)

**Comment by korydraughn** [comment]
This isn't a blocker for 4.3.3. Bumping.

**Comment by korydraughn** [comment]
@MartinFlores751 Please move into the 5.1.0 milestone and close if complete.
