### ISSUE TITLE
test_authentication_PAM_with_server_params fails due to unexpected PAM_AUTH_PASSWORD_FAILED from iinit

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7102]
- [x] main
- [x] 4-3-stable

---

I ran into a test failure with `test_authentication_PAM_with_server_params` while working on PREP.
(This test fails regardless of whether or not PREP is configured, so it's not a PREP issue.)

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/542668a2cdd88a0decc7dc3eca75739a).

```
--- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser irodsauthuser rodsuser] --- 
Assert Command: iadmin mkuser irodsauthuser rodsuser
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser irodsauthuser password ;=iamnotasecret] --- 
Assert Command: iadmin moduser irodsauthuser password ;=iamnotasecret
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [imkdir /tempZone/home/irodsauthuser/2023-05-22Z19:03:07--irods-testing-1byta41r] --- 
Assert Command: imkdir /tempZone/home/irodsauthuser/2023-05-22Z19:03:07--irods-testing-1byta41r
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [icd /tempZone/home/irodsauthuser/2023-05-22Z19:03:07--irods-testing-1byta41r] --- 
Assert Command: icd /tempZone/home/irodsauthuser/2023-05-22Z19:03:07--irods-testing-1byta41r
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

running iinit for PAM user [irodsauthuser] [;=iamnotasecret]
 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current PAM password:
    | Error reinstating echo mode.
  stderr:
    | Error occurred while authenticating user [irodsauthuser] [PAM_AUTH_PASSWORD_FAILED: failed to perform request
    | 
    | ] [ec=-993000] failed with error -993000 PAM_AUTH_PASSWORD_FAILED 
Unexpected output on stderr

FAILED TESTING ASSERTION


======================================================================
FAIL: test_authentication_PAM_with_server_params (irods.test.test_auth.Test_Auth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_auth.py", line 171, in test_authentication_PAM_with_server_params
    self.auth_session.assert_icommand('iinit', 'STDOUT_SINGLELINE',
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

**Comment by alanking** [comment]
This test passes consistently for me when I run it in the testing environment. Perhaps there's some difference in the images we are using?

Looks like there may have been some hiccups involving this and other auth tests in the relatively recent past around the `numbits` used when generating the `dhparam`s, between openssl 1.1.0 and 1.1.1. That's the best guess I've got right now. I'll have another look at this later.

**Comment by alanking** [comment]
https://github.com/irods/irods_development_environment/issues/79 will address this in the development environment.
