### ISSUE TITLE
test_authentication_PAM_without_negotiation fails due to unexpected PAM_AUTH_PASSWORD_FAILED from iinit 

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7120]
Probably related: #7102
I ran into a test failure with `test_authentication_PAM_without_negotiation` while working on PREP.
(This test fails regardless of whether or not PREP is installed, so it's not a PREP issue.)

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/81d24be5855776bcbeaf077af24249e6).

```
 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser irodsauthuser rodsuser] --- 
Assert Command: iadmin mkuser irodsauthuser rodsuser
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser irodsauthuser password ;=iamnotasecret] --- 
Assert Command: iadmin moduser irodsauthuser password ;=iamnotasecret
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [imkdir /tempZone/home/irodsauthuser/2023-06-11Z15:50:09--irods-testing-u14zfb04] --- 
Assert Command: imkdir /tempZone/home/irodsauthuser/2023-06-11Z15:50:09--irods-testing-u14zfb04
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [icd /tempZone/home/irodsauthuser/2023-06-11Z15:50:09--irods-testing-u14zfb04] --- 
Assert Command: icd /tempZone/home/irodsauthuser/2023-06-11Z15:50:09--irods-testing-u14zfb04
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [irodsauthuser#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current PAM password:
    | Error reinstating echo mode.
  stderr:
    | Error occurred while authenticating user [irodsauthuser] [PAM_AUTH_PASSWORD_FAILED: failed to perform request
    | 
    | ] [ec=-993000] failed with error -993000 PAM_AUTH_PASSWORD_FAILED 
Unexpected output on stderr

FAILED TESTING ASSERTION


======================================================================
FAIL: test_authentication_PAM_without_negotiation (irods.test.test_auth.Test_Auth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_auth.py", line 83, in test_authentication_PAM_without_negotiation
    self.auth_session.assert_icommand('iinit', 'STDOUT_SINGLELINE',
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

**Comment by alanking** [comment]
This may be failing because there is a precondition required by this test and the one in #7102 which have historically been handled by our automated testing machinery, *not* the test class itself. This is still the case as the preconditoin is now being handled by the testing environment for all test-running containers before the tests are run.

If this was not run in the testing environment, this precondition needs to be met somehow in order for the test to succeed:
https://github.com/irods/irods/blob/8797c1c944175fe28024474b53cdef826672e74b/scripts/irods/test/test_auth.py#L26

We should probably just add a check for the existence of the user and skip the tests if not present. Don't think we can create the user as the iRODS service account, which runs the tests.

Alternatively, we could introduce a "test hook" like we have for the plugins which is usually run as a user with sudo access. This could set up the environment for running the iRODS tests just like the test hooks do for the plugins. I would strongly recommend that we move this out of the 4.3.1 milestone (or maybe even move to 4.4) if we decide to go this route.

**Comment by alanking** [comment]
I reproduced the issue by manually running the test in an ubuntu:22.04 container in the testing environment. I confirmed that irodsauthuser did not exist at the time the test was run. I also confirmed that adding a skip on the test for when the user does not exist appropriately skips the test (or not) if the user cannot (or can) be found via `pwd.getpwnam`.

**Comment by alanking** [comment]
https://github.com/irods/irods_development_environment/issues/79 will address this in the development environment.
