### ISSUE TITLE
test_ifsck__2650 fails due to unexpected UNIX_FILE_GET_FS_FREESPACE_ERR

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7122]
I ran into a test failure with `test_ifsck__2650` while working on PREP.
(This test fails regardless of whether or not PREP is configured, so it's not a PREP issue.)

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/545f87f32407739a469c904617c6ada8).

```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [imkdir /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12] --- 
Assert Command: imkdir /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [ils -L /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt] --- 
Assert Command: ils -L /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt
Expecting STDERR_SINGLELINE: ['does not exist']
  stdout:
    | 
  stderr:
    | remote addresses: 10.200.0.2 ERROR: lsUtil: srcPath /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt does not exist or user lacks access permission
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iput -K /tmp/fsckfile.txt /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt] --- 
Assert Command: iput -K /tmp/fsckfile.txt /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | remote addresses: 10.200.0.2 ERROR: putUtil: put error for /tempZone/home/otherrods/2023-06-11Z16:15:11--irods-testing-hiv73kbs/255_byte_directory_name_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12_abcdefghijklmnopqrstuvwxyz12/fsckfile.txt, status = -526036 status = -526036 UNIX_FILE_GET_FS_FREESPACE_ERR, File name too long
Unexpected output on stderr

FAILED TESTING ASSERTION


======================================================================
FAIL: test_ifsck__2650 (irods.test.test_resource_types.Test_Resource_Unixfilesystem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_resource_types.py", line 593, in test_ifsck__2650
    self.admin.assert_icommand('iput -K ' + filepath + ' ' + full_logical_path)  # iput
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

The error code `UNIX_FILE_GET_FS_FREESPACE_ERR` is used here, but it appears this is not a free space related error.

**Comment by korydraughn** [comment]
Have you seen this happen since it was first reported?

I haven't seen this in any recent test runs on my end.

**Comment by SwooshyCueb** [comment]
No, I haven't run into this again

**Comment by korydraughn** [comment]
Ok. Closing.

If we run into it again, we can reopen this issue or create a new one.
