### ISSUE TITLE
test_irepl_a_updates_stale_zero_byte_replicas__issue_6285 fails when running python suite

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7168]
When running the python test suite for #7159 and irods/irods_rule_engine_plugin_python#157, I ran into a peculiar test failure. I could *only* reproduce the test failure in the original container in which I was running the python test suite. (Note that I am NOT using the testing environment here.)

I could not reproduce the test failure under the following conditions:
- Running the individual test in a fresh container with iRODS built from #7159 and PREP built from  irods/irods_rule_engine_plugin_python#157
- Running the individual test in a fresh container with iRODS built from #7159 and PREP as is currently released
- Running the individual test in a fresh container with iRODS built from #7159 and no PREP installed

This leads me to suspect that one of the tests that ran prior did not tear itself down properly and left the server in a state that resulted in the test failure.

More investigation is required.

I'm opening this issue in the main iRODS repo as I do not currently have reason to believe it's a PREP-related issue.

```
Stdout:
 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser otherrods rodsadmin] --- 
Assert Command: iadmin mkuser otherrods rodsadmin
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser otherrods password rods] --- 
Assert Command: iadmin moduser otherrods password rods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [imkdir /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg] --- 
Assert Command: imkdir /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg] --- 
Assert Command: icd /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin mkuser alice rodsuser] --- 
Assert Command: iadmin mkuser alice rodsuser
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin moduser alice password apass] --- 
Assert Command: iadmin moduser alice password apass
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [imkdir /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_] --- 
Assert Command: imkdir /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_] --- 
Assert Command: icd /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [iadmin mkresc root_a passthru] --- 
Assert Command: iadmin mkresc root_a passthru
Expecting STDOUT: ['root_a']
  stdout:
    | Creating resource:
    | Name:             "root_a"
    | Type:             "passthru"
    | Host:             ""
    | Path:             ""
    | Context:  ""
  stderr:
    | remote addresses: 172.17.0.2 ERROR: rcGeneralAdmin failed with error -806000 CAT_SQL_ERR 
Unexpected output on stderr

FAILED TESTING ASSERTION


 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irm -rf /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg] --- 
Assert Command: irm -rf /tempZone/home/otherrods/2023-07-03Z19:37:30--irods-testing-0ln_lsmg
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [otherrods#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser otherrods] --- 
Assert Command: iadmin rmuser otherrods
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [icd] --- 
Assert Command: icd
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irm -rf /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_] --- 
Assert Command: irm -rf /tempZone/home/alice/2023-07-03Z19:37:31--irods-testing-qxf5q9d_
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [alice#tempZone] [irmtrash] --- 
Assert Command: irmtrash
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found

 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmuser alice] --- 
Assert Command: iadmin rmuser alice
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found


======================================================================
FAIL: test_irepl_a_updates_stale_zero_byte_replicas__issue_6285 (irods.test.test_irepl.Test_Irepl)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_irepl.py", line 178, in test_irepl_a_updates_stale_zero_byte_replicas__issue_6285
    lib.create_passthru_resource(roots[0], self.admin)
  File "/var/lib/irods/scripts/irods/lib.py", line 608, in create_passthru_resource
    user.assert_icommand(['iadmin', 'mkresc', resource_name, 'passthru'], 'STDOUT', [resource_name])
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

**Comment by trel** [comment]
interesting.

`-806000 CAT_SQL_ERR` feels like the database got tired...

not sure how that command would generate bad sql itself...

**Comment by SwooshyCueb** [comment]
was able to reproduce the issue on ubuntu 20.04 when testing irods built against libstdc++.
Ran the python suite, which got all the way to this test before failing.

**Comment by trel** [comment]
So now the question is... what is the bad SQL that's being sent to the database?   Do we have a capture of the server logs?

**Comment by SwooshyCueb** [comment]
I don't have logs captured from any relevant test run currently. Given how long it would take to get them, I've elected to start narrowing down which tests might be responsible.

So far it appears that either `test_delay_queue` and/or `test_icommands_file_operations` contain the misbehaving test(s). Unfortunately, both of these suites fail when cron is disabled, which means that once I do get logs, they will be quite messy.

**Comment by SwooshyCueb** [comment]
Bad news. After multiple attempts, I have been unable to track down an individual test module that is responsible for dirtying up the irods installation in such a way that this test will fail. So far the only way that I have been able to reproduce this failure is by running *every* test module up to `test_irepl`.

I am led to the conclusion that there are *multiple* tests in different modules dirtying up the irods installation, and it is the combination of some or all of these dirty tests that cause this test to fail.

This is going to take much longer to track down.

**Comment by korydraughn** [comment]
Dang.

What depends on this?
Is this a blocker for 4.3.1, libstdc++, or anything else?

**Comment by SwooshyCueb** [comment]
It's not a blocker for anything AFAIK

**Comment by korydraughn** [comment]
Good to know.

**Comment by korydraughn** [comment]
If there's anything you've learned that isn't captured here, but feels important for resolving this issue, please post it.

**Comment by alanking** [comment]
While it is possible that the `CAT_SQL_ERR` is caused by some database failure or environment corruption from a previous test, this error message also comes back whenever you try to create a resource with the same name as an existing resource:
```bash
$ iadmin mkresc ffffff passthru
Creating resource:
Name:           "ffffff"
Type:           "passthru"
Host:           ""
Path:           ""
Context:        ""
$ iadmin mkresc ffffff passthru
Creating resource:
Name:           "ffffff"
Type:           "passthru"
Host:           ""
Path:           ""
Context:        ""
remote addresses: 172.22.0.3 ERROR: rcGeneralAdmin failed with error -806000 CAT_SQL_ERR 
```
Now, I would have expected to get `CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME` or something like that, but that's a different issue. Literally: https://github.com/irods/irods/issues/7440 (I also get a function sequence error)

After a brief search through the repo, the only test with a resource named `root_a` is this one. The cleanup of this resource occurs here:
https://github.com/irods/irods/blob/329c4e364c39a5a112bee1044a1faec8bde36be2/scripts/irods/test/test_irepl.py#L207-L213

`leaf_a` and `leaf_b` are names of resources in other test suites, but the failure shown in the output above is on the creation of `root_a`.

I am going to try running the test suite serially over the weekend and see if I get the same result.

**Comment by trel** [comment]
> only test with a resource named `root_a` is this one

is definitely very confusing.

**Comment by alanking** [comment]
I didn't keep my promise, so I'm *now* running the test suite serially from top to bottom in a single container based off of a build of the branch in https://github.com/irods/irods/pull/7583. I'm using the testing environment because that is what we are using for our releases, but I'm willing to try the "runner" containers in the development environment if that would help.

**Comment by SwooshyCueb** [comment]
> I didn't keep my promise, so I'm _now_ running the test suite serially from top to bottom in a single container based off of a build of the branch in #7583. I'm using the testing environment because that is what we are using for our releases, but I'm willing to try the "runner" containers in the development environment if that would help.

That's what I usually use when running the tests serially.

**Comment by alanking** [comment]
Almost a year later...

Using the same container as described here: https://github.com/irods/irods/issues/7459#issuecomment-2673121770

I started the iRODS server and I tried running the test suite like this as the `irods` service account user:
```
python3 scripts/run_tests.py --run_python_suite
```
I observed two failures:
```
----------------------------------------------------------------------
Ran 2166 tests in 33816.733s

FAILED (failures=2, skipped=134)
<__main__.RegisteredTestResult run=2166 errors=0 failures=2>
```
For some reason, it appears that the same test was logged as failing twice. Here's the first:
```
======================================================================
FAIL: test_icommands_segfault_when_ssl_cert_hostname_not_matching__issue_3609 (irods.test.test_ssl.Test_SSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_ssl.py", line 41, in test_icommands_segfault_when_ssl_cert_hostname_not_matching__issue_3609
    self.admin.assert_icommand(['ils'], 'STDERR', use_regex=True, expected_results='.*-2105000 SSL_CERT_ERROR.*')
  File "/var/lib/irods/scripts/irods/test/session.py", line 162, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 76, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
AssertionError
```
Here's the failed assertion:
```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [ils] --- 
Assert Command: ils 
Expecting STDERR: regex ['.*-2105000 SSL_CERT_ERROR.*']
  stdout:
    | /tempZone/home/otherrods/2025-02-21Z11:03:29--irods-testing-g3s57q8z:
  stderr:
    |   
Output not found

FAILED TESTING ASSERTION
```
... and this one, in the `tearDown`...
```
======================================================================
FAIL: test_icommands_segfault_when_ssl_cert_hostname_not_matching__issue_3609 (irods.test.test_ssl.Test_SSL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_ssl.py", line 24, in tearDown
    super(Test_SSL, self).tearDown()
  File "/var/lib/irods/scripts/irods/test/session.py", line 82, in tearDown
    session.__exit__()
  File "/var/lib/irods/scripts/irods/test/session.py", line 225, in __exit__
    self.assert_icommand(['irm', '-rf', self.session_collection])
  File "/var/lib/irods/scripts/irods/test/session.py", line 162, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 76, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
AssertionError
```
Here's the failed assertion:
```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [irm -rf /tempZone/home/otherrods/2025-02-21Z11:03:29--irods-testing-g3s57q8z] ---
Assert Command: irm -rf /tempZone/home/otherrods/2025-02-21Z11:03:29--irods-testing-g3s57q8z
Expecting EMPTY: ['']
  stdout:
    |
  stderr:
    | remote addresses: 172.17.0.2 ERROR: _rcConnect: connectToRhost error, server on b96d3bcdbaf2:1247 is probably down status = -1824000 CLIENT_NEGOTIATION_ERROR
Unexpected output on stderr
                                                                                                                                                                                                                                                                                
FAILED TESTING ASSERTION
```
I ran the test again in isolation on the same server and it passed:
```
irods.test.test_ssl.Test_SSL.test_icommands_segfault_when_ssl_cert_hostname_not_matching__issue_3609 ... ok

----------------------------------------------------------------------
Ran 1 test in 21.985s

OK
<__main__.RegisteredTestResult run=1 errors=0 failures=0>
```
This is the only test in the suite.

Note: neither of these is `test_irepl_a_updates_stale_zero_byte_replicas__issue_6285`, which of course passed. Due to #8221, I will not be trying this with a debug build. All of these tests pass consistently in the testing environment.

Not sure how to proceed with this issue.

**Comment by alanking** [comment]
Closing this one. Please open a new issue if it crops up again.
