### ISSUE TITLE
Investigate `test_rulebase` failing

### ISSUE THREAD

**Issue by Nishant2022** [irods/irods#7201]
While running the test suite on the tip of main, `test_rulebase` consistently fails.

These are the error message I receive:

```xml
<testcase classname="irods.test.test_rulebase.Test_Remote_Exec" name="test_delay_in_remote_writeline" time="1.508" timestamp="2023-07-19T19:07:30" file="scripts/irods/test/test_rulebase.py" line="1068">
                <error type="FileNotFoundError" message="[Errno 2] No such file or directory: '/var/log/irods/irods.log'"><![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_rulebase.py", line 1088, in test_delay_in_remote_writeline
    initial_log_size = lib.get_file_size_by_path(paths.server_log_path())
  File "/var/lib/irods/scripts/irods/lib.py", line 356, in get_file_size_by_path
    return os.stat(path).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/irods/irods.log'
]]></error>
```

```xml
<testcase classname="irods.test.test_rulebase.Test_Remote_Exec" name="test_remote_in_delay_writeline" time="1.485" timestamp="2023-07-19T19:07:31" file="scripts/irods/test/test_rulebase.py" line="1095">
                <error type="FileNotFoundError" message="[Errno 2] No such file or directory: '/var/log/irods/irods.log'"><![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_rulebase.py", line 1115, in test_remote_in_delay_writeline
    initial_log_size = lib.get_file_size_by_path(paths.server_log_path())
  File "/var/lib/irods/scripts/irods/lib.py", line 356, in get_file_size_by_path
    return os.stat(path).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/irods/irods.log'
]]></error>
```

This appears to be related to https://github.com/irods/irods/issues/7172 as `lib.get_file_size_by_path` is failing.

**Comment by alanking** [comment]
For posterity, what OS was running the test? If in a container, what is the host OS? Thanks

**Comment by Nishant2022** [comment]
This error was generated in a ubuntu 20.04 container with a postgres 10.12 catalog and on a RHEL 9 Machine.

I also experience errors with the test on a ubuntu 20.04 container with a postgres 10.12 catalog on a Ubuntu 22.04 Machine.

**Comment by korydraughn** [comment]
At this point, we're confident this is likely due to the hardware. The test passes consistently on a large enough computer.

Closing.
