### ISSUE TITLE
Has GenQuery of data objects changed between 4.3.0 and 4.3.1 ?

### ISSUE THREAD

**Issue by kjsanger** [irods/irods#7369]
### iRODS Version, OS and Version

Ubuntu 22.04, 4-3-stable

### What did you try to do?

Run a simple metadata query equivalent to `imeta qu -d foo = bar` or
`imeta qu -C foo = bar` using the GenQuery C API (using this client
https://github.com/wtsi-npg/baton)

### Expected behavior

For the query to run without error on both collections and data objects,
returning the single path that has been annotated with metadata foo = bar.

### Observed behavior (including steps to reproduce, if applicable)

I see the expected behaviour for collections, but for data objects I see
a `CAT_SQL_ERR` and the server side logging shows a query generated for
data objects that is missing both column and table:

```
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"bindVar[1]=foo","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.506Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"bindVar[2]=bar","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"cllExecSqlWithResult: SQLExecDirect error: -1, sql:select distinct  from  where r_data_meta_main.meta_attr_name = ?  AND r_data_meta_main.meta_attr_value = ? ","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"SQLSTATE: 42601","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"SQLCODE: 1","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"SQL Error message: ERROR: syntax error at or near \"from\";\nError while executing the query","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"chlGenQuery cmlGetFirstRowFromSql failure -806000","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"_rsGenQuery: genQuery status = -806000","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
Oct  6 12:14:27 d9325b7b87ae irodsServer[21669]: {"log_category":"legacy","log_level":"info","log_message":"rsGenQuery: _rsGenQuery failed, status = -806000","request_api_name":"GEN_QUERY_AN","request_api_number":702,"request_api_version":"d","request_client_user":"irods","request_host":"172.20.0.3","request_proxy_user":"irods","request_release_version":"rods4.3.0","server_host":"d9325b7b87ae","server_pid":21669,"server_timestamp":"2023-10-06T12:14:27.507Z","server_type":"agent","server_zone":"testZone"}
```

According to the logs, the SQL generated is `select distinct  from  where r_data_meta_main.meta_attr_name = ?  AND r_data_meta_main.meta_attr_value = ?`

The client code has worked on every version of iRODS since 4.0.x (and before that even) and also worked on 4.3.0 (after patching the bug fixed by f01cb5f9de7a17a4e24ee10941bd8c36bd9e26bf)

I realise that I'm testing an unreleased code branch, but I thought that with the release being tagged it's better to test before, rather than after release.

Has there been an intentional change to the API? If so can you point me to a some information on what client-side changes we need to make?

**Comment by trel** [comment]
I see...

```
select distinct  from  where r_data_meta_main.meta_attr_name = ?  AND r_data_meta_main.meta_attr_value = ?
```

which is definitely missing the column(s) and table(s) information.

Will investigate.

**Comment by trel** [comment]
> equivalent to imeta qu -d foo = bar 

Does `imeta qu -d foo = bar` itself work without issue?

On 4.3.0 locally...
```
$ imeta add -d file2 foo bar yeps
$ imeta qu -d foo = bar
collection: /tempZone/home/rods
dataObj: file2
```

Which baton command are you issuing?

**Comment by kjsanger** [comment]
I find that the icommands work correctly.

For collections, with the expected result:
```
jq -n '{avus: [{a: "foo", v: "bar"}]}' | ./src/baton-metaquery --coll --debug
2023-10-06T12:42:03Z DEBUG Work to do, lock obtained
2023-10-06T12:42:03Z NOTICE Opening a new iRODS connection
2023-10-06T12:42:03Z DEBUG Metadata query in zone '(null)'
2023-10-06T12:42:03Z DEBUG Searching for collections ...
2023-10-06T12:42:03Z DEBUG Preparing a query to select 1 columns
2023-10-06T12:42:03Z DEBUG Preparing AVU search a: 'foo' v: 'bar', op: '='
2023-10-06T12:42:03Z DEBUG Adding condition 1 of 2: META_COLL_ATTR_NAME = foo
2023-10-06T12:42:03Z DEBUG Made string 0 of 2: op: = value: foo, len 3, total len 8 [= 'foo']
2023-10-06T12:42:03Z DEBUG Adding condition 1 of 2: META_COLL_ATTR_VALUE = bar
2023-10-06T12:42:03Z DEBUG Made string 1 of 2: op: = value: bar, len 3, total len 8 [= 'bar']
2023-10-06T12:42:03Z DEBUG Running query ...
2023-10-06T12:42:03Z DEBUG Attempting to get chunk 0 of query
2023-10-06T12:42:03Z DEBUG Successfully fetched chunk 0 of query
2023-10-06T12:42:03Z DEBUG Converting 1 rows of results to JSON
2023-10-06T12:42:03Z DEBUG Converting row 0 of 1 to JSON
2023-10-06T12:42:03Z DEBUG Encoding column 0 'collection' value '/testZone/home/irods' as JSON
2023-10-06T12:42:03Z DEBUG Obtained a total of 1 JSON results in 1 chunks
2023-10-06T12:42:03Z DEBUG Work done, lock released
[{"collection": "/testZone/home/irods"}]
2023-10-06T12:42:03Z NOTICE Closed the connection on exit
2023-10-06T12:42:03Z DEBUG Processed 1 items with 0 errors
```

For data objects:

```
jq -n '{avus: [{a: "foo", v: "bar"}]}' | ./src/baton-metaquery --obj --d
ebug
2023-10-06T12:42:59Z DEBUG Work to do, lock obtained
2023-10-06T12:42:59Z NOTICE Opening a new iRODS connection
2023-10-06T12:42:59Z DEBUG Metadata query in zone '(null)'
2023-10-06T12:42:59Z DEBUG Searching for data objects ...
2023-10-06T12:42:59Z DEBUG Preparing a query to select 0 columns
2023-10-06T12:42:59Z DEBUG Preparing AVU search a: 'foo' v: 'bar', op: '='
2023-10-06T12:42:59Z DEBUG Adding condition 1 of 2: META_DATA_ATTR_NAME = foo
2023-10-06T12:42:59Z DEBUG Made string 0 of 2: op: = value: foo, len 3, total len 8 [= 'foo']
2023-10-06T12:42:59Z DEBUG Adding condition 1 of 2: META_DATA_ATTR_VALUE = bar
2023-10-06T12:42:59Z DEBUG Made string 1 of 2: op: = value: bar, len 3, total len 8 [= 'bar']
2023-10-06T12:42:59Z DEBUG Running query ...
2023-10-06T12:42:59Z DEBUG Attempting to get chunk 0 of query
2023-10-06T12:42:59Z ERROR Failed to fetch query result: in chunk 0 error -806000 CAT_SQL_ERR
2023-10-06T12:42:59Z ERROR Failed to fetch query result: in chunk 0 error -806000 CAT_SQL_ERR
2023-10-06T12:42:59Z DEBUG Work done, lock released
{"avus": [{"a": "foo", "v": "bar"}], "error": {"message": "Failed to fetch query result: in chunk 0 error -806000 CAT_SQL_ERR", "code": -806000}}
2023-10-06T12:42:59Z NOTICE Closed the connection on exit
2023-10-06T12:42:59Z WARN Processed 1 items with 1 errors
```

**Comment by kjsanger** [comment]
Thanks for spotting! I'll find out why that's (not) getting set.

**Comment by kjsanger** [comment]
Well, this is an interesting bug. The value that was `0` is `obj_format.num_columns` which should be set to either 3 (if getting an object's data size in addition to its collection and name), or should be set to 2 (if just getting the object's collection and name).

There's a branch to do one or the other, depending if the user has set
PRINT_SIZE (which is not the case in this test). So the second branch should be taken. Yet `num_columns` is `0` immediately after the if-else.

However, adding the useless `logmsg(DEBUG, "Hello");` log statement means the
second branch is executed and `num_columns` is `2` as expected.

```
   query_format_in_t *obj_format;
    if (flags & PRINT_SIZE) {
        obj_format = &(query_format_in_t)
            { .num_columns = 3,
              .columns     = { COL_COLL_NAME, COL_DATA_NAME, COL_DATA_SIZE },
              .labels      = { JSON_COLLECTION_KEY, JSON_DATA_OBJECT_KEY,
                               JSON_SIZE_KEY },
              .good_repl   = 1 };
    }
    else {
        obj_format = &(query_format_in_t)
            { .num_columns = 2,
              .columns     = { COL_COLL_NAME, COL_DATA_NAME },
              .labels      = { JSON_COLLECTION_KEY, JSON_DATA_OBJECT_KEY },
              .good_repl   = 0 };
        logmsg(DEBUG, "Hello");
    }
```

**Comment by kjsanger** [comment]
The fact that this correlates with a change from 4.3.0 to 4.3.1 I suspect is circumstantial - the other thing that has changed is the OS version and therefore compiler.

**Comment by trel** [comment]
So I do not understand *how* you have a zero...   is it an initialization UB thing you've hit?

And yes, feels like an updated compiler tightening the reins.

**Comment by korydraughn** [comment]
Perhaps you're running into a lifetime issue?

The anonymous struct you created within the if-ladder will not exist outside of it. Try compiling with address sanitizer or running your program against valgrind.

See this godbolt example for what I'm referring to.

https://gcc.godbolt.org/z/vsMGGn8jc

**Comment by korydraughn** [comment]
You can also allocate the `query_format_in_t` struct on the stack or heap to get around the lifetime issue.

**Comment by kjsanger** [comment]
FWIW, no errors from `-fsanitize=address` (already using `-Wall -Werror -Wextra -pedantic`).

**Comment by kjsanger** [comment]
```
 ./src/baton-metaquery -f test.json 
=================================================================
==17637==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd30044014 at pc 0x7f08fe73b5dd bp 0x7ffd300427d0 sp 0x7ffd300427c0
READ of size 4 at 0x7ffd30044014 thread T0
    #0 0x7f08fe73b5dc in do_search /workspaces/baton/src/json_query.c:264
    #1 0x7f08fe7324b9 in search_metadata /workspaces/baton/src/baton.c:529
    #2 0x7f08fe74245e in iterate_json /workspaces/baton/src/operations.c:123
    #3 0x7f08fe74245e in do_operation /workspaces/baton/src/operations.c:206
    #4 0x55d82141e85b in main /workspaces/baton/src/baton-metaquery.c:199
    #5 0x7f08fd8f7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #6 0x7f08fd8f7e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #7 0x55d82141ea14 in _start (/workspaces/baton/src/.libs/baton-metaquery+0x2a14)

Address 0x7ffd30044014 is located in stack of thread T0 at offset 3412 in frame
    #0 0x7f08fe731c9f in search_metadata /workspaces/baton/src/baton.c:464

  This frame has 3 object(s):
    [48, 1600) '<unknown>'
    [1728, 3280) '<unknown>'
    [3408, 4960) '<unknown>' <== Memory access at offset 3412 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /workspaces/baton/src/json_query.c:264 in do_search
Shadow bytes around the buggy address:
  0x1000260007b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260007c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260007d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260007e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000260007f0: 00 00 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2 f2
=>0x100026000800: f2 f2[f8]f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100026000810: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100026000820: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100026000830: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100026000840: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100026000850: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==17637==ABORTING
```

**Comment by trel** [comment]
stack-use-after-scope!
