### ISSUE TITLE
iRODS 4.3.1 fails to start after upgrade because of missing required parameter in service account environment

### ISSUE THREAD

**Issue by cookie33** [irods/irods#7392]
- [x] irods_docs
- [x] Confirm upgrades from iRODS 4.2.x to 4.3.3 do not run into the schema validation issue (it does, but situationally - https://github.com/irods/irods/issues/7392#issuecomment-2669579446)

---

### iRODS Version, OS and Version

iRODS 4.3.1
CentOS Linux release 7.9.2009 (Core)

### What did you try to do?

Upgrade iRODS from 4.3.0 to 4.3.1

### Expected behavior

iRODS starts after upgrade

### Observed behavior (including steps to reproduce, if applicable)

iRODS does not start after upgrade. It complains about a missing required variable `irods_connection_pool_refresh_time_in_seconds` in ~/.irods/irods_environment.json.

Following is output of `/var/lib/irods/log/control_log.txt`:
```
...
2023-10-24T12:43:14.780Z -   DEBUG -             json_validation.py:  59 - {'$id': 'file:///var/lib/irods/configuration_schemas/v4/service_account_environment.json',
 '$schema': 'https://json-schema.org/draft/2020-12/schema',
 'allOf': [{'$ref': 'client_environment.json'}],
 'properties': {'irods_authentication_file': {'type': 'string'},
                'irods_authentication_scheme': {'type': 'string'},
                'irods_client_server_negotiation': {'enum': ['request_server_negotiation',
                                                             'off']},
                'irods_client_server_policy': {'enum': ['CS_NEG_REFUSE',
                                                        'CS_NEG_REQUIRE',
                                                        'CS_NEG_DONT_CARE']},
                'irods_connection_pool_refresh_time_in_seconds': {'type': 'integer'},
                'irods_cwd': {'type': 'string'},
                'irods_debug': {'type': 'string'},
                'irods_default_hash_scheme': {'type': 'string'},
                'irods_default_number_of_transfer_threads': {'type': 'integer'},
                'irods_default_resource': {'type': 'string'},
                'irods_encryption_algorithm': {'type': 'string'},
                'irods_encryption_key_size': {'type': 'integer'},
                'irods_encryption_num_hash_rounds': {'type': 'integer'},
                'irods_encryption_salt_size': {'type': 'integer'},
                'irods_gsi_server_dn': {'type': 'string'},
                'irods_home': {'type': 'string'},
                'irods_log_level': {'type': 'integer'},
                'irods_match_hash_policy': {'type': 'string'},
                'irods_maximum_size_for_single_buffer_in_megabytes': {'type': 'integer'},
                'irods_plugins_home': {'type': 'string'},
                'irods_server_control_plane_encryption_algorithm': {'type': 'string'},
                'irods_server_control_plane_encryption_num_hash_rounds': {'type': 'integer'},
                'irods_server_control_plane_key': {'type': 'string'},
                'irods_server_control_plane_port': {'type': 'integer'},
                'irods_ssl_ca_certificate_file': {'type': 'string'},
                'irods_ssl_ca_certificate_path': {'type': 'string'},
                'irods_ssl_certificate_chain_file': {'type': 'string'},
                'irods_ssl_certificate_key_file': {'type': 'string'},
                'irods_ssl_dh_params_file': {'type': 'string'},
                'irods_ssl_verify_server': {'enum': ['cert',
                                                     'hostname',
                                                     'none']},
                'irods_tcp_keepalive_intvl_in_seconds': {'type': 'integer'},
                'irods_tcp_keepalive_probes': {'type': 'integer'},
                'irods_tcp_keepalive_time_in_seconds': {'type': 'integer'},
                'irods_transfer_buffer_size_for_parallel_transfer_in_megabytes': {'type': 'integer'},
                'schema_name': {'type': 'string'},
                'schema_version': {'type': 'string'}},
 'required': ['irods_client_server_negotiation',
              'irods_client_server_policy',
              'irods_connection_pool_refresh_time_in_seconds',
              'irods_cwd',
              'irods_default_hash_scheme',
              'irods_default_number_of_transfer_threads',
              'irods_default_resource',
              'irods_encryption_algorithm',
              'irods_encryption_key_size',
              'irods_encryption_num_hash_rounds',
              'irods_encryption_salt_size',
              'irods_home',
              'irods_match_hash_policy',
              'irods_maximum_size_for_single_buffer_in_megabytes',
              'irods_server_control_plane_encryption_algorithm',
              'irods_server_control_plane_encryption_num_hash_rounds',
              'irods_server_control_plane_key',
              'irods_server_control_plane_port',
              'irods_transfer_buffer_size_for_parallel_transfer_in_megabytes',
              'schema_name',
              'schema_version'],
 'type': 'object'}
2023-10-24T12:43:14.793Z -   ERROR -               irods_control.py: 127 - Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/json_validation.py", line 60, in validate_dict
    jsonschema.validate(config_dict, schema, resolver=jsonschema.RefResolver(schema_uri, schema))
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: 'irods_connection_pool_refresh_time_in_seconds' is a required property

Failed validating 'required' in schema:
    {'$id': 'file:///var/lib/irods/configuration_schemas/v4/service_account_environment.json',
     '$schema': 'https://json-schema.org/draft/2020-12/schema',
     'allOf': [{'$ref': 'client_environment.json'}],
     'properties': {'irods_authentication_file': {'type': 'string'},
                    'irods_authentication_scheme': {'type': 'string'},
                    'irods_client_server_negotiation': {'enum': ['request_server_negotiation',
                                                                 'off']},
                    'irods_client_server_policy': {'enum': ['CS_NEG_REFUSE',
                                                            'CS_NEG_REQUIRE',
                                                            'CS_NEG_DONT_CARE']},
                    'irods_connection_pool_refresh_time_in_seconds': {'type': 'integer'},
                    'irods_cwd': {'type': 'string'},
                    'irods_debug': {'type': 'string'},
                    'irods_default_hash_scheme': {'type': 'string'},
                    'irods_default_number_of_transfer_threads': {'type': 'integer'},
                    'irods_default_resource': {'type': 'string'},
                    'irods_encryption_algorithm': {'type': 'string'},
                    'irods_encryption_key_size': {'type': 'integer'},
                    'irods_encryption_num_hash_rounds': {'type': 'integer'},
                    'irods_encryption_salt_size': {'type': 'integer'},
                    'irods_gsi_server_dn': {'type': 'string'},
                    'irods_home': {'type': 'string'},
                    'irods_log_level': {'type': 'integer'},
                    'irods_match_hash_policy': {'type': 'string'},
                    'irods_maximum_size_for_single_buffer_in_megabytes': {'type': 'integer'},
                    'irods_plugins_home': {'type': 'string'},
                    'irods_server_control_plane_encryption_algorithm': {'type': 'string'},
                    'irods_server_control_plane_encryption_num_hash_rounds': {'type': 'integer'},
                    'irods_server_control_plane_key': {'type': 'string'},
                    'irods_server_control_plane_port': {'type': 'integer'},
                    'irods_ssl_ca_certificate_file': {'type': 'string'},
                    'irods_ssl_ca_certificate_path': {'type': 'string'},
                    'irods_ssl_certificate_chain_file': {'type': 'string'},
                    'irods_ssl_certificate_key_file': {'type': 'string'},
                    'irods_ssl_dh_params_file': {'type': 'string'},
                    'irods_ssl_verify_server': {'enum': ['cert',
                                                         'hostname',
                                                         'none']},
                    'irods_tcp_keepalive_intvl_in_seconds': {'type': 'integer'},
                    'irods_tcp_keepalive_probes': {'type': 'integer'},
                    'irods_tcp_keepalive_time_in_seconds': {'type': 'integer'},
                    'irods_transfer_buffer_size_for_parallel_transfer_in_megabytes': {'type': 'integer'},
                    'schema_name': {'type': 'string'},
                    'schema_version': {'type': 'string'}},
     'required': ['irods_client_server_negotiation',
                  'irods_client_server_policy',
                  'irods_connection_pool_refresh_time_in_seconds',
                  'irods_cwd',
                  'irods_default_hash_scheme',
                  'irods_default_number_of_transfer_threads',
                  'irods_default_resource',
                  'irods_encryption_algorithm',
                  'irods_encryption_key_size',
                  'irods_encryption_num_hash_rounds',
                  'irods_encryption_salt_size',
                  'irods_home',
                  'irods_match_hash_policy',
                  'irods_maximum_size_for_single_buffer_in_megabytes',
                  'irods_server_control_plane_encryption_algorithm',
                  'irods_server_control_plane_encryption_num_hash_rounds',
                  'irods_server_control_plane_key',
                  'irods_server_control_plane_port',
                  'irods_transfer_buffer_size_for_parallel_transfer_in_megabytes',
                  'schema_name',
                  'schema_version'],
     'type': 'object'}
...
```
The documentation states that the parameter `irods_connection_pool_refresh_time_in_seconds` is an optional parameter. But it is not.

And it is also not mentioned in the upgrade actions.

**Comment by trel** [comment]
Oh!   Drat.

So we need to

- make sure our upgrade logic injects the default value of `300`.


- remove the '(Optional)' from 
https://github.com/irods/irods_docs/blob/361894ef2a3740b867c012c6f2d3b1c701f07c2f/docs/system_overview/configuration.md?plain=1#L510

**Comment by korydraughn** [comment]
Does anything actually use that property?

A quick grep points to it not being used by the server at all.

**Comment by trel** [comment]
Perhaps.

Here, we say it is part of the 'minimum settings':

https://github.com/irods/irods_docs/blob/361894ef2a3740b867c012c6f2d3b1c701f07c2f/docs/system_overview/configuration.md?plain=1#L729-L735

So we have some inconsistency to clean up, regardless.

**Comment by trel** [comment]
Used here...

https://github.com/search?q=repo%3Airods%2Firods%20irodsConnectionPoolRefreshTime&type=code

**Comment by korydraughn** [comment]
Ah that's probably why it looks like it isn't used. Using more `grep -C` would've helped with that.

However, `iinit` doesn't set that property and the icommands work without any issues.

This feels like a documentation/schema issue.

**Comment by cookie33** [comment]
For normal users it does not have to be set. It only seems to be reuired for the service account environment
That is what it is complaining about.

**Comment by korydraughn** [comment]
From https://github.com/irods/irods/pull/8209#discussion_r1962019250.

> After some discussion, we've agreed to do the following:
> - Remove "(Optional)" from the configs in irods/irods_docs
> - Confirm upgrades from iRODS 4.2.x to 4.3.3 do not run into the schema validation issue
> 
> We are not going to bump the schema version for 4.3 (remains at v4). We expect iRODS 5 to ship > with a schema version of v5.

**Comment by MartinFlores751** [comment]
Here are some ways to reproduce the issue:

This issue is likely to come up when upgrading from an iRODS version less than 4.2.5, to 4.3.1 and greater. This is because `irods_connection_pool_refresh_time_in_seconds` is not defined in the default configuration before version 4.2.5.

As another example for how this issue may come up, consider the following:

Since `irods_connection_pool_refresh_time_in_seconds` was optional before 4.3.1, it could be removed from the configuration without causing any issues prior to 4.3.1 (e.g. creating a minimal configuration). Then, when performing the upgrade, the "minimal configuration" would cause this issue to show up.

**Comment by alanking** [comment]
I made a checkbox for confirming the upgrade issue and one for the docs. The docs one has been checked.

**Comment by MartinFlores751** [comment]
For the upgrade check box, see this comment: https://github.com/irods/irods/issues/7392#issuecomment-2669579446

The issue can show up in two cases, starting from a server before 4.2.5, and manually removing the option itself before upgrading to 4.3.1 or greater.

**Comment by alanking** [comment]
Got it, thanks. Checked box with link to comment. Please close if complete.
