### ISSUE TITLE
iRODS warning on startup

### ISSUE THREAD

**Issue by chip-aws** [irods/irods#7414]
### iRODS Version, OS and Version
iRODS Version 4.3.1 , Red Hat Enterprise Linux Server release 7.9 (Maipo),

Hello,

When we start iRODS, we get the warning messages shown below.  The startup script appears to be bypassing validation of the following files: /etc/irods/server_config.json, /var/lib/irods/version.json,
and /var/lib/irods/.irods/irods_environment.json, although all of these files exist.  Should this be a cause of concern and will it affect the operation of iRODS?  The iRODS service does appear to start up successfully.

Thanks,
Doug White
School of Information and Library Science
UNC Chapel Hill

[root@diamond log]# systemctl status irods
● irods.service - LSB: Manages the iRODS service
   Loaded: loaded (/etc/rc.d/init.d/irods; bad; vendor preset: disabled)
   Active: active (exited) since Wed 2023-11-08 11:23:32 EST; 15min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 29265 ExecStop=/etc/rc.d/init.d/irods stop (code=exited, status=0/SUCCESS)
  Process: 29296 ExecStart=/etc/rc.d/init.d/irods start (code=exited, status=0/SUCCESS)

Nov 08 11:23:31 servername.com irods[29296]: Traceback (most recent call last):
Nov 08 11:23:31 servername.com irods[29296]: File "/var/lib/irods/scripts/irods/controller.py", line 69, in start
Nov 08 11:23:31 servername.com irods[29296]: self.config.validate_configuration()
Nov 08 11:23:31 servername.com irods[29296]: File "/var/lib/irods/scripts/irods/configuration.py", line 296, in validate_configuration
Nov 08 11:23:31 servername.com irods[29296]: lib.indent(*skipped)))
Nov 08 11:23:31 servername.com irods[29296]: irods.exceptions.IrodsWarning: Skipped validation for the following files:
Nov 08 11:23:31 servername.com irods[29296]: /etc/irods/server_config.json
Nov 08 11:23:31 servername.com irods[29296]: /var/lib/irods/version.json
Nov 08 11:23:31 servername.com irods[29296]: /var/lib/irods/.irods/irods_environment.json
Nov 08 11:23:32 servername.com systemd[1]: Started LSB: Manages the iRODS service.

**Comment by korydraughn** [comment]
Try checking `/var/lib/irods/log/control_log.txt`. That log file should contain the reason behind the schema validation issue.

**Comment by chip-aws** [comment]
Thanks.  I checked that log earlier, but it wasn't obvious to me what the error was. All of the files exist, but possibly there is an error in the format of those configuration files I mentioned above? From what I can tell, the most important warning in /var/lib/irods/log/control_log.txt appears to be this:                                                                                                                                                 
File "/var/lib/irods/scripts/irods/controller.py", line 69, in start
self.config.validate_configuration()
File "/var/lib/irods/scripts/irods/configuration.py", line 296, in validate_configuration
lib.indent(*skipped))) irods.exceptions.IrodsWarning: Skipped validation for the following files:
/etc/irods/server_config.json /var/lib/irods/version.json
/var/lib/irods/.irods/irods_environment.json
irods.exceptions.IrodsWarning: WARNING: Validation Failed for [/var/lib/irods/version.json]:
       against [https://schemas.irods.org/configuration/v4/version.json]
      JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-11-07T22:20:33.663Z -  DEBUG -              configuration.py: 281 - Attempting to validate /var/lib/irods/.irods/irods_environment.json against https://schemas.irods.org/configuration/v4/service_account_environment.json
2023-11-07T22:20:33.663Z -  DEBUG -            json_validation.py:  85 - Loading schema from https://schemas.irods.org/configuration/v4/service_account_environment.json
2023-11-07T22:20:33.663Z -  DEBUG -            json_validation.py:  87 - Parsed URL: https://schemas.irods.org/configuration/v4/service_account_environment.json
2023-11-07T22:20:33.664Z -  DEBUG -             connectionpool.py: 959 - Starting new HTTPS connection (1): schemas.irods.org:443
2023-11-07T22:20:33.700Z -  DEBUG -             connectionpool.py: 437 - [https://schemas.irods.org:443](https://schemas.irods.org/) "GET /configuration/v4/service_account_environment.json HTTP/1.1" 404 247
2023-11-07T22:20:33.701Z - WARNING -               configuration.py: 288 - WARNING: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]:
       against [https://schemas.irods.org/configuration/v4/service_account_environment.json]
      JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by korydraughn** [comment]
Wait, it's reaching out to an unknown location on the internet. The URLs in that output do not exist.

What value do you have for `"schema_validation_base_uri"` in server_config.json?

**Comment by chip-aws** [comment]
I just noticed that - https://schemas.irods.org/configuration/v4/service_account_environment.json  is not available.

**Comment by korydraughn** [comment]
Try setting that to `"file:///var/lib/irods/configuration_schemas"`.

**Comment by chip-aws** [comment]
That path does exist on the system and is owned by the iRODS user, but iRODS won't start with that setting. 

 irods.service - LSB: Manages the iRODS service
   Loaded: loaded (/etc/rc.d/init.d/irods; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2023-11-08 12:59:43 EST; 1min 25s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 8060 ExecStop=/etc/rc.d/init.d/irods stop (code=exited, status=0/SUCCESS)
  Process: 8615 ExecStart=/etc/rc.d/init.d/irods start (code=exited, status=1/FAILURE)

Nov 08 12:59:43 server.com server_control_plane_port': 1248,
Nov 08 12:59:43 server.com irods[8615]: 'irods_transfer_buffer_size_for_parallel_transfer_in_megabytes': 4,
Nov 08 12:59:43 server.com irods[8615]: 'irods_user_name': 'redacted',
Nov 08 12:59:43 server.com irods[8615]: 'irods_zone_name': 'redacted',
Nov 08 12:59:43 server.com irods[8615]: 'schema_name': 'service_account_environment',
Nov 08 12:59:43 server.com irods[8615]: 'schema_version': 'v4'}
Nov 08 12:59:43 server.com systemd[1]: irods.service: control process exited, code=exited status=1
Nov 08 12:59:43 server.com systemd[1]: Failed to start LSB: Manages the iRODS service.
Nov 08 12:59:43 server.com systemd[1]: Unit irods.service entered failed state.
Nov 08 12:59:43 server.com systemd[1]: irods.service failed.

**Comment by korydraughn** [comment]
The control_log.txt log file should contain the reason.

**Comment by chip-aws** [comment]
This seems to work - "https://github.com/irods/irods_schema_configuration", but I'll take a look at the control_log.txt file with the other settings since I assume "file:///var/lib/irods/configuration_schemas" is going to be used in the future.

**Comment by korydraughn** [comment]
That URL points to an obsolete version of the schema files. You shouldn't use that.

The file path I provided points to files shipped with your iRODS server. They represent the latest version of the schema files for your deployment. Please use that path.

**Comment by chip-aws** [comment]
Sure.  Using  "file:///var/lib/irods/configuration_schemas", the first two file validations are successful but on the irods_environment.json validation, this error occurs:  rods.exceptions.IrodsError: ERROR: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/service_account_environment.json]
        ValidationError: 'irods_connection_pool_refresh_time_in_seconds' is a required property,   so I guess that value needs to be specified.

**Comment by korydraughn** [comment]
That's correct. The default value for that is 300.

**Comment by korydraughn** [comment]
That makes this issue a duplicate of #7392.

Once you add that, startup should be clean.

**Comment by chip-aws** [comment]
Great.  All is working now with no warning messages on startup.  Thanks!

**Comment by korydraughn** [comment]
Excellent.

Closing as duplicate.

**Comment by korydraughn** [comment]
Then again, let's keep this open until the work is actually resolved.

**Comment by MartinFlores751** [comment]
Work is resolved is #7392, closing.
