### ISSUE TITLE
Cannot create collection if parent collection contains the same named data object

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods#7419]
### iRODS Version, OS and Version
iRODS 4.3.1, almalinux8

### What did you try to do?
Wanted to create a collection with the same data object name.

### Expected behavior
I expected to see the collection I wanted to create is made without any error.

### Observed behavior (including steps to reproduce, if applicable)
Collection create operation fails with some errors both in the client and in logs.

iCommands:
```
[irods@dev-u0137480 irods]$ itouch test
[irods@dev-u0137480 irods]$ ils
/u0137480/home/rods:
  test
[irods@dev-u0137480 irods]$ imkdir test
remote addresses: 10.0.2.100 ERROR: mkdirUtil: mkColl of /u0137480/home/rods/test error. status = -834000 CAT_NAME_EXISTS_AS_DATAOBJ
```
No error in logs.

prc:
```
>>> with iRODSSession(irods_env_file=env_file) as session:
...     session.collections.create("/u0137480/home/rods/test")
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 45, in create
    response = conn.recv()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 132, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.CAT_NAME_EXISTS_AS_DATAOBJ: None
```
Logs
```
irods stdout | {"log_category":"legacy","log_level":"error","log_message":"rsMkCollR: rsCollCreate failed for /u0137480/home/rods/test, status =-834000","request_api_name":"COLL_CREATE_AN","request_api_number":681,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":76696,"server_timestamp":"2023-11-15T08:39:57.288Z","server_type":"agent","server_zone":"u0137480"}
irods stdout | {"log_category":"rule_engine","log_level":"error","log_message":"caught python exception","python_exception":"Traceback (most recent call last):\n  File \"<string>\", line 11, in main\n  File \"/usr/local/lib/python3.6/site-packages/irods/manager/collection_manager.py\", line 45, in create\n    response = conn.recv()\n  File \"/usr/local/lib/python3.6/site-packages/irods/connection.py\", line 132, in recv\n    raise get_exception_by_code(msg.int_info, err_msg)\nirods.exception.CAT_NAME_EXISTS_AS_DATAOBJ: None\n","request_api_name":"EXEC_MY_RULE_AN","request_api_number":625,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","rule_engine_plugin":"python","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":76690,"server_timestamp":"2023-11-15T08:39:57.290Z","server_type":"agent","server_zone":"u0137480"}
irods stdout | {"log_category":"api","log_level":"error","log_message":"rsExecMyRule: -1828000, [-]\t/irods_plugin_source/src/main.cpp:782:irods::error exec_rule_text(const irods::default_re_ctx &, const std::string &, msParamArray_t *, const std::string &, irods::callback) :  status [RULE_ENGINE_ERROR]  errno [] -- message [irods_rule_engine_plugin_python::irods::error exec_rule_text(const irods::default_re_ctx &, const std::string &, msParamArray_t *, const std::string &, irods::callback) Caught Python exception.\nTraceback (most recent call last):\n  File \"<string>\", line 11, in main\n  File \"/usr/local/lib/python3.6/site-packages/irods/manager/collection_manager.py\", line 45, in create\n    response = conn.recv()\n  File \"/usr/local/lib/python3.6/site-packages/irods/connection.py\", line 132, in recv\n    raise get_exception_by_code(msg.int_info, err_msg)\nirods.exception.CAT_NAME_EXISTS_AS_DATAOBJ: None\n]\n\n","request_api_name":"EXEC_MY_RULE_AN","request_api_number":625,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":76690,"server_timestamp":"2023-11-15T08:39:57.290Z","server_type":"agent","server_zone":"u0137480"}
irods stdout | {"log_category":"legacy","log_level":"error","log_message":"rsMkCollR: rsCollCreate failed for /u0137480/home/rods/test, status =-834000","request_api_name":"COLL_CREATE_AN","request_api_number":681,"request_api_version":"d","request_client_user":"rods","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":77700,"server_timestamp":"2023-11-15T08:50:41.104Z","server_type":"agent","server_zone":"u0137480"}

```

It looks like the underlying reason for this issue might be either the same with [this ](https://github.com/irods/irods/issues/6510 ) one or separate but a similar issue.

**Comment by trel** [comment]
> I believe things are working as intended.

Agreed.

**Comment by mstfdkmn** [comment]
Indeed that looks like the same behavior of linux too. Thanks.

**Comment by korydraughn** [comment]
Great! Closing.
