### ISSUE TITLE
test_status_with_invalid_host fails

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7459]
The test `test_control_plane.TestControlPlane.test_status_with_invalid_host` fails on tip of main. It also takes a very long time to run.
I can consistently reproduce this test failure in my Ubuntu 22.04 container with postgres.

Here's some snippets from the test output:
```
 --- IrodsSession: icommand executed by [rods#tempZone] [iadmin rmresc invalid_resc] --- 
Assert Command: iadmin rmresc invalid_resc
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | remote addresses: 10.200.0.3 ERROR: _rcConnect: connectToRhost timed out, retrying
    | remote addresses: 10.200.0.3 ERROR: _rcConnect: connectToRhost error, server on 18f5853d760c:1247 is probably down status = -115000 SYS_SOCK_READ_TIMEDOUT
    | remote addresses: 10.200.0.3 ERROR: rcConnect failure SYS_SOCK_READ_TIMEDOUT () (-115000) _rcConnect: connectToRhost failed
    | 
Unexpected output on stderr

FAILED TESTING ASSERTION
```
```
 --- IrodsSession: icommand executed by [rods#tempZone] [iinit] --- 
Assert Command: iinit
Expecting STDOUT_SINGLELINE: ['']
  stdout:
    | WARNING: Error 25 disabling echo mode. Password will be displayed in plaintext.
    | Enter your current iRODS password:
  stderr:
    | remote addresses: 10.200.0.3 ERROR: _rcConnect: connectToRhost timed out, retrying
    | remote addresses: 10.200.0.3 ERROR: _rcConnect: connectToRhost error, server on 18f5853d760c:1247 is probably down status = -115000 SYS_SOCK_READ_TIMEDOUT
    | remote addresses: 10.200.0.3 ERROR: Saved password, but failed to connect to server 18f5853d760c
Unexpected output on stderr

FAILED TESTING ASSERTION
```
```
======================================================================
FAIL: test_status_with_invalid_host (irods.test.test_control_plane.TestControlPlane)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_control_plane.py", line 195, in test_status_with_invalid_host
    self.assertTrue(({'failed_to_connect': 'tcp://invalid_host:1248'} in host_responses) or ({'response_message_is_empty_from': 'tcp://invalid_host:1248'} in host_responses))
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_control_plane.py", line 197, in test_status_with_invalid_host
    admin_session.assert_icommand('iadmin rmresc invalid_resc')
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```
```
======================================================================
FAIL: test_status_with_invalid_host (irods.test.test_control_plane.TestControlPlane)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/session.py", line 82, in tearDown
    with make_session_for_existing_admin() as admin_session:
  File "/var/lib/irods/scripts/irods/test/session.py", line 37, in make_session_for_existing_admin
    return IrodsSession(env_dict, test.settings.PREEXISTING_ADMIN_PASSWORD, False)
  File "/var/lib/irods/scripts/irods/test/session.py", line 103, in __init__
    self.assert_icommand('iinit', 'STDOUT_SINGLELINE',
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

**Comment by alanking** [comment]
Also seems potentially related to https://github.com/irods/irods/issues/7389 and #7458.

Just linking these together for posterity in case it proves useful

**Comment by alanking** [comment]
Linking to https://github.com/irods/irods/issues/7521 as well. Something funny about this test suite.

**Comment by alanking** [comment]
I have not been able to reproduce this failure in the particular way described here (SYS_SOCK_READ_TIMEDOUT). I've seen other failures as described in #7389 and #7521, but not like this one.The only thing I can think of is that maybe our TCP keepalive settings differ?

In any case, I'm going to leave this open at least until closer to release and we can decide what to do with it. Same for #7458.

**Comment by alanking** [comment]
Almost a year later...

I built an Ubuntu 22.04 runner image from the development environment. I built the tip of 4-3-stable (at time of writing) using a builder image from the testing environment. I installed the packages and set up iRODS using the default configuration.

I started the iRODS server and I tried running this test like this as the `irods` service account user:
```
python3 scripts/run_tests.py --run_specific_test test_control_plane.TestControlPlane.test_status_with_invalid_host --no_buf
```
The test passed with no problems:
```
irods.test.test_control_plane.TestControlPlane.test_status_with_invalid_host ... ok

----------------------------------------------------------------------
Ran 1 test in 106.781s

OK
<__main__.RegisteredTestResult run=1 errors=0 failures=0>
```
This test is also passing consistently in the testing environment.

Next, I'm going to try this with a debug build in the testing environment runner image.

**Comment by trel** [comment]
looking promising... maybe both this and https://github.com/irods/irods/issues/7458 are just working now...

**Comment by alanking** [comment]
The test passed with a debug build as well:
```
irods.test.test_control_plane.TestControlPlane.test_status_with_invalid_host ... ok

----------------------------------------------------------------------
Ran 1 test in 107.908s

OK
<__main__.RegisteredTestResult run=1 errors=0 failures=0>
```

**Comment by trel** [comment]
close it.

**Comment by alanking** [comment]
Closing. Please open a new issue for observed failures.
