### ISSUE TITLE
Please tell me how to build iRODS to use mariadb.

### ISSUE THREAD

**Issue by Narushima2030** [irods/irods#7469]
- [x] main
- [x] 4-3-stable
---
Ubuntu:20.04 + mariadb:10.3 + iRODS:4.3.1
I would like to configure iRODS in this environment. Please tell me how to set it up.

I tried to build it using the steps below.

```
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 523, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 123, in setup_server
    database_interface.setup_database_config(irods_config)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 96, in setup_database_config
    db_type = get_database_type()
  File "/var/lib/irods/scripts/irods/database_interface.py", line 90, in get_database_type
    raise IrodsError('Database type must be one of postgres, cockroachdb, mysql, or oracle.')
irods.exceptions.IrodsError: Database type must be one of postgres, cockroachdb, mysql, or oracle.
```

Install irods-database-plugin-mysql

5.install irods-database-plugin-mysql 

Install it as it is required as a dependent package.
6.install default-mysql-client
7.install mysql-client-8.0 

Removing mariadb when installing mysql-client-8.0

```
(Reading database ... 111979 files and directories currently installed.)
Removing mariadb-client (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-server (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-server-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-client-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-client-core-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
```

I would like to know the best way to build an iRODS environment using mariadb.

**Comment by alanking** [comment]
iRODS does not provide a mariadb database plugin, but through testing and some usage in the community, it has been shown that the mysql database plugin works well with a mariadb database server and ODBC drivers (with some exceptions - see https://github.com/irods/irods/issues/7323 for one).

So mysql-client-8.0 is automatically removing the mariadb packages? Is tihs preventing you from achieving the mysql/mariadb hybrid solution? Have you tried re-installing the mariadb packages after installing the mysql packages, or are they mutually exclusive?

**Comment by Narushima2030** [comment]
Thanks for the reply.

Refer to information from others such as this issue
mariadb database server and ODBC drivers and mysql database plugin 
Since I was building it with , I thought it could be achieved similarly.

However, I am not able to successfully substitute the mysql database plugin for using the mariadb database server, so I asked this question to confirm that there are no mistakes in my construction method.

>So mysql-client-8.0 is automatically removing the mariadb packages?
yes.

>Is tihs preventing you from achieving the mysql/mariadb hybrid solution? 
yes. It seems so.

>Have you tried re-installing the mariadb packages after installing the mysql packages, or are they mutually exclusive?
Seems to be mutually exclusive.

mysql(server,client) install after mariadb(server,client) install

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  galera-3 libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libfwupdplugin1 libsnappy1v5
  libxmlb1 mariadb-common socat
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  mysql-client-8.0 mysql-client-core-8.0 mysql-server-8.0 mysql-server-core-8.0
Suggested packages:
  mailx tinyca
The following packages will be REMOVED:
  mariadb-client mariadb-client-10.3 mariadb-client-core-10.3 mariadb-server mariadb-server-10.3
  mariadb-server-core-10.3
The following NEW packages will be installed:
  mysql-client mysql-client-8.0 mysql-client-core-8.0 mysql-server mysql-server-8.0
  mysql-server-core-8.0
0 upgraded, 6 newly installed, 6 to remove and 4 not upgraded.
Need to get 29.1 MB of archives.
After this operation, 100 MB of additional disk space will be used.
Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client-core-8.0 amd64 8.0.35-0ubuntu0.20.04.1 [5079 kB]
Get:2 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client-8.0 amd64 8.0.35-0ubuntu0.20.04.1 [22.0 kB]
Get:3 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-server-core-8.0 amd64 8.0.35-0ubuntu0.20.04.1 [22.6 MB]
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-server-8.0 amd64 8.0.35-0ubuntu0.20.04.1 [1326 kB]
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-client all 8.0.35-0ubuntu0.20.04.1 [9364 B]
Get:6 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 mysql-server all 8.0.35-0ubuntu0.20.04.1 [9472 B]
Fetched 29.1 MB in 4s (7595 kB/s)      
Preconfiguring packages ...
(Reading database ... 129826 files and directories currently installed.)
Removing mariadb-client (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-server (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-server-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-client-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-client-core-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
Removing mariadb-server-core-10.3 (1:10.3.38-0ubuntu0.20.04.1) ...
```

mariadb(server,client) install after mysql(server,client) install

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libmecab2 libxmlb1 mecab-ipadic mecab-ipadic-utf8 mecab-utils
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  galera-3 libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libsnappy1v5 mariadb-client-10.3
  mariadb-client-core-10.3 mariadb-common mariadb-server-10.3 mariadb-server-core-10.3 socat
Suggested packages:
  libmldbm-perl libnet-daemon-perl libsql-statement-perl mailx mariadb-test tinyca
The following packages will be REMOVED:
  mysql-client mysql-client-8.0 mysql-client-core-8.0 mysql-server mysql-server-8.0
  mysql-server-core-8.0
The following NEW packages will be installed:
  galera-3 libconfig-inifiles-perl libdbd-mysql-perl libdbi-perl libsnappy1v5 mariadb-client-10.3
  mariadb-client-core-10.3 mariadb-common mariadb-server mariadb-server-10.3
  mariadb-server-core-10.3 socat
0 upgraded, 12 newly installed, 6 to remove and 4 not upgraded.
Need to get 19.6 MB of archives.
After this operation, 93.6 MB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-common all 1:10.3.38-0ubuntu0.20.04.1 [15.9 kB]
Get:2 http://nova.clouds.archive.ubuntu.com/ubuntu focal/universe amd64 galera-3 amd64 25.3.29-1 [898 kB]
Get:3 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/main amd64 libdbi-perl amd64 1.643-1ubuntu0.1 [730 kB]
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu focal/main amd64 libconfig-inifiles-perl all 3.000002-1 [40.6 kB]
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu focal/main amd64 libsnappy1v5 amd64 1.1.8-1build1 [16.7 kB]
Get:6 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-client-core-10.3 amd64 1:10.3.38-0ubuntu0.20.04.1 [5855 kB]
Get:7 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-client-10.3 amd64 1:10.3.38-0ubuntu0.20.04.1 [1129 kB]
Get:8 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-server-core-10.3 amd64 1:10.3.38-0ubuntu0.20.04.1 [6249 kB]
Get:9 http://nova.clouds.archive.ubuntu.com/ubuntu focal/main amd64 socat amd64 1.7.3.3-2 [323 kB]
Get:10 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-server-10.3 amd64 1:10.3.38-0ubuntu0.20.04.1 [4203 kB]
Get:11 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libdbd-mysql-perl amd64 4.050-3ubuntu0.2 [83.2 kB]
Get:12 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates/universe amd64 mariadb-server all 1:10.3.38-0ubuntu0.20.04.1 [12.7 kB]
Fetched 19.6 MB in 4s (5315 kB/s)           
Preconfiguring packages ...
(Reading database ... 111752 files and directories currently installed.)
Removing mysql-client (8.0.35-0ubuntu0.20.04.1) ...
Removing mysql-server (8.0.35-0ubuntu0.20.04.1) ...
Removing mysql-server-8.0 (8.0.35-0ubuntu0.20.04.1) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Removing mysql-client-8.0 (8.0.35-0ubuntu0.20.04.1) ...
Removing mysql-client-core-8.0 (8.0.35-0ubuntu0.20.04.1) ...
Removing mysql-server-core-8.0 (8.0.35-0ubuntu0.20.04.1) ...
```

**Comment by SwooshyCueb** [comment]
I could be wrong, but my understanding is that if you have the mariadb packages, you don't need the mysql packages.

**Comment by Narushima2030** [comment]
Thank you for your comment.

I also understand that if you have the mariadb package, you don't need the mysql package.
I was hoping for a replacement for the mysql database plugin when using mariadb, but I may need another method.

**Comment by Narushima2030** [comment]
Thank you for your comment.

I also understand that if you have the mariadb package, you don't need the mysql package.
I was hoping to replace the mysql database plugin when using mariadb, but package dependencies seem to make that impossible.

**Comment by korydraughn** [comment]
You will need the iRODS MySQL database plugin. The ODBC driver for MariaDB is supposed to be compatible with MySQL.

Did you compare what you did against the steps in #7323?

Are you running the iRODS server and the MariaDB database on the same machine?
Can you access the MariaDB database using some other command line tool?

**Comment by SwooshyCueb** [comment]
> I was hoping to replace the mysql database plugin when using mariadb, but package dependencies seem to make that impossible.

I'm not sure I'm understanding you properly.
Our mysql database plugin package isn't supposed to conflict with any mariadb packages. Are you saying that's not the case?

**Comment by SwooshyCueb** [comment]
I'm thinking the package issue is the only issue being reported here, so I'm going to go ahead and assign this to myself to look into further once I'm done working on irods/externals#220

**Comment by SwooshyCueb** [comment]
The package dependency declaration issue has been resolved. There are still some remaining issues with mariadb and the mariadb ODBC connector, which are being tracked in other issues.

I'm going to close this issue now.
