### ISSUE TITLE
Post-install test fails when using mariadb

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods#7494]
Setting up irods with the mysql plugin pointed at a mariadb server and using the mariadb odbc driver errors out at the very end during teh post-install test:

```
+---------------------------+
| Running Post-Install Test |
+---------------------------+

Calling ['/usr/sbin/irodsTestPutGet'] with options:
{'shell': False, 'stderr': -1, 'stdout': -1}
Command /usr/sbin/irodsTestPutGet returned with code 1.
stderr:
  Error: cannot remove data object ["/tempZone/home/rods/post_install_test.1707763399640759.txt"]
Error encountered running setup_irods:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 523, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 148, in setup_server
    test_put(irods_config)
  File "/var/lib/irods/scripts/setup_irods.py", line 180, in test_put
    raise IrodsError('Post-install test failed. Please check your configuration.')
irods.exceptions.IrodsError: Post-install test failed. Please check your configuration.
Exiting...
```

However, a quick test with `ils` and `itouch` shows that the server is working, albeit with the `CAT_SUCCESS_BUT_WITH_NO_INFO` behavior described in #7323:

```
root@7913a03a187c:/tmp# sudo -u irods -g irods -H ils
/tempZone/home/rods:
root@7913a03a187c:/tmp# sudo -u irods -g irods -H itouch asdf
Level 0: CAT_SUCCESS_BUT_WITH_NO_INFO: cannot set mtime for [/tempZone/home/rods/asdf]


root@7913a03a187c:/tmp# sudo -u irods -g irods -H ils
/tempZone/home/rods:
  asdf
```

This has been observed with a post-#7485 build of irods in the following environments:
- Ubuntu 22.04 container with MariaDB 10.6 from the Ubuntu repos running in the same container, using the MariaDB ODBC driver from the Ubuntu repos.
- Ubuntu 22.04 container with MariaDB 10.6 from the Ubuntu repos running in the same container, using the MariaDB ODBC driver version 3.1.20 provided by MariaDB.

**Comment by MartinFlores751** [comment]
After a live debugging session with @korydraughn and @trel present, we found that adding a sleep after `create_data_object_if_necessary(...)` fixed this issue.

The sleep was added after this if block: https://github.com/irods/irods/blob/14b302498a86489a080d77fa99d2977b2631d06a/plugins/api/src/touch.cpp#L442-L446

The `CAT_SUCCESS_BUT_WITH_NO_INFO` originates from the following code block: https://github.com/irods/irods/blob/14b302498a86489a080d77fa99d2977b2631d06a/plugins/database/src/low_level_odbc.cpp#L514-L532

It is believed that the creation and update transactions were happening too close together, leading to `SQLRowCount(...)` returning 0.

The `CAT_SUCCESS_BUT_WITH_NO_INFO` happens when creating a new data object with `itouch`. Running `itouch` on an existing data object does not create the issue.

---

It might be worthwhile to look and see if the documentation is different for MariaDB ODBC vs. other database connectors.

**Comment by trel** [comment]
looks like we might be able to set an ODBC connection option to return `FOUND_ROWS`, rather than affected rows...
https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html#codbc-dsn-option-flags

this would presumably return `1`, and would solve the issue...

**Comment by korydraughn** [comment]
MariaDB may not support that. This is the documentation of interest for MariaDB when it comes to those settings.
- https://mariadb.com/docs/connectors/mariadb-connector-odbc/mariadb-connector-odbc-guide#general-connection-parameters

Notice the `OPTION`/`OPTIONS` parameter _(MySQL also supports this)_. Setting it to 2 appears to align with the `FOUND_ROWS=1` option for MySQL 8. I haven't tested this.

**Comment by trel** [comment]
agreed. bit 1, value 2.

> 1(2) - Tells connector to return the number of matched rows instead of number of changed rows
