### ISSUE TITLE
setup_irods unable to resolve hostname to local machine in cloud setup

### ISSUE THREAD

**Issue by tsmeele** [irods/irods#7529]
### iRODS Version, OS and Version
iRODS 4.3.1 on Ubuntu 20
Cloud based workspace.

### What did you try to do?
Run setup_irods.py after installation of packages for iRODS provider

### Expected behavior
Script would ask user parameters

### Observed behavior (including steps to reproduce, if applicable)
Fatal error, hostname does not resolve to local machine.  

Output:
```
root@ubuntu2004sudo:/var/lib/irods/scripts# python3 setup_irods.py 
Error encountered running setup_irods:
Traceback (most recent call last):
  File "setup_irods.py", line 523, in main
    setup_server(irods_config,
  File "setup_irods.py", line 74, in setup_server
    check_hostname()
  File "setup_irods.py", line 194, in check_hostname
    raise IrodsError('The hostname (%s) must resolve to the local machine.' % (hostname))
irods.exceptions.IrodsError: The hostname (ubuntu2004sudo.researchcloudde.src.surf-hosted.nl) must resolve to the local machine.
root@ubuntu2004sudo:/var/lib/irods/scripts# hostname
ubuntu2004sudo.researchcloudde.src.surf-hosted.nl
root@ubuntu2004sudo:/var/lib/irods/scripts# cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
145.38.194.252  ubuntu2004sudo.researchcloudde.src.surf-hosted.nl
root@ubuntu2004sudo:/var/lib/irods/scripts# 
```
The error appears related to the fact that the /etc/hosts file specifies an external IP address for the hostname, which is a common configuration in cloud environments.

Ideally the setup_irods.py would be able to support such a configuration. A workaround could be to have an option to the Python script to ignore the failing hostname resolution check.

**Comment by trel** [comment]
This could be remedied today with a --json_configuration_file that has already been manipulated to hold the hosts information?

steps would be...
- start container/vm/cloud instance
- copy a templated configuration file to the real configuration file 'to be'
- manipulate the configuration file to taste (with any hostnames/ips necessary)
- run `setup_irods.py --json_configuration_file`

**Comment by tsmeele** [comment]
Unfortunately not, the error is thrown before the config file is parsed.

Met vriendelijke groet,

Ton
________________________________

**Comment by trel** [comment]
oh!   hmm...

**Comment by trel** [comment]
Does it behave better if you were to append the resolved hostname to the 127.0.0.1 line in /etc/hosts?

**Comment by tsmeele** [comment]
Yes shen i change /etc/hosts the problem vanishes, as expected.

Met vriendelijke groet,

Ton
________________________________

**Comment by trel** [comment]
We could offer a 'skip-local-put-test' option to the setup script...

Or not do the check that makes sure that `localhost` routes to self...

Not sure what else we can do here without a larger revamp of hostname resolution itself.

**Comment by tsmeele** [comment]
An option to bypass the test that makes sure that FQDN resolves to localhost should probably be sufficient to allow us setup iRODS in cloud environments.  Once iRODS is in place it will be able to listen on 1247 and answer to any iput tests as usual.

**Comment by trel** [comment]
The `irodsTestPutGet` connects to localhost... so I see either we...
a) add an option to skip the test entirely, or
b) add an option/way to have the test itself use a different hostname for `irodsTestPutGet`, or
c) both?!

**Comment by tsmeele** [comment]
whatever works to support a cloud install :)

**Comment by tsmeele** [comment]
For iRODS 4.3.3 unattended installs on cloud, it appears sufficient to skip the test entirely by inserting a 'return' statement immediately after the def check_hostname() line.   
My preconditions are:
- In the json_configuration_file, specify the FQDN as the catalog provider host.
- Linux command 'hostname' set to FQDN
- /etc/hosts unmodified, it still has an entry for FQDN that points to an IP address that appears to be non-local.

**Comment by kript** [comment]
For the benefit of others ~banging their heads against~ bumping into this issue, this is also the default behaviour of Kubernetes, which is _not confusing at all_ when docker compose works and kubectl doesn't on a file converted with `kompose convert`. 😉 

If its helpful, version  found this on;

```sh
$ minikube version
minikube version: v1.35.0
commit: dd5d320e41b5451cdf3c01891bc4e13d189586ed-dirty
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.0
```
