### ISSUE TITLE
Outdated installation doc for PostgreSQL >= 15 ?

### ISSUE THREAD

**Issue by lsioctl** [irods/irods#7831]
Hello,

Following the install documentation on PostgreSQL

https://docs.irods.org/4.3.2/getting_started/installation/

I had this error saying I can't access to the public schema.

 (sorry for the French in the logs I have to change that :D)

```bash
Traceback (most recent call last):
  File "/var/lib/irods/scripts/setup_irods.py", line 540, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/lib/irods/scripts/setup_irods.py", line 526, in main
    setup_server(irods_config,
  File "/var/lib/irods/scripts/setup_irods.py", line 134, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory, default_resource_name=default_resource_name)
  File "/var/lib/irods/scripts/irods/database_interface.py", line 26, in setup_catalog
    if database_connect.create_database_tables(irods_config, cursor) != 'skipped':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/irods/scripts/irods/database_connect.py", line 369, in create_database_tables
    execute_sql_file(sql_file, cursor, by_line=True)
  File "/var/lib/irods/scripts/irods/database_connect.py", line 267, in execute_sql_file
    cursor.execute(line)
pyodbc.ProgrammingError: ('42501', '[42501] ERREUR: droit refusé pour le schéma public;\nError while executing the query\x00稨 (1) (SQLExecDirectW)')
```

It seems that is related to PostgreSQL >= 15, as spotted in this SO:

https://stackoverflow.com/questions/74110708/postgres-15-permission-denied-for-schema-public

I had to type this command:

```bash
ALTER DATABASE "ICAT" OWNER TO irods;
```

And after everything went smoothly.

**Comment by trel** [comment]
pulling this into 4.3.3

**Comment by SwooshyCueb** [comment]
yes, the docs have already been updated for 4.3.3.

**Comment by alanking** [comment]
I think we can treat this issue as a  duplicate of https://github.com/irods/irods/issues/7382.
