### ISSUE TITLE
`test_icommands_file_operations.Test_ICommands_File_Operations_3` fails on EL8 when SSL is enabled

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7933]
## Testing

Testing environment setup:
- Running topology tests from `provider`
  - i.e. `python run_topology_tests.py <args> provider`
- SSL enabled

The following output was captured for `test_icommands_file_operations.Test_ICommands_File_Operations_3`.
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="11" file="irods/test/test_icommands_file_operations.py" name="irods.test.test_icommands_file_operations.Test_ICommands_File_Operations_3-20240802171324" skipped="0" tests="11" time="2680.511" timestamp="2024-08-02T17:58:04">
        <testcase classname="irods.test.test_icommands_file_operations.Test_ICommands_File_Operations_3" file="scripts/irods/test/test_icommands_file_operations.py" line="505" name="test_cancel_large_iput_for_create" time="0.000" timestamp="0001-01-01T00:00:00">
                <failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_icommands_file_operations.py", line 526, in test_cancel_large_iput_for_create
    self.user0.assert_icommand('ils -l', 'STDOUT_SINGLELINE', [file_name, str(new_size)])
  File "/var/lib/irods/scripts/irods/test/session.py", line 162, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 76, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
AssertionError
]]>             </failure>
```
```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [ichmod write bobby ../../public/testfile.txt] --- 
Assert Command: ichmod write bobby ../../public/testfile.txt
Expecting EMPTY: ['']
  stdout:       
    | 
  stderr:
    | 
Output found

run_resource_setup - END
 --- IrodsSession: icommand executed by [alice#tempZone] [iquest %s select RESC_VAULT_PATH where RESC_NAME = 'demoResc'] --- 


INTERRUPTING iCMD
running icommand: alice[iput '/tmp/irods-test-icommands-recursive/test_cancel_large_put/junk0000']
  filename set to: [/var/lib/irods/Vault/home/alice/2024-08-02Z17:13:27--irods-testing-tz0nkexh/junk0000]
  filesize set to: [10] bytes
 --- IrodsSession: icommand executed by [alice#tempZone] [ils -l] --- 
Assert Command: ils -l
Expecting STDOUT_SINGLELINE: ['junk0000', '809500672']
  stdout:
    | 
  stderr:
    | remote addresses: 10.15.2.5 ERROR: _rcConnect: connectToRhost timed out, retrying
    | remote addresses: 10.15.2.5 ERROR: _rcConnect: connectToRhost error, server on 08780d6a349c:1247 is probably down status = -115000 SYS_SOCK_READ_TIMEDOUT
Unexpected output on stderr

FAILED TESTING ASSERTION
```

The tests pass when SSL is disabled.

Please investigate.

_This applies to 4-3-stable only._

**Comment by SwooshyCueb** [comment]
This also affects Debian 11: https://github.com/SwooshyCueb/irods-test-logs/tree/main/433-deb11-p14-top1-ssl-5_468a442a-40ba-412b-96a1-0f6d28d26516/logs/433-deb11-p14-top1-ssl-5_irods-catalog-provider_1

**Comment by korydraughn** [comment]
From the test output:
```
INTERRUPTING iCMD                                                                                                                                                                             
running icommand: alice[iput '/tmp/irods-test-icommands-recursive/test_cancel_large_put/junk0000']                                                                                            
  filename set to: [/var/lib/irods/Vault/home/alice/2025-02-24Z22:24:55--irods-testing-3d2ezrur/junk0000]                                                                                                                                                                                                                                                                                    
  filesize set to: [10] bytes                                                                                                                                                                                                                                                                                                                                                                
 --- IrodsSession: icommand executed by [alice#tempZone] [ils -l] ---                                                                                                                                                                                                                                                                                                                        
Assert Command: ils -l                                                                                                                                                                        
Expecting STDOUT_SINGLELINE: ['junk0000', '809500672']                                         
  stdout:                                                                                                                                                                                     
    | /tempZone/home/alice/2025-02-24Z22:24:55--irods-testing-3d2ezrur:                        
    |   alice             0 demoResc            0 2025-02-24.22:25 ? junk0000                                                                                                                 
  stderr:                                                                                                                                                                                     
    |                                                                                                                                                                                         
Output not found                                                                                                                                                                              
                                                                                                                                                                                              
FAILED TESTING ASSERTION
```

**Comment by trel** [comment]
This sounds good.   Any other side effects that we can think of by ignoring SIGPIPE?

**Comment by korydraughn** [comment]
Ignoring that signal moves the handling of broken pipes to the call site, which I believe is covered by the current implementation. 4.2 ignores SIGPIPE and I believe this issue and #7934 are actually highlighting a regression which was introduced in 4.3.0.

**Comment by korydraughn** [comment]
The main branch does not have this issue because it already ignores SIGPIPE for agents.

https://github.com/irods/irods/blob/15e9213fc366acb486fa04f62c0a11f23f0ab331/server/main_server/src/agent_main.cpp#L730-L731

Removed checkbox for main branch.
