### ISSUE TITLE
`test_resource_types.Test_Resource_Unixfilesystem` fails on EL8 when SSL is enabled

### ISSUE THREAD

**Issue by korydraughn** [irods/irods#7934]
## Testing

Testing environment setup:
- Running topology tests from `provider`
  - i.e. `python run_topology_tests.py <args> provider`
- SSL enabled

The following output was captured for `test_resource_types.Test_Resource_Unixfilesystem`.
```
        <testcase classname="irods.test.test_resource_types.Test_Resource_Unixfilesystem" file="scripts/irods/test/test_resource_types.py" line="562" name="test_local_iput_interrupt_largefile" time="0.000" timestamp="0001-01-01T00:00:00">
                <failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/resource_suite.py", line 589, in test_local_iput_interrupt_largefile
    self.admin.assert_icommand(iputcmd, 'STDOUT', "was restarted successfully")
  File "/var/lib/irods/scripts/irods/test/session.py", line 162, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 76, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 104, in _assert_helper
    assert result
AssertionError
]]>             </failure>
```
```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iquest %s select DATA_SIZE where DATA_NAME = '/tempZone/home/otherrods/2024-08-02Z17:29:43--irods-testing-v9ncigxq' and DATA_REPL_NUM = '0'] ---
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iput --lfrestart /tmp/irods-testing-v9ncigxq/bigrestartfile /tmp/irods-testing-v9ncigxq/bigfile] --- 
Assert Command: iput --lfrestart /tmp/irods-testing-v9ncigxq/bigrestartfile /tmp/irods-testing-v9ncigxq/bigfile
Expecting STDOUT: ['was restarted successfully']
  stdout:
    | 
  stderr:
    | remote addresses: 10.15.2.4 ERROR: cannot open target file /tempZone/home/otherrods/2024-08-02Z17:29:43--irods-testing-v9ncigxq/bigfile, status = -1803000 status = -1803000 HIERARCHY_ERROR
    | remote addresses: 10.15.2.4 ERROR: putUtil: put error for /tempZone/home/otherrods/2024-08-02Z17:29:43--irods-testing-v9ncigxq/bigfile, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG
Unexpected output on stderr

FAILED TESTING ASSERTION
```

The tests pass when SSL is disabled.

Please investigate.

_This applies to 4-3-stable only._

**Comment by SwooshyCueb** [comment]
This also affects Debain 11: https://github.com/SwooshyCueb/irods-test-logs/tree/main/433-deb11-p14-top1-ssl-5_468a442a-40ba-412b-96a1-0f6d28d26516/logs/433-deb11-p14-top1-ssl-5_irods-catalog-provider_2

**Comment by korydraughn** [comment]
This is still reproducible in tip of 4-3-stable.

I added a call to `ils` following interruption of the `iput` and learned that the replica being PUT is left in the intermediate state, when it should be made stale on agent tear down. That explains the hierarchy error and overwrite error.
```
INTERRUPTING iCMD                                                                                                                                                                                             
running icommand: otherrods[iput --lfrestart /tmp/irods-testing-3e6nhuw0/bigrestartfile /tmp/irods-testing-3e6nhuw0/bigfile]                                                                                  
  filename set to: [/tmp/irods-testing-3e6nhuw0/bigrestartfile]                                                                                                                                               
  filesize set to: [300] bytes                                                                                                                                                                                
  restartfile [/tmp/irods-testing-3e6nhuw0/bigrestartfile] contents --> [                                                                                                                                     
<FileRestartInfo_PI>                                                                                                                                                                                          
                                                                                                                                                                                                              
<fileName>/tmp/irods-testing-3e6nhuw0/bigfile</fileName>                                                                                                                                                      
                                                                                                                                                                                                              
<objPath>/tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile</objPath>                                                                                                               
                                                                                                                                                                                                              
<numSeg>4</numSeg>                                                                                                                                                                                            
                                                                                                                                                                                                              
<flags>0</flags>                                                                                                                                                                                              
                                                                                                                                                                                                              
<fileSize>600000000</fileSize>                                                                                                                                                                                
                                                                                                                                                                                                              
<DataSeg_PI>                                                                                                                                                                                                  
                                                                                                                                                                                                              
<len>8388608</len>                                                                                                                                                                                            
                                                                                                                                                                                                              
<offset>0</offset>                                                                                                                                                                                            
                                                                                                                                                                                                              
</DataSeg_PI>                                                                                                                                                                                                 
                                                                                                                                                                                                              
<DataSeg_PI>                                                                                                                                                                                                  
                                                                                                                                                                                                              
<len>8388608</len>                                                                                                                                                                                            
                                                                                                                                                                                                              
<offset>150000000</offset>                                                                                                                                                                                    
                                                                                                                                                                                                              
</DataSeg_PI>                                                                                                                                                                                                 
                                                                                                                                                                                                              
<DataSeg_PI>                                                                                                                                                                                                  
                                                                                                                                                                                                              
<len>8388608</len>                                                                                                                                                                                            
                                                                                                                                                                                                              
<offset>300000000</offset>                                                                                                                                                                                    
                                                                                                                                                                                                              
</DataSeg_PI>                                                                                                                                                                                                 
                                                                                                                                                                                                              
<DataSeg_PI>                                                                                                                                                                                                  
                                                                                                                                                                                                              
<len>8388608</len>                                                                                                                                                                                            
                                                                                                                                                                                                              
<offset>450000000</offset>                                                                                                                                                                                    
                                                                                                                                                                                                              
</DataSeg_PI>                                                                                                                                                                                                 
                                                                                                                                                                                                              
</FileRestartInfo_PI>                                                                                                                                                                                         
                                                                                                                                                                                                              
]                                                                                                                                                                                                             
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iquest %s select DATA_SIZE where DATA_NAME = '/tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0' and DATA_REPL_NUM = '0'] ---
 --- IrodsSession: icommand executed by [otherrods#tempZone] [ils -L /tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile] ---                                                        
Assert Command: ils -L /tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile                                                                                                           
Expecting STDOUT: ['']                                                                                                                                                                                        
  stdout:                                                                                                                                                                                                     
    |   otherrods         0 demoResc            0 2025-02-24.21:36 ? bigfile                                                                                                                                  
    |         generic    /var/lib/irods/demoRescVault/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile                                                                                      
  stderr:                                                                                                                                                                                                     
    |                                                                                                                                                                                                         
Output found                                                                                                                                                                                                  
                                                                                                                                                                                                              
 --- IrodsSession: icommand executed by [otherrods#tempZone] [iput --lfrestart /tmp/irods-testing-3e6nhuw0/bigrestartfile /tmp/irods-testing-3e6nhuw0/bigfile] ---                                            
Assert Command: iput --lfrestart /tmp/irods-testing-3e6nhuw0/bigrestartfile /tmp/irods-testing-3e6nhuw0/bigfile                                                                                               
Expecting STDOUT: ['was restarted successfully']                                                                                                                                                              
  stdout:                                                                                                                                                                                                     
    |                                                                                                                                                                                                         
  stderr:                                                                                                                                                                                                     
    | remote addresses: 10.15.1.3 ERROR: cannot open target file /tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile, status = -1803000 status = -1803000 HIERARCHY_ERROR            
    | remote addresses: 10.15.1.3 ERROR: putUtil: put error for /tempZone/home/otherrods/2025-02-24Z21:36:00--irods-testing-3e6nhuw0/bigfile, status = -312000 status = -312000 OVERWRITE_WITHOUT_FORCE_FLAG  
Unexpected output on stderr                                                                                                                                                                                   
                                                                                                                                                                                                              
FAILED TESTING ASSERTION                                                                                                                                                                                      
```

The agent servicing the request is terminated by signal 13 - i.e. SIGPIPE.

I believe this test fails because of the following:
https://github.com/irods/irods/blob/fce3dafc3cb571b91665cd8bf52fefa24696c1f0/server/core/src/rodsAgent.cpp#L561

SIGPIPE must be ignored in order for POSIX write(socket) to return EPIPE. This would allow the error to be handled at the callsite and keep the agent from terminating immediately.

**Comment by korydraughn** [comment]
Turns out even 4-2-stable ignores SIGPIPE.

Changing the code to ignore SIGPIPE allowed the test to pass with SSL enabled.

**Comment by korydraughn** [comment]
The main branch does not have this issue because it already ignores SIGPIPE for agents.

https://github.com/irods/irods/blob/15e9213fc366acb486fa04f62c0a11f23f0ab331/server/main_server/src/agent_main.cpp#L730-L731

Removed checkbox for main branch.
