### ISSUE TITLE
irods server refuses to start due to schema issue in the hosts host_resolution.json for iRODS 4.3.2

### ISSUE THREAD

**Issue by mherkazandjian** [irods/irods#7941]
- [ ] main
- [ ] 4-3-stable

---

### iRODS Version, OS and Version
- iRODS Version: 4.3.2
- OS: CentOS 7

### What did you try to do?

I attempted to start the iRODS server using the command `/var/lib/irods/irodsctl start` after the i upgraded from
iRODS 4.2.11.

### Expected behavior
The iRODS server should start without errors.

### Observed behavior (including steps to reproduce, if applicable)
When starting the iRODS server, I encountered the following error:

```bash
testvm$ /var/lib/irods/irodsctl start
Error encountered running irods_control start:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/json_validation.py", line 60, in validate_dict
    jsonschema.validate(config_dict, schema, resolver=jsonschema.RefResolver(schema_uri, schema))
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: ['myhost.example.com'] is too short

Failed validating 'minItems' in schema['properties']['host_resolution']['properties']['host_entries']['items']['properties']['addresses']:
    {'items': {'minLength': 1, 'type': 'string'},
     'minItems': 2,
     'type': 'array',
     'uniqueItems': True}

On instance['host_resolution']['host_entries'][1]['addresses']:
    ['myhost.example.com']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods_control.py", line 124, in main
    operations_dict[operation]()
  File "/var/lib/irods/scripts/irods_control.py", line 70, in <lambda>
    operations_dict['start'] = lambda: irods_controller.start(write_to_stdout=options.write_to_stdout, test_mode=options.test_mode)
  File "/var/lib/irods/scripts/irods/controller.py", line 69, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 286, in validate_configuration
    config_file['path'])
  File "/var/lib/irods/scripts/irods/json_validation.py", line 79, in validate_dict
    sys.exc_info()[2])
  File "/var/lib/irods/scripts/irods/six.py", line 671, in reraise
    raise value.with_traceback(tb)
  File "/var/lib/irods/scripts/irods/json_validation.py", line 60, in validate_dict
    jsonschema.validate(config_dict, schema, resolver=jsonschema.RefResolver(schema_uri, schema))
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 478, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/usr/lib/python3.6/site-packages/jsonschema/validators.py", line 123, in validate
    raise error
irods.exceptions.IrodsError: ERROR: Validation Failed for [/etc/irods/server_config.json]:
        against [file:///var/lib/irods/configuration_schemas/v4/server_config.json]
        ValidationError: ['myhost.example.com'] is too short

Failed validating 'minItems' in schema['properties']['host_resolution']['properties']['host_entries']['items']['properties']['addresses']:
    {'items': {'minLength': 1, 'type': 'string'},
     'minItems': 2,
     'type': 'array',
     'uniqueItems': True}

On instance['host_resolution']['host_entries'][1]['addresses']:
    ['myhost.example.com']
```

### Resolution

To resolve this issue, I had to modify the file /var/lib/irods/configuration_schemas/v4/host_resolution.json. The change involved adjusting the minItems value for the addresses property from 2 to 1. The fix is implemented here https://github.com/irods/irods/pull/7940/files

**Comment by trel** [comment]
but.. it *does* need at least two entries?

the name AND the alias(es)?   like DNS...

https://docs.irods.org/4.3.2/system_overview/configuration/#host-resolution

**Comment by mherkazandjian** [comment]
i see.

here is some clarification on why i assumed a vaule of 1 would fix the problem.
In our config prior to the upgrade we had the following for a long time, that worked

```json
{                                                                     
    "schema_name": "hosts_config",                                    
    "schema_version": "v3",                                           
    "host_entries": [                                                 
        {                                                             
            "address_type" : "local",                                 
            "addresses" : [                                           
                {"address":"123.123.90.22"                          
                }                                                     
             ]                                                        
        },                                                            
        {                                                             
            "address_type" : "remote",                                
            "addresses" : [                                           
                {"address": "132.52.314.22",                           
                 "address": "xxxxx.foo.com"       
                }                                                     
             ]                                                        
        },                                                            
.
.
.
```

after the upgrade this got merged into the server_config.json as such

```json
 "host_resolution": {                                     
     "host_entries": [                                    
         {                                                
             "address_type": "local",                     
             "addresses": [              
               "123.123.90.22",                 
               "123.123.90.23"                  # <<<<  this was inserted during the upgrade
             ]                                            
         },                                               
         {                                                
             "address_type": "remote",                    
             "addresses": [
                 "xxxxx.foo.com"                # <<<< this was inserted without the ip addr
             ]                                            
         },                                               
.
.
.
```

so i am not why that happened during the migration 
[ not : i changed used fake ip addr and obviously hostnames to mask user info ]

**Comment by mherkazandjian** [comment]
mini update, i followed the schema and fixed the errors done during the migration and reverted the minItems to 2 on the machine and the irods service started. so the MR can be ignored  ( sorry about the rush ) but it might be worthwhile to look if there is indeed a bug during the migration. We have a second identical server we i'll keep an eye there too to help you maybe reproduce the problem.

**Comment by trel** [comment]
Got it - thanks.

Yes, seems a bug in the migration path we provided.

Is there anything else interesting / special about the server?   How many machines in the zone?   More than one catalog service provider?

**Comment by korydraughn** [comment]
The original hosts_config.json presented in https://github.com/irods/irods/issues/7941#issuecomment-2293881237 has an invalid structure. According to the documentation at https://docs.irods.org/4.2.11/system_overview/configuration/#etcirodshosts_configjson, each alias in the `addresses` list is required to have the following structure:
```js
"addresses" : [
    {"address": "<hostname_or_dns_name_or_ip>"},
    // ... More entries ...
    {"address": "<hostname_or_dns_name_or_ip>"}
]
```

That would mean the correct config would look like this:
```js
{
    "schema_name": "hosts_config",
    "schema_version": "v3",
    "host_entries": [
        {
            "address_type" : "local",
            "addresses" : [
                // As already mentioned, this list requires
                // a minimum of two elements.
                {"address":"123.123.90.22"}
             ]
        },
        {
            "address_type" : "remote",
            "addresses" : [
                // Notice how this updated listing puts each
                // alias in its own object.
                {"address": "132.52.314.22"},
                {"address": "xxxxx.foo.com"}
             ]
        },
.
.
.
```

With that in mind, I tried to reproduce the issue by isolating the migration logic and running the **invalid config** through it. That produced the following, which is also invalid because it violates the `minItems` schema constraint:
```js
{
    "host_resolution": {
        "host_entries": [
            {
                "address_type": "local",
                "addresses": [
                    "123.123.90.22"
                ]
            },
            {
                "address_type": "remote",
                "addresses": [
                    "xxxxx.foo.com"
                ]
            }
        ]
    }
}
```

However, based on the output and the implementation, I believe the result is correct. I'm sure the IP address for the remote entry was removed because the aliases share the same property name within the same object, meaning the JSON library viewed that as a redefinition of the `address` property. For example:
```bash
Python 3.8.10 (default, Feb  4 2025, 15:02:54) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads('{"a": "old", "a": "new"}')
{'a': 'new'}
```

I also tried reproducing the issue by manually upgrading a 4.2.11 server to 4.3.1. The results were identical to the results I saw in the isolated test scenario.

I believe things are working as intended and there's nothing actionable here due to the invalid hosts_config.json file. The JSON schema validation detected an issue and reported it, halting the server's startup and allowing the admin to address it, as designed.

Closing.
