### ISSUE TITLE
Upgrade to 4.3.1 doesn't correct server_config.schema_validation_base_uri default

### ISSUE THREAD

**Issue by tedgin** [irods/irods#8052]
### iRODS Version, OS and Version
iRODS 4.2.8, CentOS 7 and Ubuntu 18.04

### What did you try to do?
In my iRODS 4.2.8 `/etc/irods/server_config.json` file, `schema_validation_base_uri` is set `https://schemas.irods.org/configuration`, which according to the iRODS 4.2.8 documentation, is the default value. 

I upgraded to iRODS 4.3.1 using the system package manager, and then I started iRODS to complete the upgrade.

### Expected behavior
I expected iRODS to update `schema_validation_base_uri` to its 4.3.1 default of `file:///var/lib/irods/configuration_schemas`, and then start without warnings.

### Observed behavior (including steps to reproduce, if applicable)
I get bunch of warnings related to the configuration file schemas not being able to be found.

```console
-bash-4.2$ ./irodsctl start
WARNING: Validation Failed for [/etc/irods/server_config.json]:
        against [https://schemas.irods.org/configuration/v4/server_config.json]
        JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Warning encountered in json_validation for /etc/irods/server_config.json, skipping validation...
WARNING: Validation Failed for [/var/lib/irods/version.json]:
        against [https://schemas.irods.org/configuration/v4/version.json]
        JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Warning encountered in json_validation for /var/lib/irods/version.json, skipping validation...
WARNING: Validation Failed for [/var/lib/irods/.irods/irods_environment.json]:
        against [https://schemas.irods.org/configuration/v4/service_account_environment.json]
        JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Warning encountered in json_validation for /var/lib/irods/.irods/irods_environment.json, skipping validation...
Warning encountered in validation:
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/controller.py", line 69, in start
    self.config.validate_configuration()
  File "/var/lib/irods/scripts/irods/configuration.py", line 296, in validate_configuration
    lib.indent(*skipped)))
irods.exceptions.IrodsWarning: Skipped validation for the following files:
  /etc/irods/server_config.json
  /var/lib/irods/version.json
  /var/lib/irods/.irods/irods_environment.json
```

**Comment by trel** [comment]
we could arguably detect that the default value was used and 'should' be updated to the new default value...

but instead, we took the safer route of not touching someone's existing values at all.

**Comment by korydraughn** [comment]
Agreed. We can/should detect the default value and update that. Can't touch the property if it's been modified by an admin.

**Comment by korydraughn** [comment]
We'll investigate both of those for this issue. Thanks.

**Comment by tedgin** [comment]
I found two more values that are assumed to be defined in irods_environment.json:  `irods_maximum_size_for_single_buffer_in_megabytes` and `irods_transfer_buffer_size_for_parallel_transfer_in_megabytes`.

**Comment by korydraughn** [comment]
`schema_validation_base_uri` was removed in iRODS 5.0.0.

https://github.com/irods/irods/blob/c1fc9f2c4835c51355ec4b277bd3a663e4f9e095/scripts/irods/upgrade_configuration.py#L294-L298

Handling of the other properties has been fixed as well.

With the final release of 4.3 _(4.3.5)_ now available, this issue can be closed.
