### ISSUE TITLE
Main server process occasionally crashes (SIGSEGV) in `migrate_delay_server`

### ISSUE THREAD

**Issue by alanking** [irods/irods#8104]
### iRODS Version, OS and Version
4.3.3 "Debug" build with ASAN enabled, Ubuntu 24.04 (testing environment)

### Observed behavior (including steps to reproduce, if applicable)

I just ran an iRODS server like this:
```bash
# as iRODS service account user with pwd /var/lib/irods
export ASAN_SYMBOLIZER_PATH=/opt/irods-externals/clang13.0.1-0/bin/llvm-symbolizer
export IRODS_ADDRESS_SANITIZER_DEFAULT_OPTIONS="log_path=/tmp/irods_asan_output:detect_container_overflow=0"
./irodsctl start
```

Later (we'll say... less than 24 hours later), I noticed that the server was not running anymore, but there was still a delay server and (presumably) an agent factory process. I found this ASAN report:
```
=================================================================
==33039==ERROR: AddressSanitizer: SEGV on unknown address 0x610000050000 (pc 0x7ffbba0dda10 bp 0x7ffbb2b33dc0 sp 0x7ffbb2b33548 T1)
==33039==The signal is caused by a READ memory access.
    #0 0x7ffbba0dda10  (/lib/x86_64-linux-gnu/libc.so.6+0xc1a10)
    #1 0x4ccb3c in StrstrCheck(void*, char*, char const*, char const*) /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:578:29
    #2 0x50563a in __interceptor_strstr /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:597:16
    #3 0x7ffbba8e458b in (anonymous namespace)::parseXmlTag(void const*, char const*, int, int&) /irods_source/lib/core/src/packStruct.cpp:3210:29
    #4 0x7ffbba8e458b in (anonymous namespace)::parseXmlValue(void const*&, char const*, int&) /irods_source/lib/core/src/packStruct.cpp:3174:18
    #5 0x7ffbba8e458b in (anonymous namespace)::unpackXmlIntToOutPtr(void const*&, void*&, int, char const*) /irods_source/lib/core/src/packStruct.cpp:2355:28
    #6 0x7ffbba8e458b in (anonymous namespace)::unpackIntToOutPtr(void const*&, void*&, int, char const*, iRODSProtocol) /irods_source/lib/core/src/packStruct.cpp:2278:22
    #7 0x7ffbba8d8e51 in (anonymous namespace)::unpackInt(void const*&, PackedOutput&, int, char const*, iRODSProtocol) /irods_source/lib/core/src/packStruct.cpp:2259:24
    #8 0x7ffbba8d8e51 in (anonymous namespace)::unpackNonpointerItem(packItem&, void const*&, PackedOutput&, PackingInstruction const*, iRODSProtocol, std::__1::optional<irods::version> const&) /irods_source/lib/core/src/packStruct.cpp:1932:22
    #9 0x7ffbba8d8e51 in (anonymous namespace)::unpackItem(packItem&, void const*&, PackedOutput&, PackingInstruction const*, iRODSProtocol, std::__1::optional<irods::version> const&) /irods_source/lib/core/src/packStruct.cpp:1869:16
    #10 0x7ffbba8d8e51 in (anonymous namespace)::unpackChildStruct(void const*&, PackedOutput&, packItem const&, PackingInstruction const*, int, iRODSProtocol, char const*, std::__1::optional<irods::version> const&) /irods_source/lib/core/src/packStruct.cpp:2723:30
    #11 0x7ffbba8db857 in unpack_struct /irods_source/lib/core/src/packStruct.cpp:3489:18
    #12 0x7ffbbc77b3f6 in readVersion(boost::shared_ptr<irods::network_object>, Version**) /irods_source/lib/core/src/sockComm.cpp:669:18
    #13 0x7ffbbc77d93f in connectToRhost /irods_source/lib/core/src/sockComm.cpp:861:11
    #14 0x7ffbbc72d732 in _rcConnect /irods_source/lib/core/src/rcConnect.cpp:126:14
    #15 0x7ffbbc72d4b6 in rcConnect /irods_source/lib/core/src/rcConnect.cpp:42:12
    #16 0x7ffbbc67ea6b in irods::experimental::client_connection::only_connect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, irods::experimental::fully_qualified_username const&) /irods_source/lib/core/src/client_connection.cpp:184:13
    #17 0x7ffbbc67df04 in irods::experimental::client_connection::connect_and_login(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, irods::experimental::fully_qualified_username const&) /irods_source/lib/core/src/client_connection.cpp:157:9
    #18 0x7ffbbc67da82 in irods::experimental::client_connection::client_connection() /irods_source/lib/core/src/client_connection.cpp:16:9
    #19 0x57ce29 in (anonymous namespace)::migrate_delay_server(bool, bool) /irods_source/server/main_server/src/rodsServer.cpp:818:39
    #20 0x57ce29 in initServerMain(RsComm*, bool, bool)::$_13::operator()() const /irods_source/server/main_server/src/rodsServer.cpp:2273:9
    #21 0x57c2dc in decltype(static_cast<initServerMain(RsComm*, bool, bool)::$_13&>(fp)()) std::__1::__invoke<initServerMain(RsComm*, bool, bool)::$_13&>(initServerMain(RsComm*, bool, bool)::$_13&) /opt/irods-externals/clang13.0.1-0/include/c++/v1/type_traits:3934:1
    #22 0x57c2dc in void std::__1::__invoke_void_return_wrapper<void, true>::__call<initServerMain(RsComm*, bool, bool)::$_13&>(initServerMain(RsComm*, bool, bool)::$_13&) /opt/irods-externals/clang13.0.1-0/include/c++/v1/__functional/invoke.h:61:9
    #23 0x57c2dc in std::__1::__function::__alloc_func<initServerMain(RsComm*, bool, bool)::$_13, std::__1::allocator<initServerMain(RsComm*, bool, bool)::$_13>, void ()>::operator()() /opt/irods-externals/clang13.0.1-0/include/c++/v1/__functional/function.h:171:16
    #24 0x57c2dc in std::__1::__function::__func<initServerMain(RsComm*, bool, bool)::$_13, std::__1::allocator<initServerMain(RsComm*, bool, bool)::$_13>, void ()>::operator()() /opt/irods-externals/clang13.0.1-0/include/c++/v1/__functional/function.h:345:12
    #25 0x65c42b in std::__1::__function::__value_func<void ()>::operator()() const /opt/irods-externals/clang13.0.1-0/include/c++/v1/__functional/function.h:498:16
    #26 0x65c42b in std::__1::function<void ()>::operator()() const /opt/irods-externals/clang13.0.1-0/include/c++/v1/__functional/function.h:1175:12
    #27 0x65c42b in irods::experimental::cron::cron_task::operator()() /irods_source/server/core/include/irods/process_manager.hpp:53:13
    #28 0x65bfa7 in irods::experimental::cron::cron::run() /irods_source/server/core/include/irods/process_manager.hpp:208:21
    #29 0x57bef1 in main::$_10::operator()() const /irods_source/server/main_server/src/rodsServer.cpp:1479:44
    #30 0x57bef1 in decltype(static_cast<main::$_10>(fp)()) std::__1::__invoke<main::$_10>(main::$_10&&) /opt/irods-externals/clang13.0.1-0/include/c++/v1/type_traits:3934:1
    #31 0x57bef1 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, main::$_10>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, main::$_10>&, std::__1::__tuple_indices<>) /opt/irods-externals/clang13.0.1-0/include/c++/v1/thread:280:5
    #32 0x57bef1 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, main::$_10> >(void*) /opt/irods-externals/clang13.0.1-0/include/c++/v1/thread:291:5
    #33 0x7ffbba0b8a93  (/lib/x86_64-linux-gnu/libc.so.6+0x9ca93)
    #34 0x7ffbba145a33 in clone (/lib/x86_64-linux-gnu/libc.so.6+0x129a33)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0xc1a10) 
Thread T1 created by T0 here:
    #0 0x492686 in pthread_create /externals/clang13.0.1-0_src/llvm-project/compiler-rt/lib/asan/asan_interceptors.cpp:207:3
    #1 0x55a438 in std::__1::__libcpp_thread_create(unsigned long*, void* (*)(void*), void*) /opt/irods-externals/clang13.0.1-0/include/c++/v1/__threading_support:443:10
    #2 0x55a438 in std::__1::thread::thread<main::$_10, void>(main::$_10&&) /opt/irods-externals/clang13.0.1-0/include/c++/v1/thread:307:16
    #3 0x55a438 in main /irods_source/server/main_server/src/rodsServer.cpp:1465:17
    #4 0x7ffbba0461c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9)
    #5 0x7ffbba04628a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a)
    #6 0x46d8c4 in _start (/usr/sbin/irodsServer+0x46d8c4)

==33039==ABORTING
```

Possibly related to the issues being seen here: https://github.com/irods/irods/issues/6954 This issue will possibly just be closed as invalid for 5.0.0 due to the process model changes which have already occurred there, but I wanted to report this anyway for the record.

**Comment by alanking** [comment]
I'm going to close this since iRODS 5 is much more stable. If this comes up again in 4.3 in the wild, we can open a new issue.
